const scopes = [
  'desktop',
  'mobile',
  'core',
  'docs',
  'openspec',
  'build',
  'deps',
  'git',
  'config',
  'ui',
  'terminal',
  'ssh',
  'ftp',
  'webview',
  'todo',
  'plugins',
  'home',
  'media',
  'notification',
  'tray',
  'tests',
];

const types = [
  'build',
  'feat',
  'fix',
  'docs',
  'style',
  'refactor',
  'perf',
  'test',
  'revert',
  'ci',
  'config',
  'chore',
];

module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [2, 'always', types],
    'type-empty': [2, 'never'],
    'type-case': [2, 'always', 'lower-case'],
    'scope-empty': [0],
    'scope-enum': [1, 'always', scopes],
    'scope-case': [0],
    'subject-empty': [2, 'never'],
    'subject-case': [0],
    'subject-full-stop': [0, 'never', '.'],
    'header-max-length': [2, 'always', 72],
    'body-leading-blank': [2, 'always'],
    'body-max-line-length': [1, 'always', 100],
    'footer-leading-blank': [2, 'always'],
    'footer-max-line-length': [0],
  },
  prompt: {
    messages: {
      type: '选择提交类型:',
      scope: '选择影响范围（可选）:',
      customScope: '请输入自定义范围:',
      subject: '用一句话说明为什么做这次变更:\n',
      body: '补充背景、约束、取舍（可选）。使用 "|" 换行:\n',
      breaking: '列出破坏性变更（可选）。使用 "|" 换行:\n',
      footerPrefixesSelect: '选择 Git trailer / issue 前缀（可选）:',
      customFooterPrefix: '输入自定义 trailer 前缀:',
      footer: '填写 Lore trailer 或关联 issue（可选），例如 "Confidence: high"、"Tested: pnpm test":\n',
      generatingByAI: '正在通过 AI 生成提交描述...',
      generatedSelectByAI: '选择一个 AI 生成的提交描述:',
      confirmCommit: '确认提交?',
    },
    types: [
      { value: 'feat', name: 'feat:     新功能' },
      { value: 'fix', name: 'fix:      缺陷修复' },
      { value: 'docs', name: 'docs:     文档变更' },
      { value: 'style', name: 'style:    代码格式（不影响功能）' },
      { value: 'refactor', name: 'refactor: 重构（不含新功能或修复）' },
      { value: 'perf', name: 'perf:     性能优化' },
      { value: 'test', name: 'test:     测试相关' },
      { value: 'build', name: 'build:    构建系统或外部依赖' },
      { value: 'ci', name: 'ci:       CI 配置' },
      { value: 'config', name: 'config:   项目配置' },
      { value: 'chore', name: 'chore:    维护性改动' },
      { value: 'revert', name: 'revert:   回滚提交' },
    ],
    useEmoji: false,
    useAI: false,
    aiNumber: 1,
    themeColorCode: '',
    scopes: scopes.map((scope) => ({ name: scope, value: scope })),
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    customScopesAlias: 'custom',
    emptyScopesAlias: 'empty',
    upperCaseSubject: false,
    markBreakingChangeMode: false,
    allowBreakingChanges: ['feat', 'fix', 'refactor'],
    breaklineNumber: 100,
    breaklineChar: '|',
    skipQuestions: [],
    issuePrefixes: [
      { value: 'Related', name: 'Related: 关联提交、issue 或决策' },
      { value: 'Constraint', name: 'Constraint: 外部约束' },
      { value: 'Rejected', name: 'Rejected: 被放弃的方案' },
      { value: 'Tested', name: 'Tested: 已验证内容' },
      { value: 'Not-tested', name: 'Not-tested: 未验证风险' },
    ],
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: 'skip',
    customIssuePrefixAlias: 'custom',
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    maxHeaderLength: 72,
    maxSubjectLength: 72,
    minSubjectLength: 4,
    defaultBody: '',
    defaultIssues: '',
    defaultScope: '',
    defaultSubject: '',
  },
};
