// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'bindings/mobile_clipboard.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models/multi_device_clipboard.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 515536374;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'multi_platform_core',
        ioDirectory: '../multi_platform_core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<PlatformInt64>
  crateBindingsMobileClipboardClampMobileClipboardSyncBytes({
    required PlatformInt64 value,
  });

  Future<List<String>> crateBindingsMobileClipboardClassifyMobileClipboardText({
    required String text,
  });

  Future<void> crateBindingsMobileClipboardClearMobileClipboardHistory({
    required String hostId,
  });

  Future<String> crateBindingsMobileClipboardComputeMobileClipboardContentHash({
    required List<String> parts,
  });

  Future<String> crateBindingsMobileClipboardCreateMobileClipboardHost({
    required String dbPath,
  });

  Future<void> crateBindingsMobileClipboardDeleteMobileClipboardItem({
    required String hostId,
    required String id,
  });

  Future<void> crateBindingsMobileClipboardDisposeMobileClipboardHost({
    required String hostId,
  });

  Future<void> crateBindingsMobileClipboardForgetMobileClipboardDevice({
    required String hostId,
    required String id,
  });

  Future<MultiDeviceClipboardItem>
  crateBindingsMobileClipboardGetMobileClipboardItem({
    required String hostId,
    required String id,
  });

  Future<MultiDeviceClipboardDevice>
  crateBindingsMobileClipboardGetOrCreateMobileClipboardLocalDevice({
    required String hostId,
    required String name,
  });

  Future<List<MultiDeviceClipboardDeviceStatus>>
  crateBindingsMobileClipboardListMobileClipboardDeviceStatuses({
    required String hostId,
    required PlatformInt64 onlineWindowSeconds,
  });

  Future<List<MultiDeviceClipboardDevice>>
  crateBindingsMobileClipboardListMobileClipboardDevices({
    required String hostId,
  });

  Future<List<MultiDeviceClipboardDiscoveredDevice>>
  crateBindingsMobileClipboardListMobileClipboardDiscoveredDevices({
    required String hostId,
  });

  Future<List<MultiDeviceClipboardItem>>
  crateBindingsMobileClipboardListMobileClipboardItems({
    required String hostId,
    required PlatformInt64 limit,
  });

  Future<void> crateBindingsMobileClipboardPruneMobileClipboardHistory({
    required String hostId,
    required PlatformInt64 historyLimit,
  });

  Future<MultiDeviceClipboardDevice>
  crateBindingsMobileClipboardSetMobileClipboardDeviceTrusted({
    required String hostId,
    required String id,
    required bool trusted,
  });

  Future<void> crateBindingsMobileClipboardStartMobileClipboardDiscovery({
    required String hostId,
    required MultiDeviceClipboardDiscoveryConfig config,
  });

  Future<void> crateBindingsMobileClipboardStopMobileClipboardDiscovery({
    required String hostId,
  });

  Future<MultiDeviceClipboardDevice>
  crateBindingsMobileClipboardUpsertMobileClipboardDevice({
    required String hostId,
    required UpsertMultiDeviceClipboardDeviceInput input,
  });

  Future<MultiDeviceClipboardItem>
  crateBindingsMobileClipboardUpsertMobileClipboardItem({
    required String hostId,
    required UpsertMultiDeviceClipboardItemInput input,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<PlatformInt64>
  crateBindingsMobileClipboardClampMobileClipboardSyncBytes({
    required PlatformInt64 value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateBindingsMobileClipboardClampMobileClipboardSyncBytesConstMeta,
        argValues: [value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardClampMobileClipboardSyncBytesConstMeta =>
      const TaskConstMeta(
        debugName: "clamp_mobile_clipboard_sync_bytes",
        argNames: ["value"],
      );

  @override
  Future<List<String>> crateBindingsMobileClipboardClassifyMobileClipboardText({
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateBindingsMobileClipboardClassifyMobileClipboardTextConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardClassifyMobileClipboardTextConstMeta =>
      const TaskConstMeta(
        debugName: "classify_mobile_clipboard_text",
        argNames: ["text"],
      );

  @override
  Future<void> crateBindingsMobileClipboardClearMobileClipboardHistory({
    required String hostId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardClearMobileClipboardHistoryConstMeta,
        argValues: [hostId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardClearMobileClipboardHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "clear_mobile_clipboard_history",
        argNames: ["hostId"],
      );

  @override
  Future<String> crateBindingsMobileClipboardComputeMobileClipboardContentHash({
    required List<String> parts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(parts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateBindingsMobileClipboardComputeMobileClipboardContentHashConstMeta,
        argValues: [parts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardComputeMobileClipboardContentHashConstMeta =>
      const TaskConstMeta(
        debugName: "compute_mobile_clipboard_content_hash",
        argNames: ["parts"],
      );

  @override
  Future<String> crateBindingsMobileClipboardCreateMobileClipboardHost({
    required String dbPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardCreateMobileClipboardHostConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardCreateMobileClipboardHostConstMeta =>
      const TaskConstMeta(
        debugName: "create_mobile_clipboard_host",
        argNames: ["dbPath"],
      );

  @override
  Future<void> crateBindingsMobileClipboardDeleteMobileClipboardItem({
    required String hostId,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardDeleteMobileClipboardItemConstMeta,
        argValues: [hostId, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardDeleteMobileClipboardItemConstMeta =>
      const TaskConstMeta(
        debugName: "delete_mobile_clipboard_item",
        argNames: ["hostId", "id"],
      );

  @override
  Future<void> crateBindingsMobileClipboardDisposeMobileClipboardHost({
    required String hostId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardDisposeMobileClipboardHostConstMeta,
        argValues: [hostId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardDisposeMobileClipboardHostConstMeta =>
      const TaskConstMeta(
        debugName: "dispose_mobile_clipboard_host",
        argNames: ["hostId"],
      );

  @override
  Future<void> crateBindingsMobileClipboardForgetMobileClipboardDevice({
    required String hostId,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardForgetMobileClipboardDeviceConstMeta,
        argValues: [hostId, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardForgetMobileClipboardDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "forget_mobile_clipboard_device",
        argNames: ["hostId", "id"],
      );

  @override
  Future<MultiDeviceClipboardItem>
  crateBindingsMobileClipboardGetMobileClipboardItem({
    required String hostId,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_multi_device_clipboard_item,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileClipboardGetMobileClipboardItemConstMeta,
        argValues: [hostId, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardGetMobileClipboardItemConstMeta =>
      const TaskConstMeta(
        debugName: "get_mobile_clipboard_item",
        argNames: ["hostId", "id"],
      );

  @override
  Future<MultiDeviceClipboardDevice>
  crateBindingsMobileClipboardGetOrCreateMobileClipboardLocalDevice({
    required String hostId,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_multi_device_clipboard_device,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardGetOrCreateMobileClipboardLocalDeviceConstMeta,
        argValues: [hostId, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardGetOrCreateMobileClipboardLocalDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "get_or_create_mobile_clipboard_local_device",
        argNames: ["hostId", "name"],
      );

  @override
  Future<List<MultiDeviceClipboardDeviceStatus>>
  crateBindingsMobileClipboardListMobileClipboardDeviceStatuses({
    required String hostId,
    required PlatformInt64 onlineWindowSeconds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_i_64(onlineWindowSeconds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_list_multi_device_clipboard_device_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardListMobileClipboardDeviceStatusesConstMeta,
        argValues: [hostId, onlineWindowSeconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardListMobileClipboardDeviceStatusesConstMeta =>
      const TaskConstMeta(
        debugName: "list_mobile_clipboard_device_statuses",
        argNames: ["hostId", "onlineWindowSeconds"],
      );

  @override
  Future<List<MultiDeviceClipboardDevice>>
  crateBindingsMobileClipboardListMobileClipboardDevices({
    required String hostId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_multi_device_clipboard_device,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardListMobileClipboardDevicesConstMeta,
        argValues: [hostId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardListMobileClipboardDevicesConstMeta =>
      const TaskConstMeta(
        debugName: "list_mobile_clipboard_devices",
        argNames: ["hostId"],
      );

  @override
  Future<List<MultiDeviceClipboardDiscoveredDevice>>
  crateBindingsMobileClipboardListMobileClipboardDiscoveredDevices({
    required String hostId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_list_multi_device_clipboard_discovered_device,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardListMobileClipboardDiscoveredDevicesConstMeta,
        argValues: [hostId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardListMobileClipboardDiscoveredDevicesConstMeta =>
      const TaskConstMeta(
        debugName: "list_mobile_clipboard_discovered_devices",
        argNames: ["hostId"],
      );

  @override
  Future<List<MultiDeviceClipboardItem>>
  crateBindingsMobileClipboardListMobileClipboardItems({
    required String hostId,
    required PlatformInt64 limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_i_64(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_multi_device_clipboard_item,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardListMobileClipboardItemsConstMeta,
        argValues: [hostId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardListMobileClipboardItemsConstMeta =>
      const TaskConstMeta(
        debugName: "list_mobile_clipboard_items",
        argNames: ["hostId", "limit"],
      );

  @override
  Future<void> crateBindingsMobileClipboardPruneMobileClipboardHistory({
    required String hostId,
    required PlatformInt64 historyLimit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_i_64(historyLimit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardPruneMobileClipboardHistoryConstMeta,
        argValues: [hostId, historyLimit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardPruneMobileClipboardHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "prune_mobile_clipboard_history",
        argNames: ["hostId", "historyLimit"],
      );

  @override
  Future<MultiDeviceClipboardDevice>
  crateBindingsMobileClipboardSetMobileClipboardDeviceTrusted({
    required String hostId,
    required String id,
    required bool trusted,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_String(id, serializer);
          sse_encode_bool(trusted, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_multi_device_clipboard_device,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardSetMobileClipboardDeviceTrustedConstMeta,
        argValues: [hostId, id, trusted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardSetMobileClipboardDeviceTrustedConstMeta =>
      const TaskConstMeta(
        debugName: "set_mobile_clipboard_device_trusted",
        argNames: ["hostId", "id", "trusted"],
      );

  @override
  Future<void> crateBindingsMobileClipboardStartMobileClipboardDiscovery({
    required String hostId,
    required MultiDeviceClipboardDiscoveryConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_box_autoadd_multi_device_clipboard_discovery_config(
            config,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardStartMobileClipboardDiscoveryConstMeta,
        argValues: [hostId, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardStartMobileClipboardDiscoveryConstMeta =>
      const TaskConstMeta(
        debugName: "start_mobile_clipboard_discovery",
        argNames: ["hostId", "config"],
      );

  @override
  Future<void> crateBindingsMobileClipboardStopMobileClipboardDiscovery({
    required String hostId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardStopMobileClipboardDiscoveryConstMeta,
        argValues: [hostId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardStopMobileClipboardDiscoveryConstMeta =>
      const TaskConstMeta(
        debugName: "stop_mobile_clipboard_discovery",
        argNames: ["hostId"],
      );

  @override
  Future<MultiDeviceClipboardDevice>
  crateBindingsMobileClipboardUpsertMobileClipboardDevice({
    required String hostId,
    required UpsertMultiDeviceClipboardDeviceInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_box_autoadd_upsert_multi_device_clipboard_device_input(
            input,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_multi_device_clipboard_device,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardUpsertMobileClipboardDeviceConstMeta,
        argValues: [hostId, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardUpsertMobileClipboardDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "upsert_mobile_clipboard_device",
        argNames: ["hostId", "input"],
      );

  @override
  Future<MultiDeviceClipboardItem>
  crateBindingsMobileClipboardUpsertMobileClipboardItem({
    required String hostId,
    required UpsertMultiDeviceClipboardItemInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_box_autoadd_upsert_multi_device_clipboard_item_input(
            input,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_multi_device_clipboard_item,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileClipboardUpsertMobileClipboardItemConstMeta,
        argValues: [hostId, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileClipboardUpsertMobileClipboardItemConstMeta =>
      const TaskConstMeta(
        debugName: "upsert_mobile_clipboard_item",
        argNames: ["hostId", "input"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  MultiDeviceClipboardDiscoveryConfig
  dco_decode_box_autoadd_multi_device_clipboard_discovery_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_multi_device_clipboard_discovery_config(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  UpsertMultiDeviceClipboardDeviceInput
  dco_decode_box_autoadd_upsert_multi_device_clipboard_device_input(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_upsert_multi_device_clipboard_device_input(raw);
  }

  @protected
  UpsertMultiDeviceClipboardItemInput
  dco_decode_box_autoadd_upsert_multi_device_clipboard_item_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_upsert_multi_device_clipboard_item_input(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MultiDeviceClipboardDevice>
  dco_decode_list_multi_device_clipboard_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_multi_device_clipboard_device)
        .toList();
  }

  @protected
  List<MultiDeviceClipboardDeviceStatus>
  dco_decode_list_multi_device_clipboard_device_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_multi_device_clipboard_device_status)
        .toList();
  }

  @protected
  List<MultiDeviceClipboardDiscoveredDevice>
  dco_decode_list_multi_device_clipboard_discovered_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_multi_device_clipboard_discovered_device)
        .toList();
  }

  @protected
  List<MultiDeviceClipboardItem> dco_decode_list_multi_device_clipboard_item(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_multi_device_clipboard_item)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MultiDeviceClipboardDevice dco_decode_multi_device_clipboard_device(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return MultiDeviceClipboardDevice(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      platform: dco_decode_String(arr[2]),
      publicKey: dco_decode_opt_String(arr[3]),
      trusted: dco_decode_bool(arr[4]),
      isSelf: dco_decode_bool(arr[5]),
      lastAddress: dco_decode_opt_String(arr[6]),
      lastPort: dco_decode_opt_box_autoadd_u_32(arr[7]),
      lastSeenAt: dco_decode_opt_box_autoadd_i_64(arr[8]),
      createdAt: dco_decode_i_64(arr[9]),
      updatedAt: dco_decode_i_64(arr[10]),
    );
  }

  @protected
  MultiDeviceClipboardDeviceStatus
  dco_decode_multi_device_clipboard_device_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return MultiDeviceClipboardDeviceStatus(
      deviceId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      platform: dco_decode_String(arr[2]),
      trusted: dco_decode_bool(arr[3]),
      isSelf: dco_decode_bool(arr[4]),
      state: dco_decode_String(arr[5]),
      online: dco_decode_bool(arr[6]),
      lastAddress: dco_decode_opt_String(arr[7]),
      lastPort: dco_decode_opt_box_autoadd_u_32(arr[8]),
      lastSeenAt: dco_decode_opt_box_autoadd_i_64(arr[9]),
      secondsSinceSeen: dco_decode_opt_box_autoadd_i_64(arr[10]),
    );
  }

  @protected
  MultiDeviceClipboardDiscoveredDevice
  dco_decode_multi_device_clipboard_discovered_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MultiDeviceClipboardDiscoveredDevice(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      platform: dco_decode_String(arr[2]),
      address: dco_decode_String(arr[3]),
      port: dco_decode_u_32(arr[4]),
      serviceName: dco_decode_String(arr[5]),
      lastSeenAt: dco_decode_i_64(arr[6]),
    );
  }

  @protected
  MultiDeviceClipboardDiscoveryConfig
  dco_decode_multi_device_clipboard_discovery_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MultiDeviceClipboardDiscoveryConfig(
      deviceId: dco_decode_String(arr[0]),
      deviceName: dco_decode_String(arr[1]),
      port: dco_decode_u_32(arr[2]),
      platform: dco_decode_opt_String(arr[3]),
      preferredAddress: dco_decode_opt_String(arr[4]),
      probeLocalAddresses: dco_decode_list_String(arr[5]),
      httpProbeEnabled: dco_decode_opt_box_autoadd_bool(arr[6]),
    );
  }

  @protected
  MultiDeviceClipboardItem dco_decode_multi_device_clipboard_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return MultiDeviceClipboardItem(
      id: dco_decode_String(arr[0]),
      sourceDeviceId: dco_decode_String(arr[1]),
      sourceDeviceName: dco_decode_String(arr[2]),
      contentType: dco_decode_String(arr[3]),
      mimeType: dco_decode_opt_String(arr[4]),
      text: dco_decode_opt_String(arr[5]),
      fileName: dco_decode_opt_String(arr[6]),
      assetPath: dco_decode_opt_String(arr[7]),
      previewPath: dco_decode_opt_String(arr[8]),
      byteSize: dco_decode_i_64(arr[9]),
      contentHash: dco_decode_String(arr[10]),
      tagsJson: dco_decode_String(arr[11]),
      localOnly: dco_decode_bool(arr[12]),
      createdAt: dco_decode_i_64(arr[13]),
      updatedAt: dco_decode_i_64(arr[14]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UpsertMultiDeviceClipboardDeviceInput
  dco_decode_upsert_multi_device_clipboard_device_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return UpsertMultiDeviceClipboardDeviceInput(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      platform: dco_decode_opt_String(arr[2]),
      publicKey: dco_decode_opt_String(arr[3]),
      trusted: dco_decode_opt_box_autoadd_bool(arr[4]),
      isSelf: dco_decode_opt_box_autoadd_bool(arr[5]),
      lastAddress: dco_decode_opt_String(arr[6]),
      lastPort: dco_decode_opt_box_autoadd_u_32(arr[7]),
      lastSeenAt: dco_decode_opt_box_autoadd_i_64(arr[8]),
    );
  }

  @protected
  UpsertMultiDeviceClipboardItemInput
  dco_decode_upsert_multi_device_clipboard_item_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return UpsertMultiDeviceClipboardItemInput(
      id: dco_decode_String(arr[0]),
      sourceDeviceId: dco_decode_String(arr[1]),
      sourceDeviceName: dco_decode_String(arr[2]),
      contentType: dco_decode_String(arr[3]),
      mimeType: dco_decode_opt_String(arr[4]),
      text: dco_decode_opt_String(arr[5]),
      fileName: dco_decode_opt_String(arr[6]),
      assetPath: dco_decode_opt_String(arr[7]),
      previewPath: dco_decode_opt_String(arr[8]),
      byteSize: dco_decode_opt_box_autoadd_i_64(arr[9]),
      contentHash: dco_decode_String(arr[10]),
      tagsJson: dco_decode_opt_String(arr[11]),
      localOnly: dco_decode_opt_box_autoadd_bool(arr[12]),
      createdAt: dco_decode_opt_box_autoadd_i_64(arr[13]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  MultiDeviceClipboardDiscoveryConfig
  sse_decode_box_autoadd_multi_device_clipboard_discovery_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_multi_device_clipboard_discovery_config(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  UpsertMultiDeviceClipboardDeviceInput
  sse_decode_box_autoadd_upsert_multi_device_clipboard_device_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_upsert_multi_device_clipboard_device_input(
      deserializer,
    ));
  }

  @protected
  UpsertMultiDeviceClipboardItemInput
  sse_decode_box_autoadd_upsert_multi_device_clipboard_item_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_upsert_multi_device_clipboard_item_input(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MultiDeviceClipboardDevice>
  sse_decode_list_multi_device_clipboard_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MultiDeviceClipboardDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_multi_device_clipboard_device(deserializer));
    }
    return ans_;
  }

  @protected
  List<MultiDeviceClipboardDeviceStatus>
  sse_decode_list_multi_device_clipboard_device_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MultiDeviceClipboardDeviceStatus>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_multi_device_clipboard_device_status(deserializer));
    }
    return ans_;
  }

  @protected
  List<MultiDeviceClipboardDiscoveredDevice>
  sse_decode_list_multi_device_clipboard_discovered_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MultiDeviceClipboardDiscoveredDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_multi_device_clipboard_discovered_device(deserializer),
      );
    }
    return ans_;
  }

  @protected
  List<MultiDeviceClipboardItem> sse_decode_list_multi_device_clipboard_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MultiDeviceClipboardItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_multi_device_clipboard_item(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MultiDeviceClipboardDevice sse_decode_multi_device_clipboard_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_platform = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_opt_String(deserializer);
    var var_trusted = sse_decode_bool(deserializer);
    var var_isSelf = sse_decode_bool(deserializer);
    var var_lastAddress = sse_decode_opt_String(deserializer);
    var var_lastPort = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_lastSeenAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return MultiDeviceClipboardDevice(
      id: var_id,
      name: var_name,
      platform: var_platform,
      publicKey: var_publicKey,
      trusted: var_trusted,
      isSelf: var_isSelf,
      lastAddress: var_lastAddress,
      lastPort: var_lastPort,
      lastSeenAt: var_lastSeenAt,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  MultiDeviceClipboardDeviceStatus
  sse_decode_multi_device_clipboard_device_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_platform = sse_decode_String(deserializer);
    var var_trusted = sse_decode_bool(deserializer);
    var var_isSelf = sse_decode_bool(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_online = sse_decode_bool(deserializer);
    var var_lastAddress = sse_decode_opt_String(deserializer);
    var var_lastPort = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_lastSeenAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_secondsSinceSeen = sse_decode_opt_box_autoadd_i_64(deserializer);
    return MultiDeviceClipboardDeviceStatus(
      deviceId: var_deviceId,
      name: var_name,
      platform: var_platform,
      trusted: var_trusted,
      isSelf: var_isSelf,
      state: var_state,
      online: var_online,
      lastAddress: var_lastAddress,
      lastPort: var_lastPort,
      lastSeenAt: var_lastSeenAt,
      secondsSinceSeen: var_secondsSinceSeen,
    );
  }

  @protected
  MultiDeviceClipboardDiscoveredDevice
  sse_decode_multi_device_clipboard_discovered_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_platform = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_port = sse_decode_u_32(deserializer);
    var var_serviceName = sse_decode_String(deserializer);
    var var_lastSeenAt = sse_decode_i_64(deserializer);
    return MultiDeviceClipboardDiscoveredDevice(
      id: var_id,
      name: var_name,
      platform: var_platform,
      address: var_address,
      port: var_port,
      serviceName: var_serviceName,
      lastSeenAt: var_lastSeenAt,
    );
  }

  @protected
  MultiDeviceClipboardDiscoveryConfig
  sse_decode_multi_device_clipboard_discovery_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_port = sse_decode_u_32(deserializer);
    var var_platform = sse_decode_opt_String(deserializer);
    var var_preferredAddress = sse_decode_opt_String(deserializer);
    var var_probeLocalAddresses = sse_decode_list_String(deserializer);
    var var_httpProbeEnabled = sse_decode_opt_box_autoadd_bool(deserializer);
    return MultiDeviceClipboardDiscoveryConfig(
      deviceId: var_deviceId,
      deviceName: var_deviceName,
      port: var_port,
      platform: var_platform,
      preferredAddress: var_preferredAddress,
      probeLocalAddresses: var_probeLocalAddresses,
      httpProbeEnabled: var_httpProbeEnabled,
    );
  }

  @protected
  MultiDeviceClipboardItem sse_decode_multi_device_clipboard_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sourceDeviceId = sse_decode_String(deserializer);
    var var_sourceDeviceName = sse_decode_String(deserializer);
    var var_contentType = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_opt_String(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_fileName = sse_decode_opt_String(deserializer);
    var var_assetPath = sse_decode_opt_String(deserializer);
    var var_previewPath = sse_decode_opt_String(deserializer);
    var var_byteSize = sse_decode_i_64(deserializer);
    var var_contentHash = sse_decode_String(deserializer);
    var var_tagsJson = sse_decode_String(deserializer);
    var var_localOnly = sse_decode_bool(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return MultiDeviceClipboardItem(
      id: var_id,
      sourceDeviceId: var_sourceDeviceId,
      sourceDeviceName: var_sourceDeviceName,
      contentType: var_contentType,
      mimeType: var_mimeType,
      text: var_text,
      fileName: var_fileName,
      assetPath: var_assetPath,
      previewPath: var_previewPath,
      byteSize: var_byteSize,
      contentHash: var_contentHash,
      tagsJson: var_tagsJson,
      localOnly: var_localOnly,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UpsertMultiDeviceClipboardDeviceInput
  sse_decode_upsert_multi_device_clipboard_device_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_platform = sse_decode_opt_String(deserializer);
    var var_publicKey = sse_decode_opt_String(deserializer);
    var var_trusted = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_isSelf = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_lastAddress = sse_decode_opt_String(deserializer);
    var var_lastPort = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_lastSeenAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    return UpsertMultiDeviceClipboardDeviceInput(
      id: var_id,
      name: var_name,
      platform: var_platform,
      publicKey: var_publicKey,
      trusted: var_trusted,
      isSelf: var_isSelf,
      lastAddress: var_lastAddress,
      lastPort: var_lastPort,
      lastSeenAt: var_lastSeenAt,
    );
  }

  @protected
  UpsertMultiDeviceClipboardItemInput
  sse_decode_upsert_multi_device_clipboard_item_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sourceDeviceId = sse_decode_String(deserializer);
    var var_sourceDeviceName = sse_decode_String(deserializer);
    var var_contentType = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_opt_String(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_fileName = sse_decode_opt_String(deserializer);
    var var_assetPath = sse_decode_opt_String(deserializer);
    var var_previewPath = sse_decode_opt_String(deserializer);
    var var_byteSize = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_contentHash = sse_decode_String(deserializer);
    var var_tagsJson = sse_decode_opt_String(deserializer);
    var var_localOnly = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_createdAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    return UpsertMultiDeviceClipboardItemInput(
      id: var_id,
      sourceDeviceId: var_sourceDeviceId,
      sourceDeviceName: var_sourceDeviceName,
      contentType: var_contentType,
      mimeType: var_mimeType,
      text: var_text,
      fileName: var_fileName,
      assetPath: var_assetPath,
      previewPath: var_previewPath,
      byteSize: var_byteSize,
      contentHash: var_contentHash,
      tagsJson: var_tagsJson,
      localOnly: var_localOnly,
      createdAt: var_createdAt,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_multi_device_clipboard_discovery_config(
    MultiDeviceClipboardDiscoveryConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_multi_device_clipboard_discovery_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_upsert_multi_device_clipboard_device_input(
    UpsertMultiDeviceClipboardDeviceInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_upsert_multi_device_clipboard_device_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_upsert_multi_device_clipboard_item_input(
    UpsertMultiDeviceClipboardItemInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_upsert_multi_device_clipboard_item_input(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_multi_device_clipboard_device(
    List<MultiDeviceClipboardDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_multi_device_clipboard_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_multi_device_clipboard_device_status(
    List<MultiDeviceClipboardDeviceStatus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_multi_device_clipboard_device_status(item, serializer);
    }
  }

  @protected
  void sse_encode_list_multi_device_clipboard_discovered_device(
    List<MultiDeviceClipboardDiscoveredDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_multi_device_clipboard_discovered_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_multi_device_clipboard_item(
    List<MultiDeviceClipboardItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_multi_device_clipboard_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_multi_device_clipboard_device(
    MultiDeviceClipboardDevice self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.platform, serializer);
    sse_encode_opt_String(self.publicKey, serializer);
    sse_encode_bool(self.trusted, serializer);
    sse_encode_bool(self.isSelf, serializer);
    sse_encode_opt_String(self.lastAddress, serializer);
    sse_encode_opt_box_autoadd_u_32(self.lastPort, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastSeenAt, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_multi_device_clipboard_device_status(
    MultiDeviceClipboardDeviceStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.platform, serializer);
    sse_encode_bool(self.trusted, serializer);
    sse_encode_bool(self.isSelf, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_bool(self.online, serializer);
    sse_encode_opt_String(self.lastAddress, serializer);
    sse_encode_opt_box_autoadd_u_32(self.lastPort, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastSeenAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.secondsSinceSeen, serializer);
  }

  @protected
  void sse_encode_multi_device_clipboard_discovered_device(
    MultiDeviceClipboardDiscoveredDevice self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.platform, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_u_32(self.port, serializer);
    sse_encode_String(self.serviceName, serializer);
    sse_encode_i_64(self.lastSeenAt, serializer);
  }

  @protected
  void sse_encode_multi_device_clipboard_discovery_config(
    MultiDeviceClipboardDiscoveryConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_u_32(self.port, serializer);
    sse_encode_opt_String(self.platform, serializer);
    sse_encode_opt_String(self.preferredAddress, serializer);
    sse_encode_list_String(self.probeLocalAddresses, serializer);
    sse_encode_opt_box_autoadd_bool(self.httpProbeEnabled, serializer);
  }

  @protected
  void sse_encode_multi_device_clipboard_item(
    MultiDeviceClipboardItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.sourceDeviceId, serializer);
    sse_encode_String(self.sourceDeviceName, serializer);
    sse_encode_String(self.contentType, serializer);
    sse_encode_opt_String(self.mimeType, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.fileName, serializer);
    sse_encode_opt_String(self.assetPath, serializer);
    sse_encode_opt_String(self.previewPath, serializer);
    sse_encode_i_64(self.byteSize, serializer);
    sse_encode_String(self.contentHash, serializer);
    sse_encode_String(self.tagsJson, serializer);
    sse_encode_bool(self.localOnly, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_upsert_multi_device_clipboard_device_input(
    UpsertMultiDeviceClipboardDeviceInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.platform, serializer);
    sse_encode_opt_String(self.publicKey, serializer);
    sse_encode_opt_box_autoadd_bool(self.trusted, serializer);
    sse_encode_opt_box_autoadd_bool(self.isSelf, serializer);
    sse_encode_opt_String(self.lastAddress, serializer);
    sse_encode_opt_box_autoadd_u_32(self.lastPort, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastSeenAt, serializer);
  }

  @protected
  void sse_encode_upsert_multi_device_clipboard_item_input(
    UpsertMultiDeviceClipboardItemInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.sourceDeviceId, serializer);
    sse_encode_String(self.sourceDeviceName, serializer);
    sse_encode_String(self.contentType, serializer);
    sse_encode_opt_String(self.mimeType, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.fileName, serializer);
    sse_encode_opt_String(self.assetPath, serializer);
    sse_encode_opt_String(self.previewPath, serializer);
    sse_encode_opt_box_autoadd_i_64(self.byteSize, serializer);
    sse_encode_String(self.contentHash, serializer);
    sse_encode_opt_String(self.tagsJson, serializer);
    sse_encode_opt_box_autoadd_bool(self.localOnly, serializer);
    sse_encode_opt_box_autoadd_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
