// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'bindings/mobile_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models/home_layout.dart';
import 'models/multi_device_clipboard.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 397776622;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'multi_platform_core',
        ioDirectory: '../multi_platform_core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<PlatformInt64> crateBindingsMobileApiClampMobileClipboardSyncBytes({
    required PlatformInt64 value,
  });

  Future<List<String>> crateBindingsMobileApiClassifyMobileClipboardText({
    required String text,
  });

  Future<void> crateBindingsMobileApiClearMobileClipboardHistory({
    required String hostId,
  });

  Future<String> crateBindingsMobileApiComputeMobileClipboardContentHash({
    required List<String> parts,
  });

  Future<String> crateBindingsMobileApiCreateMobileClipboardHost({
    required String dbPath,
  });

  Future<void> crateBindingsMobileApiDeleteMobileClipboardItem({
    required String hostId,
    required String id,
  });

  Future<void> crateBindingsMobileApiDisposeMobileClipboardHost({
    required String hostId,
  });

  Future<void> crateBindingsMobileApiForgetMobileClipboardDevice({
    required String hostId,
    required String id,
  });

  Future<MultiDeviceClipboardItem>
  crateBindingsMobileApiGetMobileClipboardItem({
    required String hostId,
    required String id,
  });

  Future<HomeLayout> crateBindingsMobileApiGetMobileHomeLayout({
    required String dbPath,
    required String workspaceKey,
    required String layoutScope,
  });

  Future<MultiDeviceClipboardDevice>
  crateBindingsMobileApiGetOrCreateMobileClipboardLocalDevice({
    required String hostId,
    required String name,
  });

  Future<List<MultiDeviceClipboardDeviceStatus>>
  crateBindingsMobileApiListMobileClipboardDeviceStatuses({
    required String hostId,
    required PlatformInt64 onlineWindowSeconds,
  });

  Future<List<MultiDeviceClipboardDevice>>
  crateBindingsMobileApiListMobileClipboardDevices({required String hostId});

  Future<List<MultiDeviceClipboardDiscoveredDevice>>
  crateBindingsMobileApiListMobileClipboardDiscoveredDevices({
    required String hostId,
  });

  Future<List<MultiDeviceClipboardItem>>
  crateBindingsMobileApiListMobileClipboardItems({
    required String hostId,
    required PlatformInt64 limit,
  });

  Future<void> crateBindingsMobileApiPruneMobileClipboardHistory({
    required String hostId,
    required PlatformInt64 historyLimit,
  });

  Future<HomeLayoutCategory> crateBindingsMobileApiResetMobileCategoryLayout({
    required String dbPath,
    required String workspaceKey,
    required String layoutScope,
    required String categoryId,
  });

  Future<HomeLayoutCategory> crateBindingsMobileApiSaveMobileCategoryLayout({
    required String dbPath,
    required String workspaceKey,
    required String layoutScope,
    required SaveMobileHomeCategoryLayoutInput input,
  });

  Future<MultiDeviceClipboardDevice>
  crateBindingsMobileApiSetMobileClipboardDeviceTrusted({
    required String hostId,
    required String id,
    required bool trusted,
  });

  Future<void> crateBindingsMobileApiStartMobileClipboardDiscovery({
    required String hostId,
    required MultiDeviceClipboardDiscoveryConfig config,
  });

  Future<void> crateBindingsMobileApiStopMobileClipboardDiscovery({
    required String hostId,
  });

  Future<MultiDeviceClipboardDevice>
  crateBindingsMobileApiUpsertMobileClipboardDevice({
    required String hostId,
    required UpsertMultiDeviceClipboardDeviceInput input,
  });

  Future<MultiDeviceClipboardItem>
  crateBindingsMobileApiUpsertMobileClipboardItem({
    required String hostId,
    required UpsertMultiDeviceClipboardItemInput input,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<PlatformInt64> crateBindingsMobileApiClampMobileClipboardSyncBytes({
    required PlatformInt64 value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateBindingsMobileApiClampMobileClipboardSyncBytesConstMeta,
        argValues: [value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiClampMobileClipboardSyncBytesConstMeta =>
      const TaskConstMeta(
        debugName: "clamp_mobile_clipboard_sync_bytes",
        argNames: ["value"],
      );

  @override
  Future<List<String>> crateBindingsMobileApiClassifyMobileClipboardText({
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateBindingsMobileApiClassifyMobileClipboardTextConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiClassifyMobileClipboardTextConstMeta =>
      const TaskConstMeta(
        debugName: "classify_mobile_clipboard_text",
        argNames: ["text"],
      );

  @override
  Future<void> crateBindingsMobileApiClearMobileClipboardHistory({
    required String hostId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiClearMobileClipboardHistoryConstMeta,
        argValues: [hostId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiClearMobileClipboardHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "clear_mobile_clipboard_history",
        argNames: ["hostId"],
      );

  @override
  Future<String> crateBindingsMobileApiComputeMobileClipboardContentHash({
    required List<String> parts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(parts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateBindingsMobileApiComputeMobileClipboardContentHashConstMeta,
        argValues: [parts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiComputeMobileClipboardContentHashConstMeta =>
      const TaskConstMeta(
        debugName: "compute_mobile_clipboard_content_hash",
        argNames: ["parts"],
      );

  @override
  Future<String> crateBindingsMobileApiCreateMobileClipboardHost({
    required String dbPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiCreateMobileClipboardHostConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBindingsMobileApiCreateMobileClipboardHostConstMeta =>
      const TaskConstMeta(
        debugName: "create_mobile_clipboard_host",
        argNames: ["dbPath"],
      );

  @override
  Future<void> crateBindingsMobileApiDeleteMobileClipboardItem({
    required String hostId,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiDeleteMobileClipboardItemConstMeta,
        argValues: [hostId, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBindingsMobileApiDeleteMobileClipboardItemConstMeta =>
      const TaskConstMeta(
        debugName: "delete_mobile_clipboard_item",
        argNames: ["hostId", "id"],
      );

  @override
  Future<void> crateBindingsMobileApiDisposeMobileClipboardHost({
    required String hostId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiDisposeMobileClipboardHostConstMeta,
        argValues: [hostId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiDisposeMobileClipboardHostConstMeta =>
      const TaskConstMeta(
        debugName: "dispose_mobile_clipboard_host",
        argNames: ["hostId"],
      );

  @override
  Future<void> crateBindingsMobileApiForgetMobileClipboardDevice({
    required String hostId,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiForgetMobileClipboardDeviceConstMeta,
        argValues: [hostId, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiForgetMobileClipboardDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "forget_mobile_clipboard_device",
        argNames: ["hostId", "id"],
      );

  @override
  Future<MultiDeviceClipboardItem>
  crateBindingsMobileApiGetMobileClipboardItem({
    required String hostId,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_multi_device_clipboard_item,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiGetMobileClipboardItemConstMeta,
        argValues: [hostId, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBindingsMobileApiGetMobileClipboardItemConstMeta =>
      const TaskConstMeta(
        debugName: "get_mobile_clipboard_item",
        argNames: ["hostId", "id"],
      );

  @override
  Future<HomeLayout> crateBindingsMobileApiGetMobileHomeLayout({
    required String dbPath,
    required String workspaceKey,
    required String layoutScope,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(workspaceKey, serializer);
          sse_encode_String(layoutScope, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_home_layout,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiGetMobileHomeLayoutConstMeta,
        argValues: [dbPath, workspaceKey, layoutScope],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBindingsMobileApiGetMobileHomeLayoutConstMeta =>
      const TaskConstMeta(
        debugName: "get_mobile_home_layout",
        argNames: ["dbPath", "workspaceKey", "layoutScope"],
      );

  @override
  Future<MultiDeviceClipboardDevice>
  crateBindingsMobileApiGetOrCreateMobileClipboardLocalDevice({
    required String hostId,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_multi_device_clipboard_device,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileApiGetOrCreateMobileClipboardLocalDeviceConstMeta,
        argValues: [hostId, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiGetOrCreateMobileClipboardLocalDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "get_or_create_mobile_clipboard_local_device",
        argNames: ["hostId", "name"],
      );

  @override
  Future<List<MultiDeviceClipboardDeviceStatus>>
  crateBindingsMobileApiListMobileClipboardDeviceStatuses({
    required String hostId,
    required PlatformInt64 onlineWindowSeconds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_i_64(onlineWindowSeconds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_list_multi_device_clipboard_device_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileApiListMobileClipboardDeviceStatusesConstMeta,
        argValues: [hostId, onlineWindowSeconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiListMobileClipboardDeviceStatusesConstMeta =>
      const TaskConstMeta(
        debugName: "list_mobile_clipboard_device_statuses",
        argNames: ["hostId", "onlineWindowSeconds"],
      );

  @override
  Future<List<MultiDeviceClipboardDevice>>
  crateBindingsMobileApiListMobileClipboardDevices({required String hostId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_multi_device_clipboard_device,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiListMobileClipboardDevicesConstMeta,
        argValues: [hostId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiListMobileClipboardDevicesConstMeta =>
      const TaskConstMeta(
        debugName: "list_mobile_clipboard_devices",
        argNames: ["hostId"],
      );

  @override
  Future<List<MultiDeviceClipboardDiscoveredDevice>>
  crateBindingsMobileApiListMobileClipboardDiscoveredDevices({
    required String hostId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_list_multi_device_clipboard_discovered_device,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileApiListMobileClipboardDiscoveredDevicesConstMeta,
        argValues: [hostId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiListMobileClipboardDiscoveredDevicesConstMeta =>
      const TaskConstMeta(
        debugName: "list_mobile_clipboard_discovered_devices",
        argNames: ["hostId"],
      );

  @override
  Future<List<MultiDeviceClipboardItem>>
  crateBindingsMobileApiListMobileClipboardItems({
    required String hostId,
    required PlatformInt64 limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_i_64(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_multi_device_clipboard_item,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiListMobileClipboardItemsConstMeta,
        argValues: [hostId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBindingsMobileApiListMobileClipboardItemsConstMeta =>
      const TaskConstMeta(
        debugName: "list_mobile_clipboard_items",
        argNames: ["hostId", "limit"],
      );

  @override
  Future<void> crateBindingsMobileApiPruneMobileClipboardHistory({
    required String hostId,
    required PlatformInt64 historyLimit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_i_64(historyLimit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiPruneMobileClipboardHistoryConstMeta,
        argValues: [hostId, historyLimit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiPruneMobileClipboardHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "prune_mobile_clipboard_history",
        argNames: ["hostId", "historyLimit"],
      );

  @override
  Future<HomeLayoutCategory> crateBindingsMobileApiResetMobileCategoryLayout({
    required String dbPath,
    required String workspaceKey,
    required String layoutScope,
    required String categoryId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(workspaceKey, serializer);
          sse_encode_String(layoutScope, serializer);
          sse_encode_String(categoryId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_home_layout_category,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiResetMobileCategoryLayoutConstMeta,
        argValues: [dbPath, workspaceKey, layoutScope, categoryId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBindingsMobileApiResetMobileCategoryLayoutConstMeta =>
      const TaskConstMeta(
        debugName: "reset_mobile_category_layout",
        argNames: ["dbPath", "workspaceKey", "layoutScope", "categoryId"],
      );

  @override
  Future<HomeLayoutCategory> crateBindingsMobileApiSaveMobileCategoryLayout({
    required String dbPath,
    required String workspaceKey,
    required String layoutScope,
    required SaveMobileHomeCategoryLayoutInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(workspaceKey, serializer);
          sse_encode_String(layoutScope, serializer);
          sse_encode_box_autoadd_save_mobile_home_category_layout_input(
            input,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_home_layout_category,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiSaveMobileCategoryLayoutConstMeta,
        argValues: [dbPath, workspaceKey, layoutScope, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBindingsMobileApiSaveMobileCategoryLayoutConstMeta =>
      const TaskConstMeta(
        debugName: "save_mobile_category_layout",
        argNames: ["dbPath", "workspaceKey", "layoutScope", "input"],
      );

  @override
  Future<MultiDeviceClipboardDevice>
  crateBindingsMobileApiSetMobileClipboardDeviceTrusted({
    required String hostId,
    required String id,
    required bool trusted,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_String(id, serializer);
          sse_encode_bool(trusted, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_multi_device_clipboard_device,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileApiSetMobileClipboardDeviceTrustedConstMeta,
        argValues: [hostId, id, trusted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiSetMobileClipboardDeviceTrustedConstMeta =>
      const TaskConstMeta(
        debugName: "set_mobile_clipboard_device_trusted",
        argNames: ["hostId", "id", "trusted"],
      );

  @override
  Future<void> crateBindingsMobileApiStartMobileClipboardDiscovery({
    required String hostId,
    required MultiDeviceClipboardDiscoveryConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_box_autoadd_multi_device_clipboard_discovery_config(
            config,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta:
            kCrateBindingsMobileApiStartMobileClipboardDiscoveryConstMeta,
        argValues: [hostId, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiStartMobileClipboardDiscoveryConstMeta =>
      const TaskConstMeta(
        debugName: "start_mobile_clipboard_discovery",
        argNames: ["hostId", "config"],
      );

  @override
  Future<void> crateBindingsMobileApiStopMobileClipboardDiscovery({
    required String hostId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiStopMobileClipboardDiscoveryConstMeta,
        argValues: [hostId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiStopMobileClipboardDiscoveryConstMeta =>
      const TaskConstMeta(
        debugName: "stop_mobile_clipboard_discovery",
        argNames: ["hostId"],
      );

  @override
  Future<MultiDeviceClipboardDevice>
  crateBindingsMobileApiUpsertMobileClipboardDevice({
    required String hostId,
    required UpsertMultiDeviceClipboardDeviceInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_box_autoadd_upsert_multi_device_clipboard_device_input(
            input,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_multi_device_clipboard_device,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiUpsertMobileClipboardDeviceConstMeta,
        argValues: [hostId, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateBindingsMobileApiUpsertMobileClipboardDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "upsert_mobile_clipboard_device",
        argNames: ["hostId", "input"],
      );

  @override
  Future<MultiDeviceClipboardItem>
  crateBindingsMobileApiUpsertMobileClipboardItem({
    required String hostId,
    required UpsertMultiDeviceClipboardItemInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostId, serializer);
          sse_encode_box_autoadd_upsert_multi_device_clipboard_item_input(
            input,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_multi_device_clipboard_item,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBindingsMobileApiUpsertMobileClipboardItemConstMeta,
        argValues: [hostId, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBindingsMobileApiUpsertMobileClipboardItemConstMeta =>
      const TaskConstMeta(
        debugName: "upsert_mobile_clipboard_item",
        argNames: ["hostId", "input"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  MultiDeviceClipboardDiscoveryConfig
  dco_decode_box_autoadd_multi_device_clipboard_discovery_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_multi_device_clipboard_discovery_config(raw);
  }

  @protected
  SaveMobileHomeCategoryLayoutInput
  dco_decode_box_autoadd_save_mobile_home_category_layout_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_save_mobile_home_category_layout_input(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  UpsertMultiDeviceClipboardDeviceInput
  dco_decode_box_autoadd_upsert_multi_device_clipboard_device_input(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_upsert_multi_device_clipboard_device_input(raw);
  }

  @protected
  UpsertMultiDeviceClipboardItemInput
  dco_decode_box_autoadd_upsert_multi_device_clipboard_item_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_upsert_multi_device_clipboard_item_input(raw);
  }

  @protected
  HomeLayout dco_decode_home_layout(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HomeLayout(
      workspaceKey: dco_decode_String(arr[0]),
      categories: dco_decode_list_home_layout_category(arr[1]),
    );
  }

  @protected
  HomeLayoutCategory dco_decode_home_layout_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return HomeLayoutCategory(
      id: dco_decode_String(arr[0]),
      workspaceId: dco_decode_i_64(arr[1]),
      label: dco_decode_String(arr[2]),
      icon: dco_decode_String(arr[3]),
      sortOrder: dco_decode_i_64(arr[4]),
      backgroundColor: dco_decode_opt_String(arr[5]),
      backgroundImage: dco_decode_opt_String(arr[6]),
      backgroundVideo: dco_decode_opt_String(arr[7]),
      backgroundStyle: dco_decode_opt_String(arr[8]),
      widgets: dco_decode_list_home_widget(arr[9]),
    );
  }

  @protected
  HomeWidget dco_decode_home_widget(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 24)
      throw Exception('unexpected arr length: expect 24 but see ${arr.length}');
    return HomeWidget(
      id: dco_decode_String(arr[0]),
      workspaceId: dco_decode_i_64(arr[1]),
      categoryId: dco_decode_String(arr[2]),
      label: dco_decode_String(arr[3]),
      icon: dco_decode_opt_String(arr[4]),
      action: dco_decode_opt_String(arr[5]),
      sourceType: dco_decode_String(arr[6]),
      widgetType: dco_decode_String(arr[7]),
      sizePreset: dco_decode_opt_String(arr[8]),
      widgetConfig: dco_decode_opt_String(arr[9]),
      col: dco_decode_i_64(arr[10]),
      row: dco_decode_i_64(arr[11]),
      colSpan: dco_decode_i_64(arr[12]),
      rowSpan: dco_decode_i_64(arr[13]),
      preferredCol: dco_decode_i_64(arr[14]),
      preferredRow: dco_decode_i_64(arr[15]),
      priority: dco_decode_i_64(arr[16]),
      color: dco_decode_String(arr[17]),
      backgroundImage: dco_decode_opt_String(arr[18]),
      backgroundVideo: dco_decode_opt_String(arr[19]),
      backgroundStyle: dco_decode_opt_String(arr[20]),
      hidden: dco_decode_bool(arr[21]),
      createdAt: dco_decode_String(arr[22]),
      updatedAt: dco_decode_String(arr[23]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<HomeLayoutCategory> dco_decode_list_home_layout_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_home_layout_category).toList();
  }

  @protected
  List<HomeWidget> dco_decode_list_home_widget(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_home_widget).toList();
  }

  @protected
  List<MultiDeviceClipboardDevice>
  dco_decode_list_multi_device_clipboard_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_multi_device_clipboard_device)
        .toList();
  }

  @protected
  List<MultiDeviceClipboardDeviceStatus>
  dco_decode_list_multi_device_clipboard_device_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_multi_device_clipboard_device_status)
        .toList();
  }

  @protected
  List<MultiDeviceClipboardDiscoveredDevice>
  dco_decode_list_multi_device_clipboard_discovered_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_multi_device_clipboard_discovered_device)
        .toList();
  }

  @protected
  List<MultiDeviceClipboardItem> dco_decode_list_multi_device_clipboard_item(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_multi_device_clipboard_item)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SaveMobileHomeWidgetLayoutInput>
  dco_decode_list_save_mobile_home_widget_layout_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_save_mobile_home_widget_layout_input)
        .toList();
  }

  @protected
  MultiDeviceClipboardDevice dco_decode_multi_device_clipboard_device(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return MultiDeviceClipboardDevice(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      platform: dco_decode_String(arr[2]),
      publicKey: dco_decode_opt_String(arr[3]),
      trusted: dco_decode_bool(arr[4]),
      isSelf: dco_decode_bool(arr[5]),
      lastAddress: dco_decode_opt_String(arr[6]),
      lastPort: dco_decode_opt_box_autoadd_u_32(arr[7]),
      lastSeenAt: dco_decode_opt_box_autoadd_i_64(arr[8]),
      createdAt: dco_decode_i_64(arr[9]),
      updatedAt: dco_decode_i_64(arr[10]),
    );
  }

  @protected
  MultiDeviceClipboardDeviceStatus
  dco_decode_multi_device_clipboard_device_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return MultiDeviceClipboardDeviceStatus(
      deviceId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      platform: dco_decode_String(arr[2]),
      trusted: dco_decode_bool(arr[3]),
      isSelf: dco_decode_bool(arr[4]),
      state: dco_decode_String(arr[5]),
      online: dco_decode_bool(arr[6]),
      lastAddress: dco_decode_opt_String(arr[7]),
      lastPort: dco_decode_opt_box_autoadd_u_32(arr[8]),
      lastSeenAt: dco_decode_opt_box_autoadd_i_64(arr[9]),
      secondsSinceSeen: dco_decode_opt_box_autoadd_i_64(arr[10]),
    );
  }

  @protected
  MultiDeviceClipboardDiscoveredDevice
  dco_decode_multi_device_clipboard_discovered_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MultiDeviceClipboardDiscoveredDevice(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      platform: dco_decode_String(arr[2]),
      address: dco_decode_String(arr[3]),
      port: dco_decode_u_32(arr[4]),
      serviceName: dco_decode_String(arr[5]),
      lastSeenAt: dco_decode_i_64(arr[6]),
    );
  }

  @protected
  MultiDeviceClipboardDiscoveryConfig
  dco_decode_multi_device_clipboard_discovery_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MultiDeviceClipboardDiscoveryConfig(
      deviceId: dco_decode_String(arr[0]),
      deviceName: dco_decode_String(arr[1]),
      port: dco_decode_u_32(arr[2]),
      platform: dco_decode_opt_String(arr[3]),
      preferredAddress: dco_decode_opt_String(arr[4]),
      probeLocalAddresses: dco_decode_list_String(arr[5]),
      httpProbeEnabled: dco_decode_opt_box_autoadd_bool(arr[6]),
    );
  }

  @protected
  MultiDeviceClipboardItem dco_decode_multi_device_clipboard_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return MultiDeviceClipboardItem(
      id: dco_decode_String(arr[0]),
      sourceDeviceId: dco_decode_String(arr[1]),
      sourceDeviceName: dco_decode_String(arr[2]),
      contentType: dco_decode_String(arr[3]),
      mimeType: dco_decode_opt_String(arr[4]),
      text: dco_decode_opt_String(arr[5]),
      fileName: dco_decode_opt_String(arr[6]),
      assetPath: dco_decode_opt_String(arr[7]),
      previewPath: dco_decode_opt_String(arr[8]),
      byteSize: dco_decode_i_64(arr[9]),
      contentHash: dco_decode_String(arr[10]),
      tagsJson: dco_decode_String(arr[11]),
      localOnly: dco_decode_bool(arr[12]),
      createdAt: dco_decode_i_64(arr[13]),
      updatedAt: dco_decode_i_64(arr[14]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  SaveMobileHomeCategoryLayoutInput
  dco_decode_save_mobile_home_category_layout_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SaveMobileHomeCategoryLayoutInput(
      categoryId: dco_decode_String(arr[0]),
      widgets: dco_decode_list_save_mobile_home_widget_layout_input(arr[1]),
    );
  }

  @protected
  SaveMobileHomeWidgetLayoutInput
  dco_decode_save_mobile_home_widget_layout_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return SaveMobileHomeWidgetLayoutInput(
      widgetId: dco_decode_String(arr[0]),
      col: dco_decode_i_64(arr[1]),
      row: dco_decode_i_64(arr[2]),
      colSpan: dco_decode_i_64(arr[3]),
      rowSpan: dco_decode_i_64(arr[4]),
      preferredCol: dco_decode_i_64(arr[5]),
      preferredRow: dco_decode_i_64(arr[6]),
      priority: dco_decode_i_64(arr[7]),
      hidden: dco_decode_bool(arr[8]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UpsertMultiDeviceClipboardDeviceInput
  dco_decode_upsert_multi_device_clipboard_device_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return UpsertMultiDeviceClipboardDeviceInput(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      platform: dco_decode_opt_String(arr[2]),
      publicKey: dco_decode_opt_String(arr[3]),
      trusted: dco_decode_opt_box_autoadd_bool(arr[4]),
      isSelf: dco_decode_opt_box_autoadd_bool(arr[5]),
      lastAddress: dco_decode_opt_String(arr[6]),
      lastPort: dco_decode_opt_box_autoadd_u_32(arr[7]),
      lastSeenAt: dco_decode_opt_box_autoadd_i_64(arr[8]),
    );
  }

  @protected
  UpsertMultiDeviceClipboardItemInput
  dco_decode_upsert_multi_device_clipboard_item_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return UpsertMultiDeviceClipboardItemInput(
      id: dco_decode_String(arr[0]),
      sourceDeviceId: dco_decode_String(arr[1]),
      sourceDeviceName: dco_decode_String(arr[2]),
      contentType: dco_decode_String(arr[3]),
      mimeType: dco_decode_opt_String(arr[4]),
      text: dco_decode_opt_String(arr[5]),
      fileName: dco_decode_opt_String(arr[6]),
      assetPath: dco_decode_opt_String(arr[7]),
      previewPath: dco_decode_opt_String(arr[8]),
      byteSize: dco_decode_opt_box_autoadd_i_64(arr[9]),
      contentHash: dco_decode_String(arr[10]),
      tagsJson: dco_decode_opt_String(arr[11]),
      localOnly: dco_decode_opt_box_autoadd_bool(arr[12]),
      createdAt: dco_decode_opt_box_autoadd_i_64(arr[13]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  MultiDeviceClipboardDiscoveryConfig
  sse_decode_box_autoadd_multi_device_clipboard_discovery_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_multi_device_clipboard_discovery_config(deserializer));
  }

  @protected
  SaveMobileHomeCategoryLayoutInput
  sse_decode_box_autoadd_save_mobile_home_category_layout_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_save_mobile_home_category_layout_input(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  UpsertMultiDeviceClipboardDeviceInput
  sse_decode_box_autoadd_upsert_multi_device_clipboard_device_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_upsert_multi_device_clipboard_device_input(
      deserializer,
    ));
  }

  @protected
  UpsertMultiDeviceClipboardItemInput
  sse_decode_box_autoadd_upsert_multi_device_clipboard_item_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_upsert_multi_device_clipboard_item_input(deserializer));
  }

  @protected
  HomeLayout sse_decode_home_layout(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_workspaceKey = sse_decode_String(deserializer);
    var var_categories = sse_decode_list_home_layout_category(deserializer);
    return HomeLayout(
      workspaceKey: var_workspaceKey,
      categories: var_categories,
    );
  }

  @protected
  HomeLayoutCategory sse_decode_home_layout_category(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_workspaceId = sse_decode_i_64(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_icon = sse_decode_String(deserializer);
    var var_sortOrder = sse_decode_i_64(deserializer);
    var var_backgroundColor = sse_decode_opt_String(deserializer);
    var var_backgroundImage = sse_decode_opt_String(deserializer);
    var var_backgroundVideo = sse_decode_opt_String(deserializer);
    var var_backgroundStyle = sse_decode_opt_String(deserializer);
    var var_widgets = sse_decode_list_home_widget(deserializer);
    return HomeLayoutCategory(
      id: var_id,
      workspaceId: var_workspaceId,
      label: var_label,
      icon: var_icon,
      sortOrder: var_sortOrder,
      backgroundColor: var_backgroundColor,
      backgroundImage: var_backgroundImage,
      backgroundVideo: var_backgroundVideo,
      backgroundStyle: var_backgroundStyle,
      widgets: var_widgets,
    );
  }

  @protected
  HomeWidget sse_decode_home_widget(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_workspaceId = sse_decode_i_64(deserializer);
    var var_categoryId = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_icon = sse_decode_opt_String(deserializer);
    var var_action = sse_decode_opt_String(deserializer);
    var var_sourceType = sse_decode_String(deserializer);
    var var_widgetType = sse_decode_String(deserializer);
    var var_sizePreset = sse_decode_opt_String(deserializer);
    var var_widgetConfig = sse_decode_opt_String(deserializer);
    var var_col = sse_decode_i_64(deserializer);
    var var_row = sse_decode_i_64(deserializer);
    var var_colSpan = sse_decode_i_64(deserializer);
    var var_rowSpan = sse_decode_i_64(deserializer);
    var var_preferredCol = sse_decode_i_64(deserializer);
    var var_preferredRow = sse_decode_i_64(deserializer);
    var var_priority = sse_decode_i_64(deserializer);
    var var_color = sse_decode_String(deserializer);
    var var_backgroundImage = sse_decode_opt_String(deserializer);
    var var_backgroundVideo = sse_decode_opt_String(deserializer);
    var var_backgroundStyle = sse_decode_opt_String(deserializer);
    var var_hidden = sse_decode_bool(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return HomeWidget(
      id: var_id,
      workspaceId: var_workspaceId,
      categoryId: var_categoryId,
      label: var_label,
      icon: var_icon,
      action: var_action,
      sourceType: var_sourceType,
      widgetType: var_widgetType,
      sizePreset: var_sizePreset,
      widgetConfig: var_widgetConfig,
      col: var_col,
      row: var_row,
      colSpan: var_colSpan,
      rowSpan: var_rowSpan,
      preferredCol: var_preferredCol,
      preferredRow: var_preferredRow,
      priority: var_priority,
      color: var_color,
      backgroundImage: var_backgroundImage,
      backgroundVideo: var_backgroundVideo,
      backgroundStyle: var_backgroundStyle,
      hidden: var_hidden,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<HomeLayoutCategory> sse_decode_list_home_layout_category(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HomeLayoutCategory>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_home_layout_category(deserializer));
    }
    return ans_;
  }

  @protected
  List<HomeWidget> sse_decode_list_home_widget(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HomeWidget>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_home_widget(deserializer));
    }
    return ans_;
  }

  @protected
  List<MultiDeviceClipboardDevice>
  sse_decode_list_multi_device_clipboard_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MultiDeviceClipboardDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_multi_device_clipboard_device(deserializer));
    }
    return ans_;
  }

  @protected
  List<MultiDeviceClipboardDeviceStatus>
  sse_decode_list_multi_device_clipboard_device_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MultiDeviceClipboardDeviceStatus>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_multi_device_clipboard_device_status(deserializer));
    }
    return ans_;
  }

  @protected
  List<MultiDeviceClipboardDiscoveredDevice>
  sse_decode_list_multi_device_clipboard_discovered_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MultiDeviceClipboardDiscoveredDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_multi_device_clipboard_discovered_device(deserializer),
      );
    }
    return ans_;
  }

  @protected
  List<MultiDeviceClipboardItem> sse_decode_list_multi_device_clipboard_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MultiDeviceClipboardItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_multi_device_clipboard_item(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SaveMobileHomeWidgetLayoutInput>
  sse_decode_list_save_mobile_home_widget_layout_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SaveMobileHomeWidgetLayoutInput>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_save_mobile_home_widget_layout_input(deserializer));
    }
    return ans_;
  }

  @protected
  MultiDeviceClipboardDevice sse_decode_multi_device_clipboard_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_platform = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_opt_String(deserializer);
    var var_trusted = sse_decode_bool(deserializer);
    var var_isSelf = sse_decode_bool(deserializer);
    var var_lastAddress = sse_decode_opt_String(deserializer);
    var var_lastPort = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_lastSeenAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return MultiDeviceClipboardDevice(
      id: var_id,
      name: var_name,
      platform: var_platform,
      publicKey: var_publicKey,
      trusted: var_trusted,
      isSelf: var_isSelf,
      lastAddress: var_lastAddress,
      lastPort: var_lastPort,
      lastSeenAt: var_lastSeenAt,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  MultiDeviceClipboardDeviceStatus
  sse_decode_multi_device_clipboard_device_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_platform = sse_decode_String(deserializer);
    var var_trusted = sse_decode_bool(deserializer);
    var var_isSelf = sse_decode_bool(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_online = sse_decode_bool(deserializer);
    var var_lastAddress = sse_decode_opt_String(deserializer);
    var var_lastPort = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_lastSeenAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_secondsSinceSeen = sse_decode_opt_box_autoadd_i_64(deserializer);
    return MultiDeviceClipboardDeviceStatus(
      deviceId: var_deviceId,
      name: var_name,
      platform: var_platform,
      trusted: var_trusted,
      isSelf: var_isSelf,
      state: var_state,
      online: var_online,
      lastAddress: var_lastAddress,
      lastPort: var_lastPort,
      lastSeenAt: var_lastSeenAt,
      secondsSinceSeen: var_secondsSinceSeen,
    );
  }

  @protected
  MultiDeviceClipboardDiscoveredDevice
  sse_decode_multi_device_clipboard_discovered_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_platform = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_port = sse_decode_u_32(deserializer);
    var var_serviceName = sse_decode_String(deserializer);
    var var_lastSeenAt = sse_decode_i_64(deserializer);
    return MultiDeviceClipboardDiscoveredDevice(
      id: var_id,
      name: var_name,
      platform: var_platform,
      address: var_address,
      port: var_port,
      serviceName: var_serviceName,
      lastSeenAt: var_lastSeenAt,
    );
  }

  @protected
  MultiDeviceClipboardDiscoveryConfig
  sse_decode_multi_device_clipboard_discovery_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_port = sse_decode_u_32(deserializer);
    var var_platform = sse_decode_opt_String(deserializer);
    var var_preferredAddress = sse_decode_opt_String(deserializer);
    var var_probeLocalAddresses = sse_decode_list_String(deserializer);
    var var_httpProbeEnabled = sse_decode_opt_box_autoadd_bool(deserializer);
    return MultiDeviceClipboardDiscoveryConfig(
      deviceId: var_deviceId,
      deviceName: var_deviceName,
      port: var_port,
      platform: var_platform,
      preferredAddress: var_preferredAddress,
      probeLocalAddresses: var_probeLocalAddresses,
      httpProbeEnabled: var_httpProbeEnabled,
    );
  }

  @protected
  MultiDeviceClipboardItem sse_decode_multi_device_clipboard_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sourceDeviceId = sse_decode_String(deserializer);
    var var_sourceDeviceName = sse_decode_String(deserializer);
    var var_contentType = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_opt_String(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_fileName = sse_decode_opt_String(deserializer);
    var var_assetPath = sse_decode_opt_String(deserializer);
    var var_previewPath = sse_decode_opt_String(deserializer);
    var var_byteSize = sse_decode_i_64(deserializer);
    var var_contentHash = sse_decode_String(deserializer);
    var var_tagsJson = sse_decode_String(deserializer);
    var var_localOnly = sse_decode_bool(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return MultiDeviceClipboardItem(
      id: var_id,
      sourceDeviceId: var_sourceDeviceId,
      sourceDeviceName: var_sourceDeviceName,
      contentType: var_contentType,
      mimeType: var_mimeType,
      text: var_text,
      fileName: var_fileName,
      assetPath: var_assetPath,
      previewPath: var_previewPath,
      byteSize: var_byteSize,
      contentHash: var_contentHash,
      tagsJson: var_tagsJson,
      localOnly: var_localOnly,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SaveMobileHomeCategoryLayoutInput
  sse_decode_save_mobile_home_category_layout_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_categoryId = sse_decode_String(deserializer);
    var var_widgets = sse_decode_list_save_mobile_home_widget_layout_input(
      deserializer,
    );
    return SaveMobileHomeCategoryLayoutInput(
      categoryId: var_categoryId,
      widgets: var_widgets,
    );
  }

  @protected
  SaveMobileHomeWidgetLayoutInput
  sse_decode_save_mobile_home_widget_layout_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_widgetId = sse_decode_String(deserializer);
    var var_col = sse_decode_i_64(deserializer);
    var var_row = sse_decode_i_64(deserializer);
    var var_colSpan = sse_decode_i_64(deserializer);
    var var_rowSpan = sse_decode_i_64(deserializer);
    var var_preferredCol = sse_decode_i_64(deserializer);
    var var_preferredRow = sse_decode_i_64(deserializer);
    var var_priority = sse_decode_i_64(deserializer);
    var var_hidden = sse_decode_bool(deserializer);
    return SaveMobileHomeWidgetLayoutInput(
      widgetId: var_widgetId,
      col: var_col,
      row: var_row,
      colSpan: var_colSpan,
      rowSpan: var_rowSpan,
      preferredCol: var_preferredCol,
      preferredRow: var_preferredRow,
      priority: var_priority,
      hidden: var_hidden,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UpsertMultiDeviceClipboardDeviceInput
  sse_decode_upsert_multi_device_clipboard_device_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_platform = sse_decode_opt_String(deserializer);
    var var_publicKey = sse_decode_opt_String(deserializer);
    var var_trusted = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_isSelf = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_lastAddress = sse_decode_opt_String(deserializer);
    var var_lastPort = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_lastSeenAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    return UpsertMultiDeviceClipboardDeviceInput(
      id: var_id,
      name: var_name,
      platform: var_platform,
      publicKey: var_publicKey,
      trusted: var_trusted,
      isSelf: var_isSelf,
      lastAddress: var_lastAddress,
      lastPort: var_lastPort,
      lastSeenAt: var_lastSeenAt,
    );
  }

  @protected
  UpsertMultiDeviceClipboardItemInput
  sse_decode_upsert_multi_device_clipboard_item_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sourceDeviceId = sse_decode_String(deserializer);
    var var_sourceDeviceName = sse_decode_String(deserializer);
    var var_contentType = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_opt_String(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_fileName = sse_decode_opt_String(deserializer);
    var var_assetPath = sse_decode_opt_String(deserializer);
    var var_previewPath = sse_decode_opt_String(deserializer);
    var var_byteSize = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_contentHash = sse_decode_String(deserializer);
    var var_tagsJson = sse_decode_opt_String(deserializer);
    var var_localOnly = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_createdAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    return UpsertMultiDeviceClipboardItemInput(
      id: var_id,
      sourceDeviceId: var_sourceDeviceId,
      sourceDeviceName: var_sourceDeviceName,
      contentType: var_contentType,
      mimeType: var_mimeType,
      text: var_text,
      fileName: var_fileName,
      assetPath: var_assetPath,
      previewPath: var_previewPath,
      byteSize: var_byteSize,
      contentHash: var_contentHash,
      tagsJson: var_tagsJson,
      localOnly: var_localOnly,
      createdAt: var_createdAt,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_multi_device_clipboard_discovery_config(
    MultiDeviceClipboardDiscoveryConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_multi_device_clipboard_discovery_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_save_mobile_home_category_layout_input(
    SaveMobileHomeCategoryLayoutInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_save_mobile_home_category_layout_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_upsert_multi_device_clipboard_device_input(
    UpsertMultiDeviceClipboardDeviceInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_upsert_multi_device_clipboard_device_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_upsert_multi_device_clipboard_item_input(
    UpsertMultiDeviceClipboardItemInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_upsert_multi_device_clipboard_item_input(self, serializer);
  }

  @protected
  void sse_encode_home_layout(HomeLayout self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.workspaceKey, serializer);
    sse_encode_list_home_layout_category(self.categories, serializer);
  }

  @protected
  void sse_encode_home_layout_category(
    HomeLayoutCategory self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_64(self.workspaceId, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.icon, serializer);
    sse_encode_i_64(self.sortOrder, serializer);
    sse_encode_opt_String(self.backgroundColor, serializer);
    sse_encode_opt_String(self.backgroundImage, serializer);
    sse_encode_opt_String(self.backgroundVideo, serializer);
    sse_encode_opt_String(self.backgroundStyle, serializer);
    sse_encode_list_home_widget(self.widgets, serializer);
  }

  @protected
  void sse_encode_home_widget(HomeWidget self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_64(self.workspaceId, serializer);
    sse_encode_String(self.categoryId, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_opt_String(self.icon, serializer);
    sse_encode_opt_String(self.action, serializer);
    sse_encode_String(self.sourceType, serializer);
    sse_encode_String(self.widgetType, serializer);
    sse_encode_opt_String(self.sizePreset, serializer);
    sse_encode_opt_String(self.widgetConfig, serializer);
    sse_encode_i_64(self.col, serializer);
    sse_encode_i_64(self.row, serializer);
    sse_encode_i_64(self.colSpan, serializer);
    sse_encode_i_64(self.rowSpan, serializer);
    sse_encode_i_64(self.preferredCol, serializer);
    sse_encode_i_64(self.preferredRow, serializer);
    sse_encode_i_64(self.priority, serializer);
    sse_encode_String(self.color, serializer);
    sse_encode_opt_String(self.backgroundImage, serializer);
    sse_encode_opt_String(self.backgroundVideo, serializer);
    sse_encode_opt_String(self.backgroundStyle, serializer);
    sse_encode_bool(self.hidden, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_home_layout_category(
    List<HomeLayoutCategory> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_home_layout_category(item, serializer);
    }
  }

  @protected
  void sse_encode_list_home_widget(
    List<HomeWidget> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_home_widget(item, serializer);
    }
  }

  @protected
  void sse_encode_list_multi_device_clipboard_device(
    List<MultiDeviceClipboardDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_multi_device_clipboard_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_multi_device_clipboard_device_status(
    List<MultiDeviceClipboardDeviceStatus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_multi_device_clipboard_device_status(item, serializer);
    }
  }

  @protected
  void sse_encode_list_multi_device_clipboard_discovered_device(
    List<MultiDeviceClipboardDiscoveredDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_multi_device_clipboard_discovered_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_multi_device_clipboard_item(
    List<MultiDeviceClipboardItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_multi_device_clipboard_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_save_mobile_home_widget_layout_input(
    List<SaveMobileHomeWidgetLayoutInput> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_save_mobile_home_widget_layout_input(item, serializer);
    }
  }

  @protected
  void sse_encode_multi_device_clipboard_device(
    MultiDeviceClipboardDevice self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.platform, serializer);
    sse_encode_opt_String(self.publicKey, serializer);
    sse_encode_bool(self.trusted, serializer);
    sse_encode_bool(self.isSelf, serializer);
    sse_encode_opt_String(self.lastAddress, serializer);
    sse_encode_opt_box_autoadd_u_32(self.lastPort, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastSeenAt, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_multi_device_clipboard_device_status(
    MultiDeviceClipboardDeviceStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.platform, serializer);
    sse_encode_bool(self.trusted, serializer);
    sse_encode_bool(self.isSelf, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_bool(self.online, serializer);
    sse_encode_opt_String(self.lastAddress, serializer);
    sse_encode_opt_box_autoadd_u_32(self.lastPort, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastSeenAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.secondsSinceSeen, serializer);
  }

  @protected
  void sse_encode_multi_device_clipboard_discovered_device(
    MultiDeviceClipboardDiscoveredDevice self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.platform, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_u_32(self.port, serializer);
    sse_encode_String(self.serviceName, serializer);
    sse_encode_i_64(self.lastSeenAt, serializer);
  }

  @protected
  void sse_encode_multi_device_clipboard_discovery_config(
    MultiDeviceClipboardDiscoveryConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_u_32(self.port, serializer);
    sse_encode_opt_String(self.platform, serializer);
    sse_encode_opt_String(self.preferredAddress, serializer);
    sse_encode_list_String(self.probeLocalAddresses, serializer);
    sse_encode_opt_box_autoadd_bool(self.httpProbeEnabled, serializer);
  }

  @protected
  void sse_encode_multi_device_clipboard_item(
    MultiDeviceClipboardItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.sourceDeviceId, serializer);
    sse_encode_String(self.sourceDeviceName, serializer);
    sse_encode_String(self.contentType, serializer);
    sse_encode_opt_String(self.mimeType, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.fileName, serializer);
    sse_encode_opt_String(self.assetPath, serializer);
    sse_encode_opt_String(self.previewPath, serializer);
    sse_encode_i_64(self.byteSize, serializer);
    sse_encode_String(self.contentHash, serializer);
    sse_encode_String(self.tagsJson, serializer);
    sse_encode_bool(self.localOnly, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_save_mobile_home_category_layout_input(
    SaveMobileHomeCategoryLayoutInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.categoryId, serializer);
    sse_encode_list_save_mobile_home_widget_layout_input(
      self.widgets,
      serializer,
    );
  }

  @protected
  void sse_encode_save_mobile_home_widget_layout_input(
    SaveMobileHomeWidgetLayoutInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.widgetId, serializer);
    sse_encode_i_64(self.col, serializer);
    sse_encode_i_64(self.row, serializer);
    sse_encode_i_64(self.colSpan, serializer);
    sse_encode_i_64(self.rowSpan, serializer);
    sse_encode_i_64(self.preferredCol, serializer);
    sse_encode_i_64(self.preferredRow, serializer);
    sse_encode_i_64(self.priority, serializer);
    sse_encode_bool(self.hidden, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_upsert_multi_device_clipboard_device_input(
    UpsertMultiDeviceClipboardDeviceInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.platform, serializer);
    sse_encode_opt_String(self.publicKey, serializer);
    sse_encode_opt_box_autoadd_bool(self.trusted, serializer);
    sse_encode_opt_box_autoadd_bool(self.isSelf, serializer);
    sse_encode_opt_String(self.lastAddress, serializer);
    sse_encode_opt_box_autoadd_u_32(self.lastPort, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastSeenAt, serializer);
  }

  @protected
  void sse_encode_upsert_multi_device_clipboard_item_input(
    UpsertMultiDeviceClipboardItemInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.sourceDeviceId, serializer);
    sse_encode_String(self.sourceDeviceName, serializer);
    sse_encode_String(self.contentType, serializer);
    sse_encode_opt_String(self.mimeType, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.fileName, serializer);
    sse_encode_opt_String(self.assetPath, serializer);
    sse_encode_opt_String(self.previewPath, serializer);
    sse_encode_opt_box_autoadd_i_64(self.byteSize, serializer);
    sse_encode_String(self.contentHash, serializer);
    sse_encode_opt_String(self.tagsJson, serializer);
    sse_encode_opt_box_autoadd_bool(self.localOnly, serializer);
    sse_encode_opt_box_autoadd_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
