// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'bindings/mobile_api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'models/home_layout.dart';
import 'models/multi_device_clipboard.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MultiDeviceClipboardDiscoveryConfig
  dco_decode_box_autoadd_multi_device_clipboard_discovery_config(dynamic raw);

  @protected
  SaveMobileHomeCategoryLayoutInput
  dco_decode_box_autoadd_save_mobile_home_category_layout_input(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  UpsertMultiDeviceClipboardDeviceInput
  dco_decode_box_autoadd_upsert_multi_device_clipboard_device_input(
    dynamic raw,
  );

  @protected
  UpsertMultiDeviceClipboardItemInput
  dco_decode_box_autoadd_upsert_multi_device_clipboard_item_input(dynamic raw);

  @protected
  HomeLayout dco_decode_home_layout(dynamic raw);

  @protected
  HomeLayoutCategory dco_decode_home_layout_category(dynamic raw);

  @protected
  HomeWidget dco_decode_home_widget(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<HomeLayoutCategory> dco_decode_list_home_layout_category(dynamic raw);

  @protected
  List<HomeWidget> dco_decode_list_home_widget(dynamic raw);

  @protected
  List<MultiDeviceClipboardDevice>
  dco_decode_list_multi_device_clipboard_device(dynamic raw);

  @protected
  List<MultiDeviceClipboardDeviceStatus>
  dco_decode_list_multi_device_clipboard_device_status(dynamic raw);

  @protected
  List<MultiDeviceClipboardDiscoveredDevice>
  dco_decode_list_multi_device_clipboard_discovered_device(dynamic raw);

  @protected
  List<MultiDeviceClipboardItem> dco_decode_list_multi_device_clipboard_item(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SaveMobileHomeWidgetLayoutInput>
  dco_decode_list_save_mobile_home_widget_layout_input(dynamic raw);

  @protected
  MultiDeviceClipboardDevice dco_decode_multi_device_clipboard_device(
    dynamic raw,
  );

  @protected
  MultiDeviceClipboardDeviceStatus
  dco_decode_multi_device_clipboard_device_status(dynamic raw);

  @protected
  MultiDeviceClipboardDiscoveredDevice
  dco_decode_multi_device_clipboard_discovered_device(dynamic raw);

  @protected
  MultiDeviceClipboardDiscoveryConfig
  dco_decode_multi_device_clipboard_discovery_config(dynamic raw);

  @protected
  MultiDeviceClipboardItem dco_decode_multi_device_clipboard_item(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  SaveMobileHomeCategoryLayoutInput
  dco_decode_save_mobile_home_category_layout_input(dynamic raw);

  @protected
  SaveMobileHomeWidgetLayoutInput
  dco_decode_save_mobile_home_widget_layout_input(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpsertMultiDeviceClipboardDeviceInput
  dco_decode_upsert_multi_device_clipboard_device_input(dynamic raw);

  @protected
  UpsertMultiDeviceClipboardItemInput
  dco_decode_upsert_multi_device_clipboard_item_input(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MultiDeviceClipboardDiscoveryConfig
  sse_decode_box_autoadd_multi_device_clipboard_discovery_config(
    SseDeserializer deserializer,
  );

  @protected
  SaveMobileHomeCategoryLayoutInput
  sse_decode_box_autoadd_save_mobile_home_category_layout_input(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UpsertMultiDeviceClipboardDeviceInput
  sse_decode_box_autoadd_upsert_multi_device_clipboard_device_input(
    SseDeserializer deserializer,
  );

  @protected
  UpsertMultiDeviceClipboardItemInput
  sse_decode_box_autoadd_upsert_multi_device_clipboard_item_input(
    SseDeserializer deserializer,
  );

  @protected
  HomeLayout sse_decode_home_layout(SseDeserializer deserializer);

  @protected
  HomeLayoutCategory sse_decode_home_layout_category(
    SseDeserializer deserializer,
  );

  @protected
  HomeWidget sse_decode_home_widget(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<HomeLayoutCategory> sse_decode_list_home_layout_category(
    SseDeserializer deserializer,
  );

  @protected
  List<HomeWidget> sse_decode_list_home_widget(SseDeserializer deserializer);

  @protected
  List<MultiDeviceClipboardDevice>
  sse_decode_list_multi_device_clipboard_device(SseDeserializer deserializer);

  @protected
  List<MultiDeviceClipboardDeviceStatus>
  sse_decode_list_multi_device_clipboard_device_status(
    SseDeserializer deserializer,
  );

  @protected
  List<MultiDeviceClipboardDiscoveredDevice>
  sse_decode_list_multi_device_clipboard_discovered_device(
    SseDeserializer deserializer,
  );

  @protected
  List<MultiDeviceClipboardItem> sse_decode_list_multi_device_clipboard_item(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SaveMobileHomeWidgetLayoutInput>
  sse_decode_list_save_mobile_home_widget_layout_input(
    SseDeserializer deserializer,
  );

  @protected
  MultiDeviceClipboardDevice sse_decode_multi_device_clipboard_device(
    SseDeserializer deserializer,
  );

  @protected
  MultiDeviceClipboardDeviceStatus
  sse_decode_multi_device_clipboard_device_status(SseDeserializer deserializer);

  @protected
  MultiDeviceClipboardDiscoveredDevice
  sse_decode_multi_device_clipboard_discovered_device(
    SseDeserializer deserializer,
  );

  @protected
  MultiDeviceClipboardDiscoveryConfig
  sse_decode_multi_device_clipboard_discovery_config(
    SseDeserializer deserializer,
  );

  @protected
  MultiDeviceClipboardItem sse_decode_multi_device_clipboard_item(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  SaveMobileHomeCategoryLayoutInput
  sse_decode_save_mobile_home_category_layout_input(
    SseDeserializer deserializer,
  );

  @protected
  SaveMobileHomeWidgetLayoutInput
  sse_decode_save_mobile_home_widget_layout_input(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpsertMultiDeviceClipboardDeviceInput
  sse_decode_upsert_multi_device_clipboard_device_input(
    SseDeserializer deserializer,
  );

  @protected
  UpsertMultiDeviceClipboardItemInput
  sse_decode_upsert_multi_device_clipboard_item_input(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_multi_device_clipboard_discovery_config(
    MultiDeviceClipboardDiscoveryConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_save_mobile_home_category_layout_input(
    SaveMobileHomeCategoryLayoutInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_upsert_multi_device_clipboard_device_input(
    UpsertMultiDeviceClipboardDeviceInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_upsert_multi_device_clipboard_item_input(
    UpsertMultiDeviceClipboardItemInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_home_layout(HomeLayout self, SseSerializer serializer);

  @protected
  void sse_encode_home_layout_category(
    HomeLayoutCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_home_widget(HomeWidget self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_home_layout_category(
    List<HomeLayoutCategory> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_home_widget(
    List<HomeWidget> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_multi_device_clipboard_device(
    List<MultiDeviceClipboardDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_multi_device_clipboard_device_status(
    List<MultiDeviceClipboardDeviceStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_multi_device_clipboard_discovered_device(
    List<MultiDeviceClipboardDiscoveredDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_multi_device_clipboard_item(
    List<MultiDeviceClipboardItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_save_mobile_home_widget_layout_input(
    List<SaveMobileHomeWidgetLayoutInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_multi_device_clipboard_device(
    MultiDeviceClipboardDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_multi_device_clipboard_device_status(
    MultiDeviceClipboardDeviceStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_multi_device_clipboard_discovered_device(
    MultiDeviceClipboardDiscoveredDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_multi_device_clipboard_discovery_config(
    MultiDeviceClipboardDiscoveryConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_multi_device_clipboard_item(
    MultiDeviceClipboardItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_save_mobile_home_category_layout_input(
    SaveMobileHomeCategoryLayoutInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_save_mobile_home_widget_layout_input(
    SaveMobileHomeWidgetLayoutInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_upsert_multi_device_clipboard_device_input(
    UpsertMultiDeviceClipboardDeviceInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_upsert_multi_device_clipboard_item_input(
    UpsertMultiDeviceClipboardItemInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
