/* auto-generated by NAPI-RS */

export class JsDatabase {
  constructor(path: string);
  static newInMemory(): Database;

  // User methods
  createUser(name: string, email?: string, avatar?: string): Promise<User>;
  getUser(id: number): Promise<User>;
  getUserByEmail(email: string): Promise<User>;
  listUsers(offset: number, limit: number): Promise<Array<User>>;
  updateUser(id: number, name?: string, email?: string, avatar?: string): Promise<User>;
  deleteUser(id: number): Promise<void>;
  countUsers(): Promise<number>;

  // Project methods
  createProject(name: string, ownerId: number, description?: string): Promise<Project>;
  getProject(id: number): Promise<Project>;
  listProjects(offset: number, limit: number): Promise<Array<Project>>;
  listProjectsByOwner(ownerId: number, offset?: number, limit?: number): Promise<Array<Project>>;
  updateProject(id: number, name?: string, description?: string, status?: string): Promise<Project>;
  deleteProject(id: number): Promise<void>;

  // Setting methods
  getSetting(key: string): Promise<Setting>;
  getSettingValue(key: string): Promise<string>;
  listSettings(): Promise<Array<Setting>>;
  upsertSetting(key: string, value: string, description?: string): Promise<Setting>;
  deleteSetting(key: string): Promise<void>;
}

export interface User {
  id: number;
  name: string;
  email?: string;
  avatar?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Project {
  id: number;
  name: string;
  description?: string;
  ownerId: number;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface Setting {
  key: string;
  value: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}
