/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface HomeWorkspace {
  id: number
  key: string
  name: string
  isDefault: boolean
  createdAt: string
  updatedAt: string
}
export interface HomeCategory {
  id: string
  workspaceId: number
  label: string
  icon: string
  sortOrder: number
  backgroundColor?: string
  backgroundImage?: string
  backgroundVideo?: string
  backgroundStyle?: string
  createdAt: string
  updatedAt: string
}
export interface HomeWidget {
  id: string
  workspaceId: number
  categoryId: string
  label: string
  icon?: string
  action?: string
  sourceType: string
  widgetType: string
  sizePreset?: string
  widgetConfig?: string
  col: number
  row: number
  colSpan: number
  rowSpan: number
  preferredCol: number
  preferredRow: number
  priority: number
  color: string
  backgroundImage?: string
  backgroundVideo?: string
  backgroundStyle?: string
  hidden: boolean
  createdAt: string
  updatedAt: string
}
export interface HomeLayoutCategory {
  id: string
  workspaceId: number
  label: string
  icon: string
  sortOrder: number
  backgroundColor?: string
  backgroundImage?: string
  backgroundVideo?: string
  backgroundStyle?: string
  widgets: Array<HomeWidget>
}
export interface HomeLayout {
  workspaceKey: string
  categories: Array<HomeLayoutCategory>
}
export interface CreateHomeCategoryInput {
  id: string
  workspaceKey: string
  label: string
  icon: string
  sortOrder: number
  backgroundColor?: string
  backgroundImage?: string
  backgroundVideo?: string
  backgroundStyle?: string
}
export interface UpdateHomeCategoryInput {
  label?: string
  icon?: string
  sortOrder?: number
  backgroundColor?: string
  backgroundImage?: string
  backgroundVideo?: string
  backgroundStyle?: string
}
export interface CreateHomeWidgetInput {
  id: string
  workspaceKey: string
  categoryId: string
  label: string
  icon?: string
  action?: string
  sourceType: string
  widgetType: string
  sizePreset?: string
  widgetConfig?: string
  col: number
  row: number
  colSpan: number
  rowSpan: number
  preferredCol: number
  preferredRow: number
  priority: number
  color: string
  backgroundImage?: string
  backgroundVideo?: string
  backgroundStyle?: string
  hidden: boolean
}
export interface UpdateHomeWidgetInput {
  categoryId?: string
  label?: string
  icon?: string
  action?: string
  sourceType?: string
  widgetType?: string
  sizePreset?: string
  widgetConfig?: string
  col?: number
  row?: number
  colSpan?: number
  rowSpan?: number
  preferredCol?: number
  preferredRow?: number
  priority?: number
  color?: string
  backgroundImage?: string
  backgroundVideo?: string
  backgroundStyle?: string
  hidden?: boolean
}
export interface ImportHomeWidgetInput {
  id: string
  label: string
  icon?: string
  action?: string
  sourceType?: string
  widgetType?: string
  sizePreset?: string
  widgetConfig?: string
  col: number
  row: number
  colSpan: number
  rowSpan: number
  preferredCol: number
  preferredRow: number
  priority: number
  color: string
  backgroundImage?: string
  backgroundVideo?: string
  backgroundStyle?: string
  hidden: boolean
}
export interface ImportHomeCategoryInput {
  id: string
  label: string
  icon: string
  sortOrder: number
  backgroundColor?: string
  backgroundImage?: string
  backgroundVideo?: string
  backgroundStyle?: string
  widgets: Array<ImportHomeWidgetInput>
}
export interface ImportHomeLayoutInput {
  categories: Array<ImportHomeCategoryInput>
}
/** 项目模型 */
export interface Project {
  id: number
  name: string
  description?: string
  ownerId: number
  status: string
  createdAt: string
  updatedAt: string
}
/** 设置模型 */
export interface Setting {
  id: number
  key: string
  value: string
  description?: string
  createdAt: string
  updatedAt: string
}
export interface TodoList {
  id: string
  workspaceId: number
  name: string
  icon: string
  themeColor: string
  sortOrder: number
  incompleteCount: number
  createdAt: string
  updatedAt: string
}
export interface CreateTodoListInput {
  id: string
  name: string
  icon?: string
  themeColor?: string
  sortOrder: number
}
export interface UpdateTodoListInput {
  name?: string
  icon?: string
  themeColor?: string
  sortOrder?: number
}
export interface Todo {
  id: string
  listId: string
  title: string
  note: string
  isCompleted: boolean
  isImportant: boolean
  isMyDay: boolean
  myDayDate?: string
  dueDate?: string
  repeatRule?: string
  sortOrder: number
  completedAt?: string
  createdAt: string
  updatedAt: string
  steps: Array<TodoStep>
  reminders: Array<TodoReminder>
}
export interface CreateTodoInput {
  id: string
  listId: string
  title: string
  note?: string
  isImportant?: boolean
  isMyDay?: boolean
  dueDate?: string
  repeatRule?: string
  sortOrder?: number
}
export interface UpdateTodoInput {
  listId?: string
  title?: string
  note?: string
  isImportant?: boolean
  isMyDay?: boolean
  myDayDate?: string
  dueDate?: string
  repeatRule?: string
  sortOrder?: number
}
export interface CompleteTodoResult {
  completedTodo: Todo
  nextTodo?: Todo
}
export interface TodoStep {
  id: string
  todoId: string
  title: string
  isCompleted: boolean
  sortOrder: number
  createdAt: string
  updatedAt: string
}
export interface CreateTodoStepInput {
  id: string
  todoId: string
  title: string
  sortOrder?: number
}
export interface UpdateTodoStepInput {
  title?: string
  isCompleted?: boolean
  sortOrder?: number
}
export interface TodoReminder {
  id: string
  todoId: string
  remindAt: string
  isSent: boolean
  createdAt: string
}
export interface CreateTodoReminderInput {
  id: string
  todoId: string
  remindAt: string
}
/** 用户模型 */
export interface User {
  id: number
  name: string
  email?: string
  avatar?: string
  createdAt: string
  updatedAt: string
}
export interface TerminalProfile {
  id: string
  label: string
  command: string
  args: Array<string>
  isDefault: boolean
}
export interface TerminalSessionDescriptor {
  sessionId: string
  profileId: string
  profileLabel: string
  cwd?: string
  attachedTarget: string
  status: string
  processId?: number
}
export interface CreateTerminalSessionInput {
  profileId?: string
  profileLabel?: string
  command?: string
  cwd?: string
  args?: Array<string>
  env?: Record<string, string>
  rows: number
  cols: number
  pixelWidth: number
  pixelHeight: number
  attachedTarget?: string
}
export interface ResizeTerminalSessionInput {
  sessionId: string
  rows: number
  cols: number
  pixelWidth: number
  pixelHeight: number
}
export interface TerminalEventEnvelope {
  eventType: string
  sessionId: string
  data?: string
  status?: string
  attachedTarget?: string
  message?: string
  processId?: number
  exitCode?: number
  signal?: string
}
export declare class JsTerminalHost {
  constructor()
  listProfiles(): Array<TerminalProfile>
  listSessions(): Array<TerminalSessionDescriptor>
  createSession(input: CreateTerminalSessionInput): TerminalSessionDescriptor
  write(sessionId: string, data: string): void
  resizeSession(input: ResizeTerminalSessionInput): void
  killSession(sessionId: string): void
  attachSession(sessionId: string, target: string): void
  closeDetachedView(sessionId: string, target: string): void
  registerEventSink(callback: (...args: any[]) => any): void
}
/** Node.js 数据库包装器 */
export declare class JsDatabase {
  /** 创建新的数据库实例 */
  constructor(path: string)
  /** 创建内存数据库（用于测试） */
  static newInMemory(): JsDatabase
  /** 创建用户 */
  createUser(name: string, email?: string | undefined | null, avatar?: string | undefined | null): Promise<User>
  /** 根据 ID 获取用户 */
  getUser(id: number): Promise<User>
  /** 根据邮箱获取用户 */
  getUserByEmail(email: string): Promise<User>
  /** 列出用户 */
  listUsers(offset: number, limit: number): Promise<Array<User>>
  /** 更新用户 */
  updateUser(id: number, name?: string | undefined | null, email?: string | undefined | null, avatar?: string | undefined | null): Promise<User>
  /** 删除用户 */
  deleteUser(id: number): Promise<void>
  /** 统计用户总数 */
  countUsers(): Promise<number>
  /** 创建项目 */
  createProject(name: string, description: string | undefined | null, ownerId: number): Promise<Project>
  /** 根据 ID 获取项目 */
  getProject(id: number): Promise<Project>
  /** 列出项目 */
  listProjects(offset: number, limit: number): Promise<Array<Project>>
  /** 根据所有者列出项目 */
  listProjectsByOwner(ownerId: number, offset: number, limit: number): Promise<Array<Project>>
  /** 更新项目 */
  updateProject(id: number, name?: string | undefined | null, description?: string | undefined | null, status?: string | undefined | null): Promise<Project>
  /** 删除项目 */
  deleteProject(id: number): Promise<void>
  /** 获取设置 */
  getSetting(key: string): Promise<Setting>
  /** 获取设置值 */
  getSettingValue(key: string): Promise<string>
  /** 列出所有设置 */
  listSettings(): Promise<Array<Setting>>
  /** 创建或更新设置 */
  upsertSetting(key: string, value: string, description?: string | undefined | null): Promise<Setting>
  /** 删除设置 */
  deleteSetting(key: string): Promise<void>
  getHomeLayout(workspaceKey: string): Promise<HomeLayout>
  createHomeCategory(input: CreateHomeCategoryInput): Promise<HomeCategory>
  updateHomeCategory(categoryId: string, input: UpdateHomeCategoryInput): Promise<HomeCategory>
  deleteHomeCategory(categoryId: string): Promise<void>
  createHomeWidget(input: CreateHomeWidgetInput): Promise<HomeWidget>
  updateHomeWidget(widgetId: string, input: UpdateHomeWidgetInput): Promise<HomeWidget>
  deleteHomeWidget(widgetId: string): Promise<void>
  importHomeLayout(workspaceKey: string, input: ImportHomeLayoutInput): Promise<HomeLayout>
  createTodoList(input: CreateTodoListInput): Promise<TodoList>
  updateTodoList(listId: string, input: UpdateTodoListInput): Promise<TodoList>
  deleteTodoList(listId: string): Promise<void>
  getAllTodoLists(): Promise<Array<TodoList>>
  reorderTodoLists(ids: Array<string>): Promise<void>
  createTodo(input: CreateTodoInput): Promise<Todo>
  updateTodo(todoId: string, input: UpdateTodoInput): Promise<Todo>
  deleteTodo(todoId: string): Promise<void>
  completeTodo(todoId: string): Promise<CompleteTodoResult>
  uncompleteTodo(todoId: string): Promise<Todo>
  getTodosByList(listId: string, includeCompleted: boolean): Promise<Array<Todo>>
  searchTodos(query: string): Promise<Array<Todo>>
  moveTodo(todoId: string, targetListId: string): Promise<Todo>
  getMyDayTodos(date: string): Promise<Array<Todo>>
  getImportantTodos(): Promise<Array<Todo>>
  getPlannedTodos(): Promise<Array<Todo>>
  getAllTodos(): Promise<Array<Todo>>
  getCompletedTodos(): Promise<Array<Todo>>
  addTodoToMyDay(todoId: string, date: string): Promise<void>
  removeTodoFromMyDay(todoId: string): Promise<void>
  getYesterdayIncompleteTodos(today: string): Promise<Array<Todo>>
  getMyDaySuggestions(today: string): Promise<Array<Todo>>
  createTodoStep(input: CreateTodoStepInput): Promise<TodoStep>
  updateTodoStep(stepId: string, input: UpdateTodoStepInput): Promise<TodoStep>
  deleteTodoStep(stepId: string): Promise<void>
  reorderTodoSteps(ids: Array<string>): Promise<void>
  createTodoReminder(input: CreateTodoReminderInput): Promise<TodoReminder>
  deleteTodoReminder(reminderId: string): Promise<void>
  getRemindersByTodo(todoId: string): Promise<Array<TodoReminder>>
  getPendingReminders(now: string): Promise<Array<TodoReminder>>
  markReminderSent(reminderId: string): Promise<void>
  getHomeWorkspaceBackground(workspaceKey: string): Promise<string | null>
  updateHomeWorkspaceBackground(workspaceKey: string, headerBackground?: string | undefined | null, sidebarBackground?: string | undefined | null): Promise<void>
  listInstalledPlugins(): Promise<Array<string>>
  upsertPlugin(recordJson: string): Promise<void>
  removePlugin(pluginId: string): Promise<void>
  getPluginStateValue(pluginId: string, key: string): Promise<string | null>
  setPluginStateValue(pluginId: string, key: string, value: string): Promise<void>
  deletePluginStateValue(pluginId: string, key: string): Promise<void>
}
