// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class HomeLayout {
  final String workspaceKey;
  final List<HomeLayoutCategory> categories;

  const HomeLayout({required this.workspaceKey, required this.categories});

  @override
  int get hashCode => workspaceKey.hashCode ^ categories.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeLayout &&
          runtimeType == other.runtimeType &&
          workspaceKey == other.workspaceKey &&
          categories == other.categories;
}

class HomeLayoutCategory {
  final String id;
  final PlatformInt64 workspaceId;
  final String label;
  final String icon;
  final PlatformInt64 sortOrder;
  final String? backgroundColor;
  final String? backgroundImage;
  final String? backgroundVideo;
  final String? backgroundStyle;
  final List<HomeWidget> widgets;

  const HomeLayoutCategory({
    required this.id,
    required this.workspaceId,
    required this.label,
    required this.icon,
    required this.sortOrder,
    this.backgroundColor,
    this.backgroundImage,
    this.backgroundVideo,
    this.backgroundStyle,
    required this.widgets,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      workspaceId.hashCode ^
      label.hashCode ^
      icon.hashCode ^
      sortOrder.hashCode ^
      backgroundColor.hashCode ^
      backgroundImage.hashCode ^
      backgroundVideo.hashCode ^
      backgroundStyle.hashCode ^
      widgets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeLayoutCategory &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          workspaceId == other.workspaceId &&
          label == other.label &&
          icon == other.icon &&
          sortOrder == other.sortOrder &&
          backgroundColor == other.backgroundColor &&
          backgroundImage == other.backgroundImage &&
          backgroundVideo == other.backgroundVideo &&
          backgroundStyle == other.backgroundStyle &&
          widgets == other.widgets;
}

class HomeWidget {
  final String id;
  final PlatformInt64 workspaceId;
  final String categoryId;
  final String label;
  final String? icon;
  final String? action;
  final String sourceType;
  final String widgetType;
  final String? sizePreset;
  final String? widgetConfig;
  final PlatformInt64 col;
  final PlatformInt64 row;
  final PlatformInt64 colSpan;
  final PlatformInt64 rowSpan;
  final PlatformInt64 preferredCol;
  final PlatformInt64 preferredRow;
  final PlatformInt64 priority;
  final String color;
  final String? backgroundImage;
  final String? backgroundVideo;
  final String? backgroundStyle;
  final bool hidden;
  final String createdAt;
  final String updatedAt;

  const HomeWidget({
    required this.id,
    required this.workspaceId,
    required this.categoryId,
    required this.label,
    this.icon,
    this.action,
    required this.sourceType,
    required this.widgetType,
    this.sizePreset,
    this.widgetConfig,
    required this.col,
    required this.row,
    required this.colSpan,
    required this.rowSpan,
    required this.preferredCol,
    required this.preferredRow,
    required this.priority,
    required this.color,
    this.backgroundImage,
    this.backgroundVideo,
    this.backgroundStyle,
    required this.hidden,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      workspaceId.hashCode ^
      categoryId.hashCode ^
      label.hashCode ^
      icon.hashCode ^
      action.hashCode ^
      sourceType.hashCode ^
      widgetType.hashCode ^
      sizePreset.hashCode ^
      widgetConfig.hashCode ^
      col.hashCode ^
      row.hashCode ^
      colSpan.hashCode ^
      rowSpan.hashCode ^
      preferredCol.hashCode ^
      preferredRow.hashCode ^
      priority.hashCode ^
      color.hashCode ^
      backgroundImage.hashCode ^
      backgroundVideo.hashCode ^
      backgroundStyle.hashCode ^
      hidden.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeWidget &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          workspaceId == other.workspaceId &&
          categoryId == other.categoryId &&
          label == other.label &&
          icon == other.icon &&
          action == other.action &&
          sourceType == other.sourceType &&
          widgetType == other.widgetType &&
          sizePreset == other.sizePreset &&
          widgetConfig == other.widgetConfig &&
          col == other.col &&
          row == other.row &&
          colSpan == other.colSpan &&
          rowSpan == other.rowSpan &&
          preferredCol == other.preferredCol &&
          preferredRow == other.preferredRow &&
          priority == other.priority &&
          color == other.color &&
          backgroundImage == other.backgroundImage &&
          backgroundVideo == other.backgroundVideo &&
          backgroundStyle == other.backgroundStyle &&
          hidden == other.hidden &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class SaveMobileHomeCategoryLayoutInput {
  final String categoryId;
  final List<SaveMobileHomeWidgetLayoutInput> widgets;

  const SaveMobileHomeCategoryLayoutInput({
    required this.categoryId,
    required this.widgets,
  });

  @override
  int get hashCode => categoryId.hashCode ^ widgets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveMobileHomeCategoryLayoutInput &&
          runtimeType == other.runtimeType &&
          categoryId == other.categoryId &&
          widgets == other.widgets;
}

class SaveMobileHomeWidgetLayoutInput {
  final String widgetId;
  final PlatformInt64 col;
  final PlatformInt64 row;
  final PlatformInt64 colSpan;
  final PlatformInt64 rowSpan;
  final PlatformInt64 preferredCol;
  final PlatformInt64 preferredRow;
  final PlatformInt64 priority;
  final bool hidden;

  const SaveMobileHomeWidgetLayoutInput({
    required this.widgetId,
    required this.col,
    required this.row,
    required this.colSpan,
    required this.rowSpan,
    required this.preferredCol,
    required this.preferredRow,
    required this.priority,
    required this.hidden,
  });

  @override
  int get hashCode =>
      widgetId.hashCode ^
      col.hashCode ^
      row.hashCode ^
      colSpan.hashCode ^
      rowSpan.hashCode ^
      preferredCol.hashCode ^
      preferredRow.hashCode ^
      priority.hashCode ^
      hidden.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveMobileHomeWidgetLayoutInput &&
          runtimeType == other.runtimeType &&
          widgetId == other.widgetId &&
          col == other.col &&
          row == other.row &&
          colSpan == other.colSpan &&
          rowSpan == other.rowSpan &&
          preferredCol == other.preferredCol &&
          preferredRow == other.preferredRow &&
          priority == other.priority &&
          hidden == other.hidden;
}
