// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MultiDeviceClipboardDevice {
  final String id;
  final String name;
  final String platform;
  final String? publicKey;
  final bool trusted;
  final bool isSelf;
  final String? lastAddress;
  final int? lastPort;
  final PlatformInt64? lastSeenAt;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const MultiDeviceClipboardDevice({
    required this.id,
    required this.name,
    required this.platform,
    this.publicKey,
    required this.trusted,
    required this.isSelf,
    this.lastAddress,
    this.lastPort,
    this.lastSeenAt,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      platform.hashCode ^
      publicKey.hashCode ^
      trusted.hashCode ^
      isSelf.hashCode ^
      lastAddress.hashCode ^
      lastPort.hashCode ^
      lastSeenAt.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MultiDeviceClipboardDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          platform == other.platform &&
          publicKey == other.publicKey &&
          trusted == other.trusted &&
          isSelf == other.isSelf &&
          lastAddress == other.lastAddress &&
          lastPort == other.lastPort &&
          lastSeenAt == other.lastSeenAt &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class MultiDeviceClipboardDeviceStatus {
  final String deviceId;
  final String name;
  final String platform;
  final bool trusted;
  final bool isSelf;
  final String state;
  final bool online;
  final String? lastAddress;
  final int? lastPort;
  final PlatformInt64? lastSeenAt;
  final PlatformInt64? secondsSinceSeen;

  const MultiDeviceClipboardDeviceStatus({
    required this.deviceId,
    required this.name,
    required this.platform,
    required this.trusted,
    required this.isSelf,
    required this.state,
    required this.online,
    this.lastAddress,
    this.lastPort,
    this.lastSeenAt,
    this.secondsSinceSeen,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      name.hashCode ^
      platform.hashCode ^
      trusted.hashCode ^
      isSelf.hashCode ^
      state.hashCode ^
      online.hashCode ^
      lastAddress.hashCode ^
      lastPort.hashCode ^
      lastSeenAt.hashCode ^
      secondsSinceSeen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MultiDeviceClipboardDeviceStatus &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          name == other.name &&
          platform == other.platform &&
          trusted == other.trusted &&
          isSelf == other.isSelf &&
          state == other.state &&
          online == other.online &&
          lastAddress == other.lastAddress &&
          lastPort == other.lastPort &&
          lastSeenAt == other.lastSeenAt &&
          secondsSinceSeen == other.secondsSinceSeen;
}

class MultiDeviceClipboardDiscoveredDevice {
  final String id;
  final String name;
  final String platform;
  final String address;
  final int port;
  final String serviceName;
  final PlatformInt64 lastSeenAt;

  const MultiDeviceClipboardDiscoveredDevice({
    required this.id,
    required this.name,
    required this.platform,
    required this.address,
    required this.port,
    required this.serviceName,
    required this.lastSeenAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      platform.hashCode ^
      address.hashCode ^
      port.hashCode ^
      serviceName.hashCode ^
      lastSeenAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MultiDeviceClipboardDiscoveredDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          platform == other.platform &&
          address == other.address &&
          port == other.port &&
          serviceName == other.serviceName &&
          lastSeenAt == other.lastSeenAt;
}

class MultiDeviceClipboardDiscoveryConfig {
  final String deviceId;
  final String deviceName;
  final int port;
  final String? platform;
  final String? preferredAddress;
  final List<String> probeLocalAddresses;
  final bool? httpProbeEnabled;

  const MultiDeviceClipboardDiscoveryConfig({
    required this.deviceId,
    required this.deviceName,
    required this.port,
    this.platform,
    this.preferredAddress,
    required this.probeLocalAddresses,
    this.httpProbeEnabled,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      port.hashCode ^
      platform.hashCode ^
      preferredAddress.hashCode ^
      probeLocalAddresses.hashCode ^
      httpProbeEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MultiDeviceClipboardDiscoveryConfig &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          port == other.port &&
          platform == other.platform &&
          preferredAddress == other.preferredAddress &&
          probeLocalAddresses == other.probeLocalAddresses &&
          httpProbeEnabled == other.httpProbeEnabled;
}

class MultiDeviceClipboardItem {
  final String id;
  final String sourceDeviceId;
  final String sourceDeviceName;
  final String contentType;
  final String? mimeType;
  final String? text;
  final String? fileName;
  final String? assetPath;
  final String? previewPath;
  final PlatformInt64 byteSize;
  final String contentHash;
  final String tagsJson;
  final bool localOnly;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const MultiDeviceClipboardItem({
    required this.id,
    required this.sourceDeviceId,
    required this.sourceDeviceName,
    required this.contentType,
    this.mimeType,
    this.text,
    this.fileName,
    this.assetPath,
    this.previewPath,
    required this.byteSize,
    required this.contentHash,
    required this.tagsJson,
    required this.localOnly,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sourceDeviceId.hashCode ^
      sourceDeviceName.hashCode ^
      contentType.hashCode ^
      mimeType.hashCode ^
      text.hashCode ^
      fileName.hashCode ^
      assetPath.hashCode ^
      previewPath.hashCode ^
      byteSize.hashCode ^
      contentHash.hashCode ^
      tagsJson.hashCode ^
      localOnly.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MultiDeviceClipboardItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sourceDeviceId == other.sourceDeviceId &&
          sourceDeviceName == other.sourceDeviceName &&
          contentType == other.contentType &&
          mimeType == other.mimeType &&
          text == other.text &&
          fileName == other.fileName &&
          assetPath == other.assetPath &&
          previewPath == other.previewPath &&
          byteSize == other.byteSize &&
          contentHash == other.contentHash &&
          tagsJson == other.tagsJson &&
          localOnly == other.localOnly &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class UpsertMultiDeviceClipboardDeviceInput {
  final String id;
  final String name;
  final String? platform;
  final String? publicKey;
  final bool? trusted;
  final bool? isSelf;
  final String? lastAddress;
  final int? lastPort;
  final PlatformInt64? lastSeenAt;

  const UpsertMultiDeviceClipboardDeviceInput({
    required this.id,
    required this.name,
    this.platform,
    this.publicKey,
    this.trusted,
    this.isSelf,
    this.lastAddress,
    this.lastPort,
    this.lastSeenAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      platform.hashCode ^
      publicKey.hashCode ^
      trusted.hashCode ^
      isSelf.hashCode ^
      lastAddress.hashCode ^
      lastPort.hashCode ^
      lastSeenAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpsertMultiDeviceClipboardDeviceInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          platform == other.platform &&
          publicKey == other.publicKey &&
          trusted == other.trusted &&
          isSelf == other.isSelf &&
          lastAddress == other.lastAddress &&
          lastPort == other.lastPort &&
          lastSeenAt == other.lastSeenAt;
}

class UpsertMultiDeviceClipboardItemInput {
  final String id;
  final String sourceDeviceId;
  final String sourceDeviceName;
  final String contentType;
  final String? mimeType;
  final String? text;
  final String? fileName;
  final String? assetPath;
  final String? previewPath;
  final PlatformInt64? byteSize;
  final String contentHash;
  final String? tagsJson;
  final bool? localOnly;
  final PlatformInt64? createdAt;

  const UpsertMultiDeviceClipboardItemInput({
    required this.id,
    required this.sourceDeviceId,
    required this.sourceDeviceName,
    required this.contentType,
    this.mimeType,
    this.text,
    this.fileName,
    this.assetPath,
    this.previewPath,
    this.byteSize,
    required this.contentHash,
    this.tagsJson,
    this.localOnly,
    this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sourceDeviceId.hashCode ^
      sourceDeviceName.hashCode ^
      contentType.hashCode ^
      mimeType.hashCode ^
      text.hashCode ^
      fileName.hashCode ^
      assetPath.hashCode ^
      previewPath.hashCode ^
      byteSize.hashCode ^
      contentHash.hashCode ^
      tagsJson.hashCode ^
      localOnly.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpsertMultiDeviceClipboardItemInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sourceDeviceId == other.sourceDeviceId &&
          sourceDeviceName == other.sourceDeviceName &&
          contentType == other.contentType &&
          mimeType == other.mimeType &&
          text == other.text &&
          fileName == other.fileName &&
          assetPath == other.assetPath &&
          previewPath == other.previewPath &&
          byteSize == other.byteSize &&
          contentHash == other.contentHash &&
          tagsJson == other.tagsJson &&
          localOnly == other.localOnly &&
          createdAt == other.createdAt;
}
