// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 515536374;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__bindings__mobile_clipboard__clamp_mobile_clipboard_sync_bytes_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "clamp_mobile_clipboard_sync_bytes",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_value = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::bindings::mobile_clipboard::clamp_mobile_clipboard_sync_bytes(
                            api_value,
                        ),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__bindings__mobile_clipboard__classify_mobile_clipboard_text_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "classify_mobile_clipboard_text",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_text = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::bindings::mobile_clipboard::classify_mobile_clipboard_text(api_text),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__bindings__mobile_clipboard__clear_mobile_clipboard_history_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "clear_mobile_clipboard_history",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::bindings::mobile_clipboard::clear_mobile_clipboard_history(
                                api_host_id,
                            )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__bindings__mobile_clipboard__compute_mobile_clipboard_content_hash_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "compute_mobile_clipboard_content_hash",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_parts = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::bindings::mobile_clipboard::compute_mobile_clipboard_content_hash(
                            api_parts,
                        ),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__bindings__mobile_clipboard__create_mobile_clipboard_host_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_mobile_clipboard_host",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_db_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::bindings::mobile_clipboard::create_mobile_clipboard_host(
                                api_db_path,
                            )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__bindings__mobile_clipboard__delete_mobile_clipboard_item_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "delete_mobile_clipboard_item",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
            let api_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::bindings::mobile_clipboard::delete_mobile_clipboard_item(
                                api_host_id,
                                api_id,
                            )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__bindings__mobile_clipboard__dispose_mobile_clipboard_host_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "dispose_mobile_clipboard_host",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::bindings::mobile_clipboard::dispose_mobile_clipboard_host(
                                api_host_id,
                            )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__bindings__mobile_clipboard__forget_mobile_clipboard_device_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "forget_mobile_clipboard_device",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
            let api_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::bindings::mobile_clipboard::forget_mobile_clipboard_device(
                                api_host_id,
                                api_id,
                            )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__bindings__mobile_clipboard__get_mobile_clipboard_item_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_mobile_clipboard_item",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
            let api_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::bindings::mobile_clipboard::get_mobile_clipboard_item(
                                api_host_id,
                                api_id,
                            )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__bindings__mobile_clipboard__get_or_create_mobile_clipboard_local_device_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "get_or_create_mobile_clipboard_local_device", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
let api_name = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move ||  {
                         let output_ok = crate::bindings::mobile_clipboard::get_or_create_mobile_clipboard_local_device(api_host_id, api_name)?;   Ok(output_ok)
                    })())
                } })
}
fn wire__crate__bindings__mobile_clipboard__list_mobile_clipboard_device_statuses_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "list_mobile_clipboard_device_statuses", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
let api_online_window_seconds = <i64>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move ||  {
                         let output_ok = crate::bindings::mobile_clipboard::list_mobile_clipboard_device_statuses(api_host_id, api_online_window_seconds)?;   Ok(output_ok)
                    })())
                } })
}
fn wire__crate__bindings__mobile_clipboard__list_mobile_clipboard_devices_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_mobile_clipboard_devices",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::bindings::mobile_clipboard::list_mobile_clipboard_devices(
                                api_host_id,
                            )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__bindings__mobile_clipboard__list_mobile_clipboard_discovered_devices_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "list_mobile_clipboard_discovered_devices", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move ||  {
                         let output_ok = crate::bindings::mobile_clipboard::list_mobile_clipboard_discovered_devices(api_host_id)?;   Ok(output_ok)
                    })())
                } })
}
fn wire__crate__bindings__mobile_clipboard__list_mobile_clipboard_items_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_mobile_clipboard_items",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
            let api_limit = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::bindings::mobile_clipboard::list_mobile_clipboard_items(
                                api_host_id,
                                api_limit,
                            )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__bindings__mobile_clipboard__prune_mobile_clipboard_history_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "prune_mobile_clipboard_history",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
            let api_history_limit = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::bindings::mobile_clipboard::prune_mobile_clipboard_history(
                                api_host_id,
                                api_history_limit,
                            )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__bindings__mobile_clipboard__set_mobile_clipboard_device_trusted_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_mobile_clipboard_device_trusted",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
            let api_id = <String>::sse_decode(&mut deserializer);
            let api_trusted = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::bindings::mobile_clipboard::set_mobile_clipboard_device_trusted(
                                api_host_id,
                                api_id,
                                api_trusted,
                            )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__bindings__mobile_clipboard__start_mobile_clipboard_discovery_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "start_mobile_clipboard_discovery", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
let api_config = <crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveryConfig>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move ||  {
                         let output_ok = crate::bindings::mobile_clipboard::start_mobile_clipboard_discovery(api_host_id, api_config)?;   Ok(output_ok)
                    })())
                } })
}
fn wire__crate__bindings__mobile_clipboard__stop_mobile_clipboard_discovery_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop_mobile_clipboard_discovery",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::bindings::mobile_clipboard::stop_mobile_clipboard_discovery(
                                api_host_id,
                            )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__bindings__mobile_clipboard__upsert_mobile_clipboard_device_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "upsert_mobile_clipboard_device", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
let api_input = <crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardDeviceInput>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move ||  {
                         let output_ok = crate::bindings::mobile_clipboard::upsert_mobile_clipboard_device(api_host_id, api_input)?;   Ok(output_ok)
                    })())
                } })
}
fn wire__crate__bindings__mobile_clipboard__upsert_mobile_clipboard_item_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "upsert_mobile_clipboard_item", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_host_id = <String>::sse_decode(&mut deserializer);
let api_input = <crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardItemInput>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move ||  {
                         let output_ok = crate::bindings::mobile_clipboard::upsert_mobile_clipboard_item(api_host_id, api_input)?;   Ok(output_ok)
                    })())
                } })
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::models::multi_device_clipboard::MultiDeviceClipboardDevice> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(
                <crate::models::multi_device_clipboard::MultiDeviceClipboardDevice>::sse_decode(
                    deserializer,
                ),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::models::multi_device_clipboard::MultiDeviceClipboardDeviceStatus> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::models::multi_device_clipboard::MultiDeviceClipboardDeviceStatus>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode
    for Vec<crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveredDevice>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveredDevice>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::models::multi_device_clipboard::MultiDeviceClipboardItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(
                <crate::models::multi_device_clipboard::MultiDeviceClipboardItem>::sse_decode(
                    deserializer,
                ),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::models::multi_device_clipboard::MultiDeviceClipboardDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_platform = <String>::sse_decode(deserializer);
        let mut var_publicKey = <Option<String>>::sse_decode(deserializer);
        let mut var_trusted = <bool>::sse_decode(deserializer);
        let mut var_isSelf = <bool>::sse_decode(deserializer);
        let mut var_lastAddress = <Option<String>>::sse_decode(deserializer);
        let mut var_lastPort = <Option<u32>>::sse_decode(deserializer);
        let mut var_lastSeenAt = <Option<i64>>::sse_decode(deserializer);
        let mut var_createdAt = <i64>::sse_decode(deserializer);
        let mut var_updatedAt = <i64>::sse_decode(deserializer);
        return crate::models::multi_device_clipboard::MultiDeviceClipboardDevice {
            id: var_id,
            name: var_name,
            platform: var_platform,
            public_key: var_publicKey,
            trusted: var_trusted,
            is_self: var_isSelf,
            last_address: var_lastAddress,
            last_port: var_lastPort,
            last_seen_at: var_lastSeenAt,
            created_at: var_createdAt,
            updated_at: var_updatedAt,
        };
    }
}

impl SseDecode for crate::models::multi_device_clipboard::MultiDeviceClipboardDeviceStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_deviceId = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_platform = <String>::sse_decode(deserializer);
        let mut var_trusted = <bool>::sse_decode(deserializer);
        let mut var_isSelf = <bool>::sse_decode(deserializer);
        let mut var_state = <String>::sse_decode(deserializer);
        let mut var_online = <bool>::sse_decode(deserializer);
        let mut var_lastAddress = <Option<String>>::sse_decode(deserializer);
        let mut var_lastPort = <Option<u32>>::sse_decode(deserializer);
        let mut var_lastSeenAt = <Option<i64>>::sse_decode(deserializer);
        let mut var_secondsSinceSeen = <Option<i64>>::sse_decode(deserializer);
        return crate::models::multi_device_clipboard::MultiDeviceClipboardDeviceStatus {
            device_id: var_deviceId,
            name: var_name,
            platform: var_platform,
            trusted: var_trusted,
            is_self: var_isSelf,
            state: var_state,
            online: var_online,
            last_address: var_lastAddress,
            last_port: var_lastPort,
            last_seen_at: var_lastSeenAt,
            seconds_since_seen: var_secondsSinceSeen,
        };
    }
}

impl SseDecode for crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveredDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_platform = <String>::sse_decode(deserializer);
        let mut var_address = <String>::sse_decode(deserializer);
        let mut var_port = <u32>::sse_decode(deserializer);
        let mut var_serviceName = <String>::sse_decode(deserializer);
        let mut var_lastSeenAt = <i64>::sse_decode(deserializer);
        return crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveredDevice {
            id: var_id,
            name: var_name,
            platform: var_platform,
            address: var_address,
            port: var_port,
            service_name: var_serviceName,
            last_seen_at: var_lastSeenAt,
        };
    }
}

impl SseDecode for crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveryConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_deviceId = <String>::sse_decode(deserializer);
        let mut var_deviceName = <String>::sse_decode(deserializer);
        let mut var_port = <u32>::sse_decode(deserializer);
        let mut var_platform = <Option<String>>::sse_decode(deserializer);
        let mut var_preferredAddress = <Option<String>>::sse_decode(deserializer);
        let mut var_probeLocalAddresses = <Vec<String>>::sse_decode(deserializer);
        let mut var_httpProbeEnabled = <Option<bool>>::sse_decode(deserializer);
        return crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveryConfig {
            device_id: var_deviceId,
            device_name: var_deviceName,
            port: var_port,
            platform: var_platform,
            preferred_address: var_preferredAddress,
            probe_local_addresses: var_probeLocalAddresses,
            http_probe_enabled: var_httpProbeEnabled,
        };
    }
}

impl SseDecode for crate::models::multi_device_clipboard::MultiDeviceClipboardItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_sourceDeviceId = <String>::sse_decode(deserializer);
        let mut var_sourceDeviceName = <String>::sse_decode(deserializer);
        let mut var_contentType = <String>::sse_decode(deserializer);
        let mut var_mimeType = <Option<String>>::sse_decode(deserializer);
        let mut var_text = <Option<String>>::sse_decode(deserializer);
        let mut var_fileName = <Option<String>>::sse_decode(deserializer);
        let mut var_assetPath = <Option<String>>::sse_decode(deserializer);
        let mut var_previewPath = <Option<String>>::sse_decode(deserializer);
        let mut var_byteSize = <i64>::sse_decode(deserializer);
        let mut var_contentHash = <String>::sse_decode(deserializer);
        let mut var_tagsJson = <String>::sse_decode(deserializer);
        let mut var_localOnly = <bool>::sse_decode(deserializer);
        let mut var_createdAt = <i64>::sse_decode(deserializer);
        let mut var_updatedAt = <i64>::sse_decode(deserializer);
        return crate::models::multi_device_clipboard::MultiDeviceClipboardItem {
            id: var_id,
            source_device_id: var_sourceDeviceId,
            source_device_name: var_sourceDeviceName,
            content_type: var_contentType,
            mime_type: var_mimeType,
            text: var_text,
            file_name: var_fileName,
            asset_path: var_assetPath,
            preview_path: var_previewPath,
            byte_size: var_byteSize,
            content_hash: var_contentHash,
            tags_json: var_tagsJson,
            local_only: var_localOnly,
            created_at: var_createdAt,
            updated_at: var_updatedAt,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<bool> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<bool>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardDeviceInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_platform = <Option<String>>::sse_decode(deserializer);
        let mut var_publicKey = <Option<String>>::sse_decode(deserializer);
        let mut var_trusted = <Option<bool>>::sse_decode(deserializer);
        let mut var_isSelf = <Option<bool>>::sse_decode(deserializer);
        let mut var_lastAddress = <Option<String>>::sse_decode(deserializer);
        let mut var_lastPort = <Option<u32>>::sse_decode(deserializer);
        let mut var_lastSeenAt = <Option<i64>>::sse_decode(deserializer);
        return crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardDeviceInput {
            id: var_id,
            name: var_name,
            platform: var_platform,
            public_key: var_publicKey,
            trusted: var_trusted,
            is_self: var_isSelf,
            last_address: var_lastAddress,
            last_port: var_lastPort,
            last_seen_at: var_lastSeenAt,
        };
    }
}

impl SseDecode for crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardItemInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_sourceDeviceId = <String>::sse_decode(deserializer);
        let mut var_sourceDeviceName = <String>::sse_decode(deserializer);
        let mut var_contentType = <String>::sse_decode(deserializer);
        let mut var_mimeType = <Option<String>>::sse_decode(deserializer);
        let mut var_text = <Option<String>>::sse_decode(deserializer);
        let mut var_fileName = <Option<String>>::sse_decode(deserializer);
        let mut var_assetPath = <Option<String>>::sse_decode(deserializer);
        let mut var_previewPath = <Option<String>>::sse_decode(deserializer);
        let mut var_byteSize = <Option<i64>>::sse_decode(deserializer);
        let mut var_contentHash = <String>::sse_decode(deserializer);
        let mut var_tagsJson = <Option<String>>::sse_decode(deserializer);
        let mut var_localOnly = <Option<bool>>::sse_decode(deserializer);
        let mut var_createdAt = <Option<i64>>::sse_decode(deserializer);
        return crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardItemInput {
            id: var_id,
            source_device_id: var_sourceDeviceId,
            source_device_name: var_sourceDeviceName,
            content_type: var_contentType,
            mime_type: var_mimeType,
            text: var_text,
            file_name: var_fileName,
            asset_path: var_assetPath,
            preview_path: var_previewPath,
            byte_size: var_byteSize,
            content_hash: var_contentHash,
            tags_json: var_tagsJson,
            local_only: var_localOnly,
            created_at: var_createdAt,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
                        1 => wire__crate__bindings__mobile_clipboard__clamp_mobile_clipboard_sync_bytes_impl(port, ptr, rust_vec_len, data_len),
2 => wire__crate__bindings__mobile_clipboard__classify_mobile_clipboard_text_impl(port, ptr, rust_vec_len, data_len),
3 => wire__crate__bindings__mobile_clipboard__clear_mobile_clipboard_history_impl(port, ptr, rust_vec_len, data_len),
4 => wire__crate__bindings__mobile_clipboard__compute_mobile_clipboard_content_hash_impl(port, ptr, rust_vec_len, data_len),
5 => wire__crate__bindings__mobile_clipboard__create_mobile_clipboard_host_impl(port, ptr, rust_vec_len, data_len),
6 => wire__crate__bindings__mobile_clipboard__delete_mobile_clipboard_item_impl(port, ptr, rust_vec_len, data_len),
7 => wire__crate__bindings__mobile_clipboard__dispose_mobile_clipboard_host_impl(port, ptr, rust_vec_len, data_len),
8 => wire__crate__bindings__mobile_clipboard__forget_mobile_clipboard_device_impl(port, ptr, rust_vec_len, data_len),
9 => wire__crate__bindings__mobile_clipboard__get_mobile_clipboard_item_impl(port, ptr, rust_vec_len, data_len),
10 => wire__crate__bindings__mobile_clipboard__get_or_create_mobile_clipboard_local_device_impl(port, ptr, rust_vec_len, data_len),
11 => wire__crate__bindings__mobile_clipboard__list_mobile_clipboard_device_statuses_impl(port, ptr, rust_vec_len, data_len),
12 => wire__crate__bindings__mobile_clipboard__list_mobile_clipboard_devices_impl(port, ptr, rust_vec_len, data_len),
13 => wire__crate__bindings__mobile_clipboard__list_mobile_clipboard_discovered_devices_impl(port, ptr, rust_vec_len, data_len),
14 => wire__crate__bindings__mobile_clipboard__list_mobile_clipboard_items_impl(port, ptr, rust_vec_len, data_len),
15 => wire__crate__bindings__mobile_clipboard__prune_mobile_clipboard_history_impl(port, ptr, rust_vec_len, data_len),
16 => wire__crate__bindings__mobile_clipboard__set_mobile_clipboard_device_trusted_impl(port, ptr, rust_vec_len, data_len),
17 => wire__crate__bindings__mobile_clipboard__start_mobile_clipboard_discovery_impl(port, ptr, rust_vec_len, data_len),
18 => wire__crate__bindings__mobile_clipboard__stop_mobile_clipboard_discovery_impl(port, ptr, rust_vec_len, data_len),
19 => wire__crate__bindings__mobile_clipboard__upsert_mobile_clipboard_device_impl(port, ptr, rust_vec_len, data_len),
20 => wire__crate__bindings__mobile_clipboard__upsert_mobile_clipboard_item_impl(port, ptr, rust_vec_len, data_len),
                        _ => unreachable!(),
                    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart
    for crate::models::multi_device_clipboard::MultiDeviceClipboardDevice
{
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.platform.into_into_dart().into_dart(),
            self.public_key.into_into_dart().into_dart(),
            self.trusted.into_into_dart().into_dart(),
            self.is_self.into_into_dart().into_dart(),
            self.last_address.into_into_dart().into_dart(),
            self.last_port.into_into_dart().into_dart(),
            self.last_seen_at.into_into_dart().into_dart(),
            self.created_at.into_into_dart().into_dart(),
            self.updated_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::models::multi_device_clipboard::MultiDeviceClipboardDevice
{
}
impl
    flutter_rust_bridge::IntoIntoDart<
        crate::models::multi_device_clipboard::MultiDeviceClipboardDevice,
    > for crate::models::multi_device_clipboard::MultiDeviceClipboardDevice
{
    fn into_into_dart(self) -> crate::models::multi_device_clipboard::MultiDeviceClipboardDevice {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart
    for crate::models::multi_device_clipboard::MultiDeviceClipboardDeviceStatus
{
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.device_id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.platform.into_into_dart().into_dart(),
            self.trusted.into_into_dart().into_dart(),
            self.is_self.into_into_dart().into_dart(),
            self.state.into_into_dart().into_dart(),
            self.online.into_into_dart().into_dart(),
            self.last_address.into_into_dart().into_dart(),
            self.last_port.into_into_dart().into_dart(),
            self.last_seen_at.into_into_dart().into_dart(),
            self.seconds_since_seen.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::models::multi_device_clipboard::MultiDeviceClipboardDeviceStatus
{
}
impl
    flutter_rust_bridge::IntoIntoDart<
        crate::models::multi_device_clipboard::MultiDeviceClipboardDeviceStatus,
    > for crate::models::multi_device_clipboard::MultiDeviceClipboardDeviceStatus
{
    fn into_into_dart(
        self,
    ) -> crate::models::multi_device_clipboard::MultiDeviceClipboardDeviceStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart
    for crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveredDevice
{
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.platform.into_into_dart().into_dart(),
            self.address.into_into_dart().into_dart(),
            self.port.into_into_dart().into_dart(),
            self.service_name.into_into_dart().into_dart(),
            self.last_seen_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveredDevice
{
}
impl
    flutter_rust_bridge::IntoIntoDart<
        crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveredDevice,
    > for crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveredDevice
{
    fn into_into_dart(
        self,
    ) -> crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveredDevice {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart
    for crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveryConfig
{
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.device_id.into_into_dart().into_dart(),
            self.device_name.into_into_dart().into_dart(),
            self.port.into_into_dart().into_dart(),
            self.platform.into_into_dart().into_dart(),
            self.preferred_address.into_into_dart().into_dart(),
            self.probe_local_addresses.into_into_dart().into_dart(),
            self.http_probe_enabled.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveryConfig
{
}
impl
    flutter_rust_bridge::IntoIntoDart<
        crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveryConfig,
    > for crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveryConfig
{
    fn into_into_dart(
        self,
    ) -> crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveryConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart
    for crate::models::multi_device_clipboard::MultiDeviceClipboardItem
{
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.source_device_id.into_into_dart().into_dart(),
            self.source_device_name.into_into_dart().into_dart(),
            self.content_type.into_into_dart().into_dart(),
            self.mime_type.into_into_dart().into_dart(),
            self.text.into_into_dart().into_dart(),
            self.file_name.into_into_dart().into_dart(),
            self.asset_path.into_into_dart().into_dart(),
            self.preview_path.into_into_dart().into_dart(),
            self.byte_size.into_into_dart().into_dart(),
            self.content_hash.into_into_dart().into_dart(),
            self.tags_json.into_into_dart().into_dart(),
            self.local_only.into_into_dart().into_dart(),
            self.created_at.into_into_dart().into_dart(),
            self.updated_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::models::multi_device_clipboard::MultiDeviceClipboardItem
{
}
impl
    flutter_rust_bridge::IntoIntoDart<
        crate::models::multi_device_clipboard::MultiDeviceClipboardItem,
    > for crate::models::multi_device_clipboard::MultiDeviceClipboardItem
{
    fn into_into_dart(self) -> crate::models::multi_device_clipboard::MultiDeviceClipboardItem {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart
    for crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardDeviceInput
{
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.platform.into_into_dart().into_dart(),
            self.public_key.into_into_dart().into_dart(),
            self.trusted.into_into_dart().into_dart(),
            self.is_self.into_into_dart().into_dart(),
            self.last_address.into_into_dart().into_dart(),
            self.last_port.into_into_dart().into_dart(),
            self.last_seen_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardDeviceInput
{
}
impl
    flutter_rust_bridge::IntoIntoDart<
        crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardDeviceInput,
    > for crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardDeviceInput
{
    fn into_into_dart(
        self,
    ) -> crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardDeviceInput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart
    for crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardItemInput
{
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.source_device_id.into_into_dart().into_dart(),
            self.source_device_name.into_into_dart().into_dart(),
            self.content_type.into_into_dart().into_dart(),
            self.mime_type.into_into_dart().into_dart(),
            self.text.into_into_dart().into_dart(),
            self.file_name.into_into_dart().into_dart(),
            self.asset_path.into_into_dart().into_dart(),
            self.preview_path.into_into_dart().into_dart(),
            self.byte_size.into_into_dart().into_dart(),
            self.content_hash.into_into_dart().into_dart(),
            self.tags_json.into_into_dart().into_dart(),
            self.local_only.into_into_dart().into_dart(),
            self.created_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardItemInput
{
}
impl
    flutter_rust_bridge::IntoIntoDart<
        crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardItemInput,
    > for crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardItemInput
{
    fn into_into_dart(
        self,
    ) -> crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardItemInput {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::models::multi_device_clipboard::MultiDeviceClipboardDevice> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::models::multi_device_clipboard::MultiDeviceClipboardDevice>::sse_encode(
                item, serializer,
            );
        }
    }
}

impl SseEncode for Vec<crate::models::multi_device_clipboard::MultiDeviceClipboardDeviceStatus> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::models::multi_device_clipboard::MultiDeviceClipboardDeviceStatus>::sse_encode(
                item, serializer,
            );
        }
    }
}

impl SseEncode
    for Vec<crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveredDevice>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveredDevice>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::models::multi_device_clipboard::MultiDeviceClipboardItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::models::multi_device_clipboard::MultiDeviceClipboardItem>::sse_encode(
                item, serializer,
            );
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::models::multi_device_clipboard::MultiDeviceClipboardDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.platform, serializer);
        <Option<String>>::sse_encode(self.public_key, serializer);
        <bool>::sse_encode(self.trusted, serializer);
        <bool>::sse_encode(self.is_self, serializer);
        <Option<String>>::sse_encode(self.last_address, serializer);
        <Option<u32>>::sse_encode(self.last_port, serializer);
        <Option<i64>>::sse_encode(self.last_seen_at, serializer);
        <i64>::sse_encode(self.created_at, serializer);
        <i64>::sse_encode(self.updated_at, serializer);
    }
}

impl SseEncode for crate::models::multi_device_clipboard::MultiDeviceClipboardDeviceStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.device_id, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.platform, serializer);
        <bool>::sse_encode(self.trusted, serializer);
        <bool>::sse_encode(self.is_self, serializer);
        <String>::sse_encode(self.state, serializer);
        <bool>::sse_encode(self.online, serializer);
        <Option<String>>::sse_encode(self.last_address, serializer);
        <Option<u32>>::sse_encode(self.last_port, serializer);
        <Option<i64>>::sse_encode(self.last_seen_at, serializer);
        <Option<i64>>::sse_encode(self.seconds_since_seen, serializer);
    }
}

impl SseEncode for crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveredDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.platform, serializer);
        <String>::sse_encode(self.address, serializer);
        <u32>::sse_encode(self.port, serializer);
        <String>::sse_encode(self.service_name, serializer);
        <i64>::sse_encode(self.last_seen_at, serializer);
    }
}

impl SseEncode for crate::models::multi_device_clipboard::MultiDeviceClipboardDiscoveryConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.device_id, serializer);
        <String>::sse_encode(self.device_name, serializer);
        <u32>::sse_encode(self.port, serializer);
        <Option<String>>::sse_encode(self.platform, serializer);
        <Option<String>>::sse_encode(self.preferred_address, serializer);
        <Vec<String>>::sse_encode(self.probe_local_addresses, serializer);
        <Option<bool>>::sse_encode(self.http_probe_enabled, serializer);
    }
}

impl SseEncode for crate::models::multi_device_clipboard::MultiDeviceClipboardItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.source_device_id, serializer);
        <String>::sse_encode(self.source_device_name, serializer);
        <String>::sse_encode(self.content_type, serializer);
        <Option<String>>::sse_encode(self.mime_type, serializer);
        <Option<String>>::sse_encode(self.text, serializer);
        <Option<String>>::sse_encode(self.file_name, serializer);
        <Option<String>>::sse_encode(self.asset_path, serializer);
        <Option<String>>::sse_encode(self.preview_path, serializer);
        <i64>::sse_encode(self.byte_size, serializer);
        <String>::sse_encode(self.content_hash, serializer);
        <String>::sse_encode(self.tags_json, serializer);
        <bool>::sse_encode(self.local_only, serializer);
        <i64>::sse_encode(self.created_at, serializer);
        <i64>::sse_encode(self.updated_at, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<bool> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <bool>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardDeviceInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <Option<String>>::sse_encode(self.platform, serializer);
        <Option<String>>::sse_encode(self.public_key, serializer);
        <Option<bool>>::sse_encode(self.trusted, serializer);
        <Option<bool>>::sse_encode(self.is_self, serializer);
        <Option<String>>::sse_encode(self.last_address, serializer);
        <Option<u32>>::sse_encode(self.last_port, serializer);
        <Option<i64>>::sse_encode(self.last_seen_at, serializer);
    }
}

impl SseEncode for crate::models::multi_device_clipboard::UpsertMultiDeviceClipboardItemInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.source_device_id, serializer);
        <String>::sse_encode(self.source_device_name, serializer);
        <String>::sse_encode(self.content_type, serializer);
        <Option<String>>::sse_encode(self.mime_type, serializer);
        <Option<String>>::sse_encode(self.text, serializer);
        <Option<String>>::sse_encode(self.file_name, serializer);
        <Option<String>>::sse_encode(self.asset_path, serializer);
        <Option<String>>::sse_encode(self.preview_path, serializer);
        <Option<i64>>::sse_encode(self.byte_size, serializer);
        <String>::sse_encode(self.content_hash, serializer);
        <Option<String>>::sse_encode(self.tags_json, serializer);
        <Option<bool>>::sse_encode(self.local_only, serializer);
        <Option<i64>>::sse_encode(self.created_at, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
