/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GtButtonClickDetail } from "./components/gt-button/gt-button";
export { GtButtonClickDetail } from "./components/gt-button/gt-button";
export namespace Components {
    interface GtButton {
        /**
          * @default false
         */
        "active": boolean;
        /**
          * @default false
         */
        "block": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'secondary'
         */
        "variant": 'primary' | 'secondary' | 'ghost' | 'danger';
    }
}
export interface GtButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtButtonElement;
}
declare global {
    interface HTMLGtButtonElementEventMap {
        "gt-click": GtButtonClickDetail;
    }
    interface HTMLGtButtonElement extends Components.GtButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtButtonElementEventMap>(type: K, listener: (this: HTMLGtButtonElement, ev: GtButtonCustomEvent<HTMLGtButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtButtonElementEventMap>(type: K, listener: (this: HTMLGtButtonElement, ev: GtButtonCustomEvent<HTMLGtButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtButtonElement: {
        prototype: HTMLGtButtonElement;
        new (): HTMLGtButtonElement;
    };
    interface HTMLElementTagNameMap {
        "gt-button": HTMLGtButtonElement;
    }
}
declare namespace LocalJSX {
    interface GtButton {
        /**
          * @default false
         */
        "active"?: boolean;
        /**
          * @default false
         */
        "block"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onGt-click"?: (event: GtButtonCustomEvent<GtButtonClickDetail>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'secondary'
         */
        "variant"?: 'primary' | 'secondary' | 'ghost' | 'danger';
    }

    interface GtButtonAttributes {
        "variant": 'primary' | 'secondary' | 'ghost' | 'danger';
        "size": 'sm' | 'md' | 'lg';
        "disabled": boolean;
        "active": boolean;
        "block": boolean;
        "type": 'button' | 'submit' | 'reset';
    }

    interface IntrinsicElements {
        "gt-button": Omit<GtButton, keyof GtButtonAttributes> & { [K in keyof GtButton & keyof GtButtonAttributes]?: GtButton[K] } & { [K in keyof GtButton & keyof GtButtonAttributes as `attr:${K}`]?: GtButtonAttributes[K] } & { [K in keyof GtButton & keyof GtButtonAttributes as `prop:${K}`]?: GtButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gt-button": LocalJSX.IntrinsicElements["gt-button"] & JSXBase.HTMLAttributes<HTMLGtButtonElement>;
        }
    }
}
