/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GtButtonClickDetail } from "./components/gt-button/gt-button";
import { GtCheckedChangeDetail } from "./components/gt-checkbox/gt-checkbox";
import { GtDateChangeDetail } from "./components/gt-date-picker/gt-date-picker";
import { GtDateTimeChangeDetail, GtDateTimeMode, GtDateTimeValueFormat } from "./components/gt-date-time-picker/gt-date-time-picker";
import { GtOpenChangeDetail } from "./components/gt-dialog/gt-dialog";
import { GtDisclosureChangeDetail } from "./components/gt-disclosure/gt-disclosure";
import { GtOpenChangeDetail as GtOpenChangeDetail1 } from "./components/gt-dialog/gt-dialog";
import { GtIconButtonClickDetail } from "./components/gt-icon-button/gt-icon-button";
import { GtValueChangeDetail } from "./components/gt-input/gt-input";
import { GtMenuCloseDetail } from "./components/gt-menu/gt-menu";
import { GtMenuItemClickDetail } from "./components/gt-menu-item/gt-menu-item";
import { GtPopupOpenChangeDetail, GtPopupPlacement, GtPopupVariant } from "./components/gt-popup-surface/gt-popup-surface";
import { GtRadioChangeDetail } from "./components/gt-radio/gt-radio";
import { Event } from "@stencil/core";
import { GtSelectChangeDetail, GtSelectOption } from "./components/gt-select/gt-select";
import { GtSliderFieldChangeDetail } from "./components/gt-slider-field/gt-slider-field";
import { GtSwitchChangeDetail } from "./components/gt-switch/gt-switch";
import { GtTabChangeDetail, GtTabItem } from "./components/gt-tabs/gt-tabs";
import { GtValueChangeDetail as GtValueChangeDetail1 } from "./components/gt-input/gt-input";
import { GtTimeChangeDetail } from "./components/gt-time-picker/gt-time-picker";
import { OverlayPlacement } from "./utils/overlay-controller";
export { GtButtonClickDetail } from "./components/gt-button/gt-button";
export { GtCheckedChangeDetail } from "./components/gt-checkbox/gt-checkbox";
export { GtDateChangeDetail } from "./components/gt-date-picker/gt-date-picker";
export { GtDateTimeChangeDetail, GtDateTimeMode, GtDateTimeValueFormat } from "./components/gt-date-time-picker/gt-date-time-picker";
export { GtOpenChangeDetail } from "./components/gt-dialog/gt-dialog";
export { GtDisclosureChangeDetail } from "./components/gt-disclosure/gt-disclosure";
export { GtOpenChangeDetail as GtOpenChangeDetail1 } from "./components/gt-dialog/gt-dialog";
export { GtIconButtonClickDetail } from "./components/gt-icon-button/gt-icon-button";
export { GtValueChangeDetail } from "./components/gt-input/gt-input";
export { GtMenuCloseDetail } from "./components/gt-menu/gt-menu";
export { GtMenuItemClickDetail } from "./components/gt-menu-item/gt-menu-item";
export { GtPopupOpenChangeDetail, GtPopupPlacement, GtPopupVariant } from "./components/gt-popup-surface/gt-popup-surface";
export { GtRadioChangeDetail } from "./components/gt-radio/gt-radio";
export { Event } from "@stencil/core";
export { GtSelectChangeDetail, GtSelectOption } from "./components/gt-select/gt-select";
export { GtSliderFieldChangeDetail } from "./components/gt-slider-field/gt-slider-field";
export { GtSwitchChangeDetail } from "./components/gt-switch/gt-switch";
export { GtTabChangeDetail, GtTabItem } from "./components/gt-tabs/gt-tabs";
export { GtValueChangeDetail as GtValueChangeDetail1 } from "./components/gt-input/gt-input";
export { GtTimeChangeDetail } from "./components/gt-time-picker/gt-time-picker";
export { OverlayPlacement } from "./utils/overlay-controller";
export namespace Components {
    interface GtButton {
        /**
          * @default false
         */
        "active": boolean;
        /**
          * @default false
         */
        "block": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'secondary'
         */
        "variant": 'primary' | 'secondary' | 'ghost' | 'danger';
    }
    interface GtCard {
        /**
          * @default true
         */
        "bordered": boolean;
        /**
          * @default false
         */
        "hoverable": boolean;
        /**
          * @default false
         */
        "interactive": boolean;
        /**
          * @default 'md'
         */
        "padding": 'none' | 'sm' | 'md' | 'lg';
        /**
          * @default 'md'
         */
        "radius": 'none' | 'sm' | 'md' | 'lg';
        /**
          * @default 'default'
         */
        "variant": 'default' | 'muted' | 'elevated';
    }
    interface GtCheckbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "indeterminate": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md';
        /**
          * @default ''
         */
        "value": string;
    }
    interface GtDatePicker {
        /**
          * @default true
         */
        "clearable": boolean;
        /**
          * @default true
         */
        "closeOnOutside": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "max": string;
        /**
          * @default ''
         */
        "min": string;
        /**
          * @default '选择日期'
         */
        "placeholder": string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default ''
         */
        "value": string;
    }
    interface GtDateTimePicker {
        /**
          * @default true
         */
        "clearable": boolean;
        /**
          * @default true
         */
        "closeOnOutside": boolean;
        /**
          * @default '日期'
         */
        "datePlaceholder": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 5
         */
        "minuteStep": number;
        /**
          * @default 'datetime'
         */
        "mode": GtDateTimeMode;
        /**
          * @default '选择日期和时间'
         */
        "placeholder": string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default '时间'
         */
        "timePlaceholder": string;
        "value": string | number | undefined;
        "valueFormat"?: GtDateTimeValueFormat;
        "valueType"?: 'string' | 'timestamp';
    }
    interface GtDialog {
        /**
          * @default 'Dialog'
         */
        "ariaLabel": string;
        /**
          * @default true
         */
        "closeOnEsc": boolean;
        /**
          * @default true
         */
        "closeOnMask": boolean;
        /**
          * @default true
         */
        "modal": boolean;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default false
         */
        "persistent": boolean;
    }
    interface GtDisclosure {
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default ''
         */
        "title": string;
    }
    interface GtDrawer {
        /**
          * @default 'Drawer'
         */
        "ariaLabel": string;
        /**
          * @default true
         */
        "closeOnEsc": boolean;
        /**
          * @default true
         */
        "closeOnMask": boolean;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default true
         */
        "overlay": boolean;
        /**
          * @default false
         */
        "persistent": boolean;
        /**
          * @default 'right'
         */
        "position": 'left' | 'right';
        /**
          * @default '400px'
         */
        "width": string;
    }
    interface GtEmptyState {
        /**
          * @default false
         */
        "compact": boolean;
        /**
          * @default ''
         */
        "description": string;
    }
    interface GtField {
        /**
          * @default ''
         */
        "error": string;
        /**
          * @default ''
         */
        "hint": string;
        /**
          * @default ''
         */
        "htmlFor": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'vertical'
         */
        "layout": 'horizontal' | 'vertical';
        /**
          * @default false
         */
        "required": boolean;
    }
    interface GtIconButton {
        /**
          * @default false
         */
        "active": boolean;
        /**
          * @default ''
         */
        "ariaLabel": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'square'
         */
        "shape": 'square' | 'circle';
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'ghost'
         */
        "variant": 'primary' | 'secondary' | 'ghost' | 'danger';
    }
    interface GtInput {
        "autocapitalize"?: string;
        "autocorrect"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        "list"?: string;
        "max"?: string;
        "min"?: string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readOnly": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        "spellcheck"?: boolean | 'true' | 'false';
        /**
          * @default '1'
         */
        "step": string;
        /**
          * @default 'text'
         */
        "type": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface GtMenu {
        /**
          * @default true
         */
        "closeOnClickOutside": boolean;
        /**
          * @default ''
         */
        "maxHeight": string;
        /**
          * @default ''
         */
        "outsideIgnoreSelector": string | string[];
        /**
          * @default false
         */
        "visible": boolean;
        /**
          * @default 0
         */
        "x": number;
        /**
          * @default 0
         */
        "y": number;
    }
    interface GtMenuDivider {
    }
    interface GtMenuItem {
        /**
          * @default false
         */
        "danger": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
    }
    interface GtPopupSurface {
        /**
          * @default ''
         */
        "ariaLabel": string;
        /**
          * @default ''
         */
        "ariaLabelledby": string;
        /**
          * @default true
         */
        "closeOnEsc": boolean;
        /**
          * @default true
         */
        "closeOnMask": boolean;
        /**
          * @default true
         */
        "closeOnOutside": boolean;
        /**
          * @default true
         */
        "fixed": boolean;
        /**
          * @default ''
         */
        "height": string | number;
        /**
          * @default ''
         */
        "maxHeight": string | number;
        /**
          * @default ''
         */
        "maxWidth": string | number;
        /**
          * @default false
         */
        "modelValue": boolean;
        /**
          * @default true
         */
        "overlay": boolean;
        /**
          * @default ''
         */
        "overlayClass": string | string[] | Record<string, boolean>;
        /**
          * @default ''
         */
        "panelClass": string | string[] | Record<string, boolean>;
        /**
          * @default ''
         */
        "panelStyle": string | Record<string, string | number>;
        /**
          * @default false
         */
        "persistent": boolean;
        /**
          * @default 'center'
         */
        "placement": GtPopupPlacement;
        /**
          * @default 'dialog'
         */
        "role": string;
        /**
          * @default 'body'
         */
        "teleportTo": string;
        /**
          * @default true
         */
        "teleported": boolean;
        /**
          * @default 'dialog'
         */
        "variant": GtPopupVariant;
        /**
          * @default ''
         */
        "width": string | number;
        /**
          * @default 'var(--ui-z-toast)'
         */
        "zIndex": string | number;
    }
    interface GtRadio {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md';
        /**
          * @default ''
         */
        "value": string;
    }
    interface GtRange {
        /**
          * @default ''
         */
        "ariaLabel": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 100
         */
        "max": number;
        /**
          * @default 0
         */
        "min": number;
        /**
          * @default 1
         */
        "step": number;
        /**
          * @default 0
         */
        "value": number;
    }
    interface GtScrollbar {
        /**
          * @default false
         */
        "alwaysVisible": boolean;
        "refresh": () => Promise<void>;
        "scrollBy": (options: ScrollToOptions) => Promise<void>;
        "scrollTo": (options: ScrollToOptions) => Promise<void>;
        /**
          * @default true
         */
        "showOnHover": boolean;
        /**
          * @default 0
         */
        "size": number;
        /**
          * @default ''
         */
        "thumbColor": string;
        /**
          * @default ''
         */
        "thumbHoverColor": string;
        /**
          * @default ''
         */
        "trackColor": string;
        "updateScrollableState": () => Promise<void>;
        /**
          * @default true
         */
        "x": boolean;
        /**
          * @default true
         */
        "y": boolean;
    }
    interface GtSelect {
        /**
          * @default 'slideScale'
         */
        "animation": 'fade' | 'slide' | 'scale' | 'slideScale';
        /**
          * @default true
         */
        "closeOnOutside": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default []
         */
        "options": GtSelectOption[];
        /**
          * @default '请选择…'
         */
        "placeholder": string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default ''
         */
        "value": string | number;
    }
    interface GtSliderField {
        /**
          * @default ''
         */
        "ariaLabel": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 100
         */
        "max": number;
        /**
          * @default 0
         */
        "min": number;
        /**
          * @default 1
         */
        "step": number;
        /**
          * @default ''
         */
        "unit": string;
        /**
          * @default 0
         */
        "value": number;
        /**
          * @default ''
         */
        "valueText": string;
    }
    interface GtStateCard {
        /**
          * @default false
         */
        "compact": boolean;
        /**
          * @default ''
         */
        "description": string;
        /**
          * @default 'info'
         */
        "state": 'loading' | 'empty' | 'error' | 'info';
    }
    interface GtSwitch {
        /**
          * @default ''
         */
        "ariaLabel": string;
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md';
    }
    interface GtTabs {
        /**
          * @default []
         */
        "items": GtTabItem[];
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default false
         */
        "stretch": boolean;
        /**
          * @default ''
         */
        "value": string;
        /**
          * @default 'line'
         */
        "variant": 'line' | 'segmented';
    }
    interface GtTextarea {
        "autocapitalize"?: string;
        "autocorrect"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        "maxLength"?: number;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readOnly": boolean;
        /**
          * @default 'vertical'
         */
        "resize": 'none' | 'both' | 'horizontal' | 'vertical';
        "rows"?: number;
        "spellcheck"?: boolean | 'true' | 'false';
        /**
          * @default ''
         */
        "value": string;
    }
    interface GtTimePicker {
        /**
          * @default true
         */
        "closeOnOutside": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 5
         */
        "minuteStep": number;
        /**
          * @default '选择时间'
         */
        "placeholder": string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default ''
         */
        "value": string;
    }
    interface GtTooltip {
        /**
          * @default ''
         */
        "content": string;
        /**
          * @default 300
         */
        "delay": number;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'top'
         */
        "placement": OverlayPlacement;
    }
}
export interface GtButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtButtonElement;
}
export interface GtCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtCheckboxElement;
}
export interface GtDatePickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtDatePickerElement;
}
export interface GtDateTimePickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtDateTimePickerElement;
}
export interface GtDialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtDialogElement;
}
export interface GtDisclosureCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtDisclosureElement;
}
export interface GtDrawerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtDrawerElement;
}
export interface GtIconButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtIconButtonElement;
}
export interface GtInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtInputElement;
}
export interface GtMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtMenuElement;
}
export interface GtMenuItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtMenuItemElement;
}
export interface GtPopupSurfaceCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtPopupSurfaceElement;
}
export interface GtRadioCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtRadioElement;
}
export interface GtRangeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtRangeElement;
}
export interface GtScrollbarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtScrollbarElement;
}
export interface GtSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtSelectElement;
}
export interface GtSliderFieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtSliderFieldElement;
}
export interface GtSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtSwitchElement;
}
export interface GtTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtTabsElement;
}
export interface GtTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtTextareaElement;
}
export interface GtTimePickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGtTimePickerElement;
}
declare global {
    interface HTMLGtButtonElementEventMap {
        "gt-click": GtButtonClickDetail;
    }
    interface HTMLGtButtonElement extends Components.GtButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtButtonElementEventMap>(type: K, listener: (this: HTMLGtButtonElement, ev: GtButtonCustomEvent<HTMLGtButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtButtonElementEventMap>(type: K, listener: (this: HTMLGtButtonElement, ev: GtButtonCustomEvent<HTMLGtButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtButtonElement: {
        prototype: HTMLGtButtonElement;
        new (): HTMLGtButtonElement;
    };
    interface HTMLGtCardElement extends Components.GtCard, HTMLStencilElement {
    }
    var HTMLGtCardElement: {
        prototype: HTMLGtCardElement;
        new (): HTMLGtCardElement;
    };
    interface HTMLGtCheckboxElementEventMap {
        "gt-change": GtCheckedChangeDetail;
    }
    interface HTMLGtCheckboxElement extends Components.GtCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtCheckboxElementEventMap>(type: K, listener: (this: HTMLGtCheckboxElement, ev: GtCheckboxCustomEvent<HTMLGtCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtCheckboxElementEventMap>(type: K, listener: (this: HTMLGtCheckboxElement, ev: GtCheckboxCustomEvent<HTMLGtCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtCheckboxElement: {
        prototype: HTMLGtCheckboxElement;
        new (): HTMLGtCheckboxElement;
    };
    interface HTMLGtDatePickerElementEventMap {
        "gt-change": GtDateChangeDetail;
        "gt-clear": void;
    }
    interface HTMLGtDatePickerElement extends Components.GtDatePicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtDatePickerElementEventMap>(type: K, listener: (this: HTMLGtDatePickerElement, ev: GtDatePickerCustomEvent<HTMLGtDatePickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtDatePickerElementEventMap>(type: K, listener: (this: HTMLGtDatePickerElement, ev: GtDatePickerCustomEvent<HTMLGtDatePickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtDatePickerElement: {
        prototype: HTMLGtDatePickerElement;
        new (): HTMLGtDatePickerElement;
    };
    interface HTMLGtDateTimePickerElementEventMap {
        "gt-change": GtDateTimeChangeDetail;
    }
    interface HTMLGtDateTimePickerElement extends Components.GtDateTimePicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtDateTimePickerElementEventMap>(type: K, listener: (this: HTMLGtDateTimePickerElement, ev: GtDateTimePickerCustomEvent<HTMLGtDateTimePickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtDateTimePickerElementEventMap>(type: K, listener: (this: HTMLGtDateTimePickerElement, ev: GtDateTimePickerCustomEvent<HTMLGtDateTimePickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtDateTimePickerElement: {
        prototype: HTMLGtDateTimePickerElement;
        new (): HTMLGtDateTimePickerElement;
    };
    interface HTMLGtDialogElementEventMap {
        "gt-open-change": GtOpenChangeDetail;
    }
    interface HTMLGtDialogElement extends Components.GtDialog, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtDialogElementEventMap>(type: K, listener: (this: HTMLGtDialogElement, ev: GtDialogCustomEvent<HTMLGtDialogElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtDialogElementEventMap>(type: K, listener: (this: HTMLGtDialogElement, ev: GtDialogCustomEvent<HTMLGtDialogElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtDialogElement: {
        prototype: HTMLGtDialogElement;
        new (): HTMLGtDialogElement;
    };
    interface HTMLGtDisclosureElementEventMap {
        "gt-open-change": GtDisclosureChangeDetail;
    }
    interface HTMLGtDisclosureElement extends Components.GtDisclosure, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtDisclosureElementEventMap>(type: K, listener: (this: HTMLGtDisclosureElement, ev: GtDisclosureCustomEvent<HTMLGtDisclosureElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtDisclosureElementEventMap>(type: K, listener: (this: HTMLGtDisclosureElement, ev: GtDisclosureCustomEvent<HTMLGtDisclosureElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtDisclosureElement: {
        prototype: HTMLGtDisclosureElement;
        new (): HTMLGtDisclosureElement;
    };
    interface HTMLGtDrawerElementEventMap {
        "gt-open-change": GtOpenChangeDetail1;
    }
    interface HTMLGtDrawerElement extends Components.GtDrawer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtDrawerElementEventMap>(type: K, listener: (this: HTMLGtDrawerElement, ev: GtDrawerCustomEvent<HTMLGtDrawerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtDrawerElementEventMap>(type: K, listener: (this: HTMLGtDrawerElement, ev: GtDrawerCustomEvent<HTMLGtDrawerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtDrawerElement: {
        prototype: HTMLGtDrawerElement;
        new (): HTMLGtDrawerElement;
    };
    interface HTMLGtEmptyStateElement extends Components.GtEmptyState, HTMLStencilElement {
    }
    var HTMLGtEmptyStateElement: {
        prototype: HTMLGtEmptyStateElement;
        new (): HTMLGtEmptyStateElement;
    };
    interface HTMLGtFieldElement extends Components.GtField, HTMLStencilElement {
    }
    var HTMLGtFieldElement: {
        prototype: HTMLGtFieldElement;
        new (): HTMLGtFieldElement;
    };
    interface HTMLGtIconButtonElementEventMap {
        "gt-click": GtIconButtonClickDetail;
    }
    interface HTMLGtIconButtonElement extends Components.GtIconButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtIconButtonElementEventMap>(type: K, listener: (this: HTMLGtIconButtonElement, ev: GtIconButtonCustomEvent<HTMLGtIconButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtIconButtonElementEventMap>(type: K, listener: (this: HTMLGtIconButtonElement, ev: GtIconButtonCustomEvent<HTMLGtIconButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtIconButtonElement: {
        prototype: HTMLGtIconButtonElement;
        new (): HTMLGtIconButtonElement;
    };
    interface HTMLGtInputElementEventMap {
        "gt-input": GtValueChangeDetail;
        "gt-change": GtValueChangeDetail;
    }
    interface HTMLGtInputElement extends Components.GtInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtInputElementEventMap>(type: K, listener: (this: HTMLGtInputElement, ev: GtInputCustomEvent<HTMLGtInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtInputElementEventMap>(type: K, listener: (this: HTMLGtInputElement, ev: GtInputCustomEvent<HTMLGtInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtInputElement: {
        prototype: HTMLGtInputElement;
        new (): HTMLGtInputElement;
    };
    interface HTMLGtMenuElementEventMap {
        "gt-close": GtMenuCloseDetail;
    }
    interface HTMLGtMenuElement extends Components.GtMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtMenuElementEventMap>(type: K, listener: (this: HTMLGtMenuElement, ev: GtMenuCustomEvent<HTMLGtMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtMenuElementEventMap>(type: K, listener: (this: HTMLGtMenuElement, ev: GtMenuCustomEvent<HTMLGtMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtMenuElement: {
        prototype: HTMLGtMenuElement;
        new (): HTMLGtMenuElement;
    };
    interface HTMLGtMenuDividerElement extends Components.GtMenuDivider, HTMLStencilElement {
    }
    var HTMLGtMenuDividerElement: {
        prototype: HTMLGtMenuDividerElement;
        new (): HTMLGtMenuDividerElement;
    };
    interface HTMLGtMenuItemElementEventMap {
        "gt-click": GtMenuItemClickDetail;
    }
    interface HTMLGtMenuItemElement extends Components.GtMenuItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtMenuItemElementEventMap>(type: K, listener: (this: HTMLGtMenuItemElement, ev: GtMenuItemCustomEvent<HTMLGtMenuItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtMenuItemElementEventMap>(type: K, listener: (this: HTMLGtMenuItemElement, ev: GtMenuItemCustomEvent<HTMLGtMenuItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtMenuItemElement: {
        prototype: HTMLGtMenuItemElement;
        new (): HTMLGtMenuItemElement;
    };
    interface HTMLGtPopupSurfaceElementEventMap {
        "gt-open-change": GtPopupOpenChangeDetail;
        "gt-open": void;
        "gt-close": void;
        "gt-mask-click": void;
        "gt-outside-click": void;
    }
    interface HTMLGtPopupSurfaceElement extends Components.GtPopupSurface, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtPopupSurfaceElementEventMap>(type: K, listener: (this: HTMLGtPopupSurfaceElement, ev: GtPopupSurfaceCustomEvent<HTMLGtPopupSurfaceElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtPopupSurfaceElementEventMap>(type: K, listener: (this: HTMLGtPopupSurfaceElement, ev: GtPopupSurfaceCustomEvent<HTMLGtPopupSurfaceElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtPopupSurfaceElement: {
        prototype: HTMLGtPopupSurfaceElement;
        new (): HTMLGtPopupSurfaceElement;
    };
    interface HTMLGtRadioElementEventMap {
        "gt-change": GtRadioChangeDetail;
    }
    interface HTMLGtRadioElement extends Components.GtRadio, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtRadioElementEventMap>(type: K, listener: (this: HTMLGtRadioElement, ev: GtRadioCustomEvent<HTMLGtRadioElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtRadioElementEventMap>(type: K, listener: (this: HTMLGtRadioElement, ev: GtRadioCustomEvent<HTMLGtRadioElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtRadioElement: {
        prototype: HTMLGtRadioElement;
        new (): HTMLGtRadioElement;
    };
    interface HTMLGtRangeElementEventMap {
        "gt-change": { value: number };
    }
    interface HTMLGtRangeElement extends Components.GtRange, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtRangeElementEventMap>(type: K, listener: (this: HTMLGtRangeElement, ev: GtRangeCustomEvent<HTMLGtRangeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtRangeElementEventMap>(type: K, listener: (this: HTMLGtRangeElement, ev: GtRangeCustomEvent<HTMLGtRangeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtRangeElement: {
        prototype: HTMLGtRangeElement;
        new (): HTMLGtRangeElement;
    };
    interface HTMLGtScrollbarElementEventMap {
        "gt-scroll": Event;
    }
    interface HTMLGtScrollbarElement extends Omit<Components.GtScrollbar, "scrollBy" | "scrollTo">, HTMLStencilElement {
        "scrollBy": (options: ScrollToOptions) => Promise<void>;
        "scrollTo": (options: ScrollToOptions) => Promise<void>;
        addEventListener<K extends keyof HTMLGtScrollbarElementEventMap>(type: K, listener: (this: HTMLGtScrollbarElement, ev: GtScrollbarCustomEvent<HTMLGtScrollbarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtScrollbarElementEventMap>(type: K, listener: (this: HTMLGtScrollbarElement, ev: GtScrollbarCustomEvent<HTMLGtScrollbarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtScrollbarElement: {
        prototype: HTMLGtScrollbarElement;
        new (): HTMLGtScrollbarElement;
    };
    interface HTMLGtSelectElementEventMap {
        "gt-change": GtSelectChangeDetail;
        "gt-focus": void;
        "gt-blur": void;
    }
    interface HTMLGtSelectElement extends Components.GtSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtSelectElementEventMap>(type: K, listener: (this: HTMLGtSelectElement, ev: GtSelectCustomEvent<HTMLGtSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtSelectElementEventMap>(type: K, listener: (this: HTMLGtSelectElement, ev: GtSelectCustomEvent<HTMLGtSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtSelectElement: {
        prototype: HTMLGtSelectElement;
        new (): HTMLGtSelectElement;
    };
    interface HTMLGtSliderFieldElementEventMap {
        "gt-change": GtSliderFieldChangeDetail;
    }
    interface HTMLGtSliderFieldElement extends Components.GtSliderField, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtSliderFieldElementEventMap>(type: K, listener: (this: HTMLGtSliderFieldElement, ev: GtSliderFieldCustomEvent<HTMLGtSliderFieldElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtSliderFieldElementEventMap>(type: K, listener: (this: HTMLGtSliderFieldElement, ev: GtSliderFieldCustomEvent<HTMLGtSliderFieldElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtSliderFieldElement: {
        prototype: HTMLGtSliderFieldElement;
        new (): HTMLGtSliderFieldElement;
    };
    interface HTMLGtStateCardElement extends Components.GtStateCard, HTMLStencilElement {
    }
    var HTMLGtStateCardElement: {
        prototype: HTMLGtStateCardElement;
        new (): HTMLGtStateCardElement;
    };
    interface HTMLGtSwitchElementEventMap {
        "gt-change": GtSwitchChangeDetail;
    }
    interface HTMLGtSwitchElement extends Components.GtSwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtSwitchElementEventMap>(type: K, listener: (this: HTMLGtSwitchElement, ev: GtSwitchCustomEvent<HTMLGtSwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtSwitchElementEventMap>(type: K, listener: (this: HTMLGtSwitchElement, ev: GtSwitchCustomEvent<HTMLGtSwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtSwitchElement: {
        prototype: HTMLGtSwitchElement;
        new (): HTMLGtSwitchElement;
    };
    interface HTMLGtTabsElementEventMap {
        "gt-change": GtTabChangeDetail;
    }
    interface HTMLGtTabsElement extends Components.GtTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtTabsElementEventMap>(type: K, listener: (this: HTMLGtTabsElement, ev: GtTabsCustomEvent<HTMLGtTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtTabsElementEventMap>(type: K, listener: (this: HTMLGtTabsElement, ev: GtTabsCustomEvent<HTMLGtTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtTabsElement: {
        prototype: HTMLGtTabsElement;
        new (): HTMLGtTabsElement;
    };
    interface HTMLGtTextareaElementEventMap {
        "gt-input": GtValueChangeDetail1;
        "gt-change": GtValueChangeDetail1;
    }
    interface HTMLGtTextareaElement extends Components.GtTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtTextareaElementEventMap>(type: K, listener: (this: HTMLGtTextareaElement, ev: GtTextareaCustomEvent<HTMLGtTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtTextareaElementEventMap>(type: K, listener: (this: HTMLGtTextareaElement, ev: GtTextareaCustomEvent<HTMLGtTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtTextareaElement: {
        prototype: HTMLGtTextareaElement;
        new (): HTMLGtTextareaElement;
    };
    interface HTMLGtTimePickerElementEventMap {
        "gt-change": GtTimeChangeDetail;
    }
    interface HTMLGtTimePickerElement extends Components.GtTimePicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGtTimePickerElementEventMap>(type: K, listener: (this: HTMLGtTimePickerElement, ev: GtTimePickerCustomEvent<HTMLGtTimePickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGtTimePickerElementEventMap>(type: K, listener: (this: HTMLGtTimePickerElement, ev: GtTimePickerCustomEvent<HTMLGtTimePickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGtTimePickerElement: {
        prototype: HTMLGtTimePickerElement;
        new (): HTMLGtTimePickerElement;
    };
    interface HTMLGtTooltipElement extends Components.GtTooltip, HTMLStencilElement {
    }
    var HTMLGtTooltipElement: {
        prototype: HTMLGtTooltipElement;
        new (): HTMLGtTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "gt-button": HTMLGtButtonElement;
        "gt-card": HTMLGtCardElement;
        "gt-checkbox": HTMLGtCheckboxElement;
        "gt-date-picker": HTMLGtDatePickerElement;
        "gt-date-time-picker": HTMLGtDateTimePickerElement;
        "gt-dialog": HTMLGtDialogElement;
        "gt-disclosure": HTMLGtDisclosureElement;
        "gt-drawer": HTMLGtDrawerElement;
        "gt-empty-state": HTMLGtEmptyStateElement;
        "gt-field": HTMLGtFieldElement;
        "gt-icon-button": HTMLGtIconButtonElement;
        "gt-input": HTMLGtInputElement;
        "gt-menu": HTMLGtMenuElement;
        "gt-menu-divider": HTMLGtMenuDividerElement;
        "gt-menu-item": HTMLGtMenuItemElement;
        "gt-popup-surface": HTMLGtPopupSurfaceElement;
        "gt-radio": HTMLGtRadioElement;
        "gt-range": HTMLGtRangeElement;
        "gt-scrollbar": HTMLGtScrollbarElement;
        "gt-select": HTMLGtSelectElement;
        "gt-slider-field": HTMLGtSliderFieldElement;
        "gt-state-card": HTMLGtStateCardElement;
        "gt-switch": HTMLGtSwitchElement;
        "gt-tabs": HTMLGtTabsElement;
        "gt-textarea": HTMLGtTextareaElement;
        "gt-time-picker": HTMLGtTimePickerElement;
        "gt-tooltip": HTMLGtTooltipElement;
    }
}
declare namespace LocalJSX {
    interface GtButton {
        /**
          * @default false
         */
        "active"?: boolean;
        /**
          * @default false
         */
        "block"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onGt-click"?: (event: GtButtonCustomEvent<GtButtonClickDetail>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'secondary'
         */
        "variant"?: 'primary' | 'secondary' | 'ghost' | 'danger';
    }
    interface GtCard {
        /**
          * @default true
         */
        "bordered"?: boolean;
        /**
          * @default false
         */
        "hoverable"?: boolean;
        /**
          * @default false
         */
        "interactive"?: boolean;
        /**
          * @default 'md'
         */
        "padding"?: 'none' | 'sm' | 'md' | 'lg';
        /**
          * @default 'md'
         */
        "radius"?: 'none' | 'sm' | 'md' | 'lg';
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'muted' | 'elevated';
    }
    interface GtCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onGt-change"?: (event: GtCheckboxCustomEvent<GtCheckedChangeDetail>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md';
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface GtDatePicker {
        /**
          * @default true
         */
        "clearable"?: boolean;
        /**
          * @default true
         */
        "closeOnOutside"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "max"?: string;
        /**
          * @default ''
         */
        "min"?: string;
        "onGt-change"?: (event: GtDatePickerCustomEvent<GtDateChangeDetail>) => void;
        "onGt-clear"?: (event: GtDatePickerCustomEvent<void>) => void;
        /**
          * @default '选择日期'
         */
        "placeholder"?: string;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface GtDateTimePicker {
        /**
          * @default true
         */
        "clearable"?: boolean;
        /**
          * @default true
         */
        "closeOnOutside"?: boolean;
        /**
          * @default '日期'
         */
        "datePlaceholder"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 5
         */
        "minuteStep"?: number;
        /**
          * @default 'datetime'
         */
        "mode"?: GtDateTimeMode;
        "onGt-change"?: (event: GtDateTimePickerCustomEvent<GtDateTimeChangeDetail>) => void;
        /**
          * @default '选择日期和时间'
         */
        "placeholder"?: string;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default '时间'
         */
        "timePlaceholder"?: string;
        "value"?: string | number | undefined;
        "valueFormat"?: GtDateTimeValueFormat;
        "valueType"?: 'string' | 'timestamp';
    }
    interface GtDialog {
        /**
          * @default 'Dialog'
         */
        "ariaLabel"?: string;
        /**
          * @default true
         */
        "closeOnEsc"?: boolean;
        /**
          * @default true
         */
        "closeOnMask"?: boolean;
        /**
          * @default true
         */
        "modal"?: boolean;
        "onGt-open-change"?: (event: GtDialogCustomEvent<GtOpenChangeDetail>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default false
         */
        "persistent"?: boolean;
    }
    interface GtDisclosure {
        "onGt-open-change"?: (event: GtDisclosureCustomEvent<GtDisclosureChangeDetail>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default ''
         */
        "title"?: string;
    }
    interface GtDrawer {
        /**
          * @default 'Drawer'
         */
        "ariaLabel"?: string;
        /**
          * @default true
         */
        "closeOnEsc"?: boolean;
        /**
          * @default true
         */
        "closeOnMask"?: boolean;
        "onGt-open-change"?: (event: GtDrawerCustomEvent<GtOpenChangeDetail1>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default true
         */
        "overlay"?: boolean;
        /**
          * @default false
         */
        "persistent"?: boolean;
        /**
          * @default 'right'
         */
        "position"?: 'left' | 'right';
        /**
          * @default '400px'
         */
        "width"?: string;
    }
    interface GtEmptyState {
        /**
          * @default false
         */
        "compact"?: boolean;
        /**
          * @default ''
         */
        "description"?: string;
    }
    interface GtField {
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default ''
         */
        "hint"?: string;
        /**
          * @default ''
         */
        "htmlFor"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default 'vertical'
         */
        "layout"?: 'horizontal' | 'vertical';
        /**
          * @default false
         */
        "required"?: boolean;
    }
    interface GtIconButton {
        /**
          * @default false
         */
        "active"?: boolean;
        /**
          * @default ''
         */
        "ariaLabel"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        "onGt-click"?: (event: GtIconButtonCustomEvent<GtIconButtonClickDetail>) => void;
        /**
          * @default 'square'
         */
        "shape"?: 'square' | 'circle';
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'ghost'
         */
        "variant"?: 'primary' | 'secondary' | 'ghost' | 'danger';
    }
    interface GtInput {
        "autocapitalize"?: string;
        "autocorrect"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "list"?: string;
        "max"?: string;
        "min"?: string;
        "onGt-change"?: (event: GtInputCustomEvent<GtValueChangeDetail>) => void;
        "onGt-input"?: (event: GtInputCustomEvent<GtValueChangeDetail>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readOnly"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        "spellcheck"?: boolean | 'true' | 'false';
        /**
          * @default '1'
         */
        "step"?: string;
        /**
          * @default 'text'
         */
        "type"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface GtMenu {
        /**
          * @default true
         */
        "closeOnClickOutside"?: boolean;
        /**
          * @default ''
         */
        "maxHeight"?: string;
        "onGt-close"?: (event: GtMenuCustomEvent<GtMenuCloseDetail>) => void;
        /**
          * @default ''
         */
        "outsideIgnoreSelector"?: string | string[];
        /**
          * @default false
         */
        "visible"?: boolean;
        /**
          * @default 0
         */
        "x"?: number;
        /**
          * @default 0
         */
        "y"?: number;
    }
    interface GtMenuDivider {
    }
    interface GtMenuItem {
        /**
          * @default false
         */
        "danger"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onGt-click"?: (event: GtMenuItemCustomEvent<GtMenuItemClickDetail>) => void;
    }
    interface GtPopupSurface {
        /**
          * @default ''
         */
        "ariaLabel"?: string;
        /**
          * @default ''
         */
        "ariaLabelledby"?: string;
        /**
          * @default true
         */
        "closeOnEsc"?: boolean;
        /**
          * @default true
         */
        "closeOnMask"?: boolean;
        /**
          * @default true
         */
        "closeOnOutside"?: boolean;
        /**
          * @default true
         */
        "fixed"?: boolean;
        /**
          * @default ''
         */
        "height"?: string | number;
        /**
          * @default ''
         */
        "maxHeight"?: string | number;
        /**
          * @default ''
         */
        "maxWidth"?: string | number;
        /**
          * @default false
         */
        "modelValue"?: boolean;
        "onGt-close"?: (event: GtPopupSurfaceCustomEvent<void>) => void;
        "onGt-mask-click"?: (event: GtPopupSurfaceCustomEvent<void>) => void;
        "onGt-open"?: (event: GtPopupSurfaceCustomEvent<void>) => void;
        "onGt-open-change"?: (event: GtPopupSurfaceCustomEvent<GtPopupOpenChangeDetail>) => void;
        "onGt-outside-click"?: (event: GtPopupSurfaceCustomEvent<void>) => void;
        /**
          * @default true
         */
        "overlay"?: boolean;
        /**
          * @default ''
         */
        "overlayClass"?: string | string[] | Record<string, boolean>;
        /**
          * @default ''
         */
        "panelClass"?: string | string[] | Record<string, boolean>;
        /**
          * @default ''
         */
        "panelStyle"?: string | Record<string, string | number>;
        /**
          * @default false
         */
        "persistent"?: boolean;
        /**
          * @default 'center'
         */
        "placement"?: GtPopupPlacement;
        /**
          * @default 'dialog'
         */
        "role"?: string;
        /**
          * @default 'body'
         */
        "teleportTo"?: string;
        /**
          * @default true
         */
        "teleported"?: boolean;
        /**
          * @default 'dialog'
         */
        "variant"?: GtPopupVariant;
        /**
          * @default ''
         */
        "width"?: string | number;
        /**
          * @default 'var(--ui-z-toast)'
         */
        "zIndex"?: string | number;
    }
    interface GtRadio {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onGt-change"?: (event: GtRadioCustomEvent<GtRadioChangeDetail>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md';
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface GtRange {
        /**
          * @default ''
         */
        "ariaLabel"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 100
         */
        "max"?: number;
        /**
          * @default 0
         */
        "min"?: number;
        "onGt-change"?: (event: GtRangeCustomEvent<{ value: number }>) => void;
        /**
          * @default 1
         */
        "step"?: number;
        /**
          * @default 0
         */
        "value"?: number;
    }
    interface GtScrollbar {
        /**
          * @default false
         */
        "alwaysVisible"?: boolean;
        "onGt-scroll"?: (event: GtScrollbarCustomEvent<Event>) => void;
        /**
          * @default true
         */
        "showOnHover"?: boolean;
        /**
          * @default 0
         */
        "size"?: number;
        /**
          * @default ''
         */
        "thumbColor"?: string;
        /**
          * @default ''
         */
        "thumbHoverColor"?: string;
        /**
          * @default ''
         */
        "trackColor"?: string;
        /**
          * @default true
         */
        "x"?: boolean;
        /**
          * @default true
         */
        "y"?: boolean;
    }
    interface GtSelect {
        /**
          * @default 'slideScale'
         */
        "animation"?: 'fade' | 'slide' | 'scale' | 'slideScale';
        /**
          * @default true
         */
        "closeOnOutside"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onGt-blur"?: (event: GtSelectCustomEvent<void>) => void;
        "onGt-change"?: (event: GtSelectCustomEvent<GtSelectChangeDetail>) => void;
        "onGt-focus"?: (event: GtSelectCustomEvent<void>) => void;
        /**
          * @default []
         */
        "options"?: GtSelectOption[];
        /**
          * @default '请选择…'
         */
        "placeholder"?: string;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default ''
         */
        "value"?: string | number;
    }
    interface GtSliderField {
        /**
          * @default ''
         */
        "ariaLabel"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default 100
         */
        "max"?: number;
        /**
          * @default 0
         */
        "min"?: number;
        "onGt-change"?: (event: GtSliderFieldCustomEvent<GtSliderFieldChangeDetail>) => void;
        /**
          * @default 1
         */
        "step"?: number;
        /**
          * @default ''
         */
        "unit"?: string;
        /**
          * @default 0
         */
        "value"?: number;
        /**
          * @default ''
         */
        "valueText"?: string;
    }
    interface GtStateCard {
        /**
          * @default false
         */
        "compact"?: boolean;
        /**
          * @default ''
         */
        "description"?: string;
        /**
          * @default 'info'
         */
        "state"?: 'loading' | 'empty' | 'error' | 'info';
    }
    interface GtSwitch {
        /**
          * @default ''
         */
        "ariaLabel"?: string;
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onGt-change"?: (event: GtSwitchCustomEvent<GtSwitchChangeDetail>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md';
    }
    interface GtTabs {
        /**
          * @default []
         */
        "items"?: GtTabItem[];
        "onGt-change"?: (event: GtTabsCustomEvent<GtTabChangeDetail>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default false
         */
        "stretch"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
        /**
          * @default 'line'
         */
        "variant"?: 'line' | 'segmented';
    }
    interface GtTextarea {
        "autocapitalize"?: string;
        "autocorrect"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "maxLength"?: number;
        "onGt-change"?: (event: GtTextareaCustomEvent<GtValueChangeDetail1>) => void;
        "onGt-input"?: (event: GtTextareaCustomEvent<GtValueChangeDetail1>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readOnly"?: boolean;
        /**
          * @default 'vertical'
         */
        "resize"?: 'none' | 'both' | 'horizontal' | 'vertical';
        "rows"?: number;
        "spellcheck"?: boolean | 'true' | 'false';
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface GtTimePicker {
        /**
          * @default true
         */
        "closeOnOutside"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 5
         */
        "minuteStep"?: number;
        "onGt-change"?: (event: GtTimePickerCustomEvent<GtTimeChangeDetail>) => void;
        /**
          * @default '选择时间'
         */
        "placeholder"?: string;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface GtTooltip {
        /**
          * @default ''
         */
        "content"?: string;
        /**
          * @default 300
         */
        "delay"?: number;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'top'
         */
        "placement"?: OverlayPlacement;
    }

    interface GtButtonAttributes {
        "variant": 'primary' | 'secondary' | 'ghost' | 'danger';
        "size": 'sm' | 'md' | 'lg';
        "disabled": boolean;
        "active": boolean;
        "block": boolean;
        "type": 'button' | 'submit' | 'reset';
    }
    interface GtCardAttributes {
        "variant": 'default' | 'muted' | 'elevated';
        "padding": 'none' | 'sm' | 'md' | 'lg';
        "radius": 'none' | 'sm' | 'md' | 'lg';
        "hoverable": boolean;
        "interactive": boolean;
        "bordered": boolean;
    }
    interface GtCheckboxAttributes {
        "checked": boolean;
        "indeterminate": boolean;
        "disabled": boolean;
        "size": 'sm' | 'md';
        "label": string;
        "name": string;
        "value": string;
    }
    interface GtDatePickerAttributes {
        "value": string;
        "placeholder": string;
        "clearable": boolean;
        "disabled": boolean;
        "size": 'sm' | 'md' | 'lg';
        "min": string;
        "max": string;
        "closeOnOutside": boolean;
    }
    interface GtDateTimePickerAttributes {
        "value": string;
        "placeholder": string;
        "datePlaceholder": string;
        "timePlaceholder": string;
        "disabled": boolean;
        "size": 'sm' | 'md' | 'lg';
        "mode": GtDateTimeMode;
        "valueFormat": GtDateTimeValueFormat;
        "valueType": 'string' | 'timestamp';
        "minuteStep": number;
        "clearable": boolean;
        "closeOnOutside": boolean;
    }
    interface GtDialogAttributes {
        "open": boolean;
        "modal": boolean;
        "closeOnMask": boolean;
        "closeOnEsc": boolean;
        "persistent": boolean;
        "ariaLabel": string;
    }
    interface GtDisclosureAttributes {
        "title": string;
        "open": boolean;
    }
    interface GtDrawerAttributes {
        "open": boolean;
        "position": 'left' | 'right';
        "width": string;
        "overlay": boolean;
        "closeOnMask": boolean;
        "closeOnEsc": boolean;
        "persistent": boolean;
        "ariaLabel": string;
    }
    interface GtEmptyStateAttributes {
        "description": string;
        "compact": boolean;
    }
    interface GtFieldAttributes {
        "label": string;
        "hint": string;
        "error": string;
        "required": boolean;
        "htmlFor": string;
        "layout": 'horizontal' | 'vertical';
    }
    interface GtIconButtonAttributes {
        "variant": 'primary' | 'secondary' | 'ghost' | 'danger';
        "size": 'sm' | 'md' | 'lg';
        "shape": 'square' | 'circle';
        "disabled": boolean;
        "active": boolean;
        "label": string;
        "ariaLabel": string;
        "type": 'button' | 'submit' | 'reset';
    }
    interface GtInputAttributes {
        "value": string;
        "type": string;
        "placeholder": string;
        "disabled": boolean;
        "readOnly": boolean;
        "size": 'sm' | 'md' | 'lg';
        "spellcheck": string;
        "autocorrect": string;
        "autocapitalize": string;
        "list": string;
        "min": string;
        "max": string;
        "step": string;
    }
    interface GtMenuAttributes {
        "visible": boolean;
        "x": number;
        "y": number;
        "closeOnClickOutside": boolean;
        "outsideIgnoreSelector": string | string[];
        "maxHeight": string;
    }
    interface GtMenuItemAttributes {
        "danger": boolean;
        "disabled": boolean;
    }
    interface GtPopupSurfaceAttributes {
        "modelValue": boolean;
        "variant": GtPopupVariant;
        "placement": GtPopupPlacement;
        "teleported": boolean;
        "teleportTo": string;
        "fixed": boolean;
        "overlay": boolean;
        "width": string;
        "maxWidth": string;
        "height": string;
        "maxHeight": string;
        "zIndex": string;
        "closeOnMask": boolean;
        "closeOnOutside": boolean;
        "closeOnEsc": boolean;
        "persistent": boolean;
        "role": string;
        "ariaLabel": string;
        "ariaLabelledby": string;
        "panelClass": string | string[] | Record<string, boolean>;
        "overlayClass": string | string[] | Record<string, boolean>;
        "panelStyle": string | Record<string, string | number>;
    }
    interface GtRadioAttributes {
        "checked": boolean;
        "disabled": boolean;
        "size": 'sm' | 'md';
        "label": string;
        "name": string;
        "value": string;
    }
    interface GtRangeAttributes {
        "value": number;
        "min": number;
        "max": number;
        "step": number;
        "disabled": boolean;
        "ariaLabel": string;
    }
    interface GtScrollbarAttributes {
        "x": boolean;
        "y": boolean;
        "showOnHover": boolean;
        "thumbColor": string;
        "thumbHoverColor": string;
        "trackColor": string;
        "alwaysVisible": boolean;
        "size": number;
    }
    interface GtSelectAttributes {
        "value": string;
        "disabled": boolean;
        "size": 'sm' | 'md' | 'lg';
        "placeholder": string;
        "animation": 'fade' | 'slide' | 'scale' | 'slideScale';
        "closeOnOutside": boolean;
    }
    interface GtSliderFieldAttributes {
        "value": number;
        "min": number;
        "max": number;
        "step": number;
        "disabled": boolean;
        "label": string;
        "ariaLabel": string;
        "valueText": string;
        "unit": string;
    }
    interface GtStateCardAttributes {
        "state": 'loading' | 'empty' | 'error' | 'info';
        "description": string;
        "compact": boolean;
    }
    interface GtSwitchAttributes {
        "checked": boolean;
        "disabled": boolean;
        "size": 'sm' | 'md';
        "ariaLabel": string;
    }
    interface GtTabsAttributes {
        "value": string;
        "variant": 'line' | 'segmented';
        "size": 'sm' | 'md' | 'lg';
        "stretch": boolean;
    }
    interface GtTextareaAttributes {
        "value": string;
        "placeholder": string;
        "disabled": boolean;
        "readOnly": boolean;
        "rows": number;
        "spellcheck": string;
        "autocorrect": string;
        "autocapitalize": string;
        "maxLength": number;
        "resize": 'none' | 'both' | 'horizontal' | 'vertical';
    }
    interface GtTimePickerAttributes {
        "value": string;
        "placeholder": string;
        "disabled": boolean;
        "size": 'sm' | 'md' | 'lg';
        "minuteStep": number;
        "closeOnOutside": boolean;
    }
    interface GtTooltipAttributes {
        "open": boolean;
        "content": string;
        "placement": OverlayPlacement;
        "delay": number;
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "gt-button": Omit<GtButton, keyof GtButtonAttributes> & { [K in keyof GtButton & keyof GtButtonAttributes]?: GtButton[K] } & { [K in keyof GtButton & keyof GtButtonAttributes as `attr:${K}`]?: GtButtonAttributes[K] } & { [K in keyof GtButton & keyof GtButtonAttributes as `prop:${K}`]?: GtButton[K] };
        "gt-card": Omit<GtCard, keyof GtCardAttributes> & { [K in keyof GtCard & keyof GtCardAttributes]?: GtCard[K] } & { [K in keyof GtCard & keyof GtCardAttributes as `attr:${K}`]?: GtCardAttributes[K] } & { [K in keyof GtCard & keyof GtCardAttributes as `prop:${K}`]?: GtCard[K] };
        "gt-checkbox": Omit<GtCheckbox, keyof GtCheckboxAttributes> & { [K in keyof GtCheckbox & keyof GtCheckboxAttributes]?: GtCheckbox[K] } & { [K in keyof GtCheckbox & keyof GtCheckboxAttributes as `attr:${K}`]?: GtCheckboxAttributes[K] } & { [K in keyof GtCheckbox & keyof GtCheckboxAttributes as `prop:${K}`]?: GtCheckbox[K] };
        "gt-date-picker": Omit<GtDatePicker, keyof GtDatePickerAttributes> & { [K in keyof GtDatePicker & keyof GtDatePickerAttributes]?: GtDatePicker[K] } & { [K in keyof GtDatePicker & keyof GtDatePickerAttributes as `attr:${K}`]?: GtDatePickerAttributes[K] } & { [K in keyof GtDatePicker & keyof GtDatePickerAttributes as `prop:${K}`]?: GtDatePicker[K] };
        "gt-date-time-picker": Omit<GtDateTimePicker, keyof GtDateTimePickerAttributes> & { [K in keyof GtDateTimePicker & keyof GtDateTimePickerAttributes]?: GtDateTimePicker[K] } & { [K in keyof GtDateTimePicker & keyof GtDateTimePickerAttributes as `attr:${K}`]?: GtDateTimePickerAttributes[K] } & { [K in keyof GtDateTimePicker & keyof GtDateTimePickerAttributes as `prop:${K}`]?: GtDateTimePicker[K] };
        "gt-dialog": Omit<GtDialog, keyof GtDialogAttributes> & { [K in keyof GtDialog & keyof GtDialogAttributes]?: GtDialog[K] } & { [K in keyof GtDialog & keyof GtDialogAttributes as `attr:${K}`]?: GtDialogAttributes[K] } & { [K in keyof GtDialog & keyof GtDialogAttributes as `prop:${K}`]?: GtDialog[K] };
        "gt-disclosure": Omit<GtDisclosure, keyof GtDisclosureAttributes> & { [K in keyof GtDisclosure & keyof GtDisclosureAttributes]?: GtDisclosure[K] } & { [K in keyof GtDisclosure & keyof GtDisclosureAttributes as `attr:${K}`]?: GtDisclosureAttributes[K] } & { [K in keyof GtDisclosure & keyof GtDisclosureAttributes as `prop:${K}`]?: GtDisclosure[K] };
        "gt-drawer": Omit<GtDrawer, keyof GtDrawerAttributes> & { [K in keyof GtDrawer & keyof GtDrawerAttributes]?: GtDrawer[K] } & { [K in keyof GtDrawer & keyof GtDrawerAttributes as `attr:${K}`]?: GtDrawerAttributes[K] } & { [K in keyof GtDrawer & keyof GtDrawerAttributes as `prop:${K}`]?: GtDrawer[K] };
        "gt-empty-state": Omit<GtEmptyState, keyof GtEmptyStateAttributes> & { [K in keyof GtEmptyState & keyof GtEmptyStateAttributes]?: GtEmptyState[K] } & { [K in keyof GtEmptyState & keyof GtEmptyStateAttributes as `attr:${K}`]?: GtEmptyStateAttributes[K] } & { [K in keyof GtEmptyState & keyof GtEmptyStateAttributes as `prop:${K}`]?: GtEmptyState[K] };
        "gt-field": Omit<GtField, keyof GtFieldAttributes> & { [K in keyof GtField & keyof GtFieldAttributes]?: GtField[K] } & { [K in keyof GtField & keyof GtFieldAttributes as `attr:${K}`]?: GtFieldAttributes[K] } & { [K in keyof GtField & keyof GtFieldAttributes as `prop:${K}`]?: GtField[K] };
        "gt-icon-button": Omit<GtIconButton, keyof GtIconButtonAttributes> & { [K in keyof GtIconButton & keyof GtIconButtonAttributes]?: GtIconButton[K] } & { [K in keyof GtIconButton & keyof GtIconButtonAttributes as `attr:${K}`]?: GtIconButtonAttributes[K] } & { [K in keyof GtIconButton & keyof GtIconButtonAttributes as `prop:${K}`]?: GtIconButton[K] };
        "gt-input": Omit<GtInput, keyof GtInputAttributes> & { [K in keyof GtInput & keyof GtInputAttributes]?: GtInput[K] } & { [K in keyof GtInput & keyof GtInputAttributes as `attr:${K}`]?: GtInputAttributes[K] } & { [K in keyof GtInput & keyof GtInputAttributes as `prop:${K}`]?: GtInput[K] };
        "gt-menu": Omit<GtMenu, keyof GtMenuAttributes> & { [K in keyof GtMenu & keyof GtMenuAttributes]?: GtMenu[K] } & { [K in keyof GtMenu & keyof GtMenuAttributes as `attr:${K}`]?: GtMenuAttributes[K] } & { [K in keyof GtMenu & keyof GtMenuAttributes as `prop:${K}`]?: GtMenu[K] };
        "gt-menu-divider": GtMenuDivider;
        "gt-menu-item": Omit<GtMenuItem, keyof GtMenuItemAttributes> & { [K in keyof GtMenuItem & keyof GtMenuItemAttributes]?: GtMenuItem[K] } & { [K in keyof GtMenuItem & keyof GtMenuItemAttributes as `attr:${K}`]?: GtMenuItemAttributes[K] } & { [K in keyof GtMenuItem & keyof GtMenuItemAttributes as `prop:${K}`]?: GtMenuItem[K] };
        "gt-popup-surface": Omit<GtPopupSurface, keyof GtPopupSurfaceAttributes> & { [K in keyof GtPopupSurface & keyof GtPopupSurfaceAttributes]?: GtPopupSurface[K] } & { [K in keyof GtPopupSurface & keyof GtPopupSurfaceAttributes as `attr:${K}`]?: GtPopupSurfaceAttributes[K] } & { [K in keyof GtPopupSurface & keyof GtPopupSurfaceAttributes as `prop:${K}`]?: GtPopupSurface[K] };
        "gt-radio": Omit<GtRadio, keyof GtRadioAttributes> & { [K in keyof GtRadio & keyof GtRadioAttributes]?: GtRadio[K] } & { [K in keyof GtRadio & keyof GtRadioAttributes as `attr:${K}`]?: GtRadioAttributes[K] } & { [K in keyof GtRadio & keyof GtRadioAttributes as `prop:${K}`]?: GtRadio[K] };
        "gt-range": Omit<GtRange, keyof GtRangeAttributes> & { [K in keyof GtRange & keyof GtRangeAttributes]?: GtRange[K] } & { [K in keyof GtRange & keyof GtRangeAttributes as `attr:${K}`]?: GtRangeAttributes[K] } & { [K in keyof GtRange & keyof GtRangeAttributes as `prop:${K}`]?: GtRange[K] };
        "gt-scrollbar": Omit<GtScrollbar, keyof GtScrollbarAttributes> & { [K in keyof GtScrollbar & keyof GtScrollbarAttributes]?: GtScrollbar[K] } & { [K in keyof GtScrollbar & keyof GtScrollbarAttributes as `attr:${K}`]?: GtScrollbarAttributes[K] } & { [K in keyof GtScrollbar & keyof GtScrollbarAttributes as `prop:${K}`]?: GtScrollbar[K] };
        "gt-select": Omit<GtSelect, keyof GtSelectAttributes> & { [K in keyof GtSelect & keyof GtSelectAttributes]?: GtSelect[K] } & { [K in keyof GtSelect & keyof GtSelectAttributes as `attr:${K}`]?: GtSelectAttributes[K] } & { [K in keyof GtSelect & keyof GtSelectAttributes as `prop:${K}`]?: GtSelect[K] };
        "gt-slider-field": Omit<GtSliderField, keyof GtSliderFieldAttributes> & { [K in keyof GtSliderField & keyof GtSliderFieldAttributes]?: GtSliderField[K] } & { [K in keyof GtSliderField & keyof GtSliderFieldAttributes as `attr:${K}`]?: GtSliderFieldAttributes[K] } & { [K in keyof GtSliderField & keyof GtSliderFieldAttributes as `prop:${K}`]?: GtSliderField[K] };
        "gt-state-card": Omit<GtStateCard, keyof GtStateCardAttributes> & { [K in keyof GtStateCard & keyof GtStateCardAttributes]?: GtStateCard[K] } & { [K in keyof GtStateCard & keyof GtStateCardAttributes as `attr:${K}`]?: GtStateCardAttributes[K] } & { [K in keyof GtStateCard & keyof GtStateCardAttributes as `prop:${K}`]?: GtStateCard[K] };
        "gt-switch": Omit<GtSwitch, keyof GtSwitchAttributes> & { [K in keyof GtSwitch & keyof GtSwitchAttributes]?: GtSwitch[K] } & { [K in keyof GtSwitch & keyof GtSwitchAttributes as `attr:${K}`]?: GtSwitchAttributes[K] } & { [K in keyof GtSwitch & keyof GtSwitchAttributes as `prop:${K}`]?: GtSwitch[K] };
        "gt-tabs": Omit<GtTabs, keyof GtTabsAttributes> & { [K in keyof GtTabs & keyof GtTabsAttributes]?: GtTabs[K] } & { [K in keyof GtTabs & keyof GtTabsAttributes as `attr:${K}`]?: GtTabsAttributes[K] } & { [K in keyof GtTabs & keyof GtTabsAttributes as `prop:${K}`]?: GtTabs[K] };
        "gt-textarea": Omit<GtTextarea, keyof GtTextareaAttributes> & { [K in keyof GtTextarea & keyof GtTextareaAttributes]?: GtTextarea[K] } & { [K in keyof GtTextarea & keyof GtTextareaAttributes as `attr:${K}`]?: GtTextareaAttributes[K] } & { [K in keyof GtTextarea & keyof GtTextareaAttributes as `prop:${K}`]?: GtTextarea[K] };
        "gt-time-picker": Omit<GtTimePicker, keyof GtTimePickerAttributes> & { [K in keyof GtTimePicker & keyof GtTimePickerAttributes]?: GtTimePicker[K] } & { [K in keyof GtTimePicker & keyof GtTimePickerAttributes as `attr:${K}`]?: GtTimePickerAttributes[K] } & { [K in keyof GtTimePicker & keyof GtTimePickerAttributes as `prop:${K}`]?: GtTimePicker[K] };
        "gt-tooltip": Omit<GtTooltip, keyof GtTooltipAttributes> & { [K in keyof GtTooltip & keyof GtTooltipAttributes]?: GtTooltip[K] } & { [K in keyof GtTooltip & keyof GtTooltipAttributes as `attr:${K}`]?: GtTooltipAttributes[K] } & { [K in keyof GtTooltip & keyof GtTooltipAttributes as `prop:${K}`]?: GtTooltip[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gt-button": LocalJSX.IntrinsicElements["gt-button"] & JSXBase.HTMLAttributes<HTMLGtButtonElement>;
            "gt-card": LocalJSX.IntrinsicElements["gt-card"] & JSXBase.HTMLAttributes<HTMLGtCardElement>;
            "gt-checkbox": LocalJSX.IntrinsicElements["gt-checkbox"] & JSXBase.HTMLAttributes<HTMLGtCheckboxElement>;
            "gt-date-picker": LocalJSX.IntrinsicElements["gt-date-picker"] & JSXBase.HTMLAttributes<HTMLGtDatePickerElement>;
            "gt-date-time-picker": LocalJSX.IntrinsicElements["gt-date-time-picker"] & JSXBase.HTMLAttributes<HTMLGtDateTimePickerElement>;
            "gt-dialog": LocalJSX.IntrinsicElements["gt-dialog"] & JSXBase.HTMLAttributes<HTMLGtDialogElement>;
            "gt-disclosure": LocalJSX.IntrinsicElements["gt-disclosure"] & JSXBase.HTMLAttributes<HTMLGtDisclosureElement>;
            "gt-drawer": LocalJSX.IntrinsicElements["gt-drawer"] & JSXBase.HTMLAttributes<HTMLGtDrawerElement>;
            "gt-empty-state": LocalJSX.IntrinsicElements["gt-empty-state"] & JSXBase.HTMLAttributes<HTMLGtEmptyStateElement>;
            "gt-field": LocalJSX.IntrinsicElements["gt-field"] & JSXBase.HTMLAttributes<HTMLGtFieldElement>;
            "gt-icon-button": LocalJSX.IntrinsicElements["gt-icon-button"] & JSXBase.HTMLAttributes<HTMLGtIconButtonElement>;
            "gt-input": LocalJSX.IntrinsicElements["gt-input"] & JSXBase.HTMLAttributes<HTMLGtInputElement>;
            "gt-menu": LocalJSX.IntrinsicElements["gt-menu"] & JSXBase.HTMLAttributes<HTMLGtMenuElement>;
            "gt-menu-divider": LocalJSX.IntrinsicElements["gt-menu-divider"] & JSXBase.HTMLAttributes<HTMLGtMenuDividerElement>;
            "gt-menu-item": LocalJSX.IntrinsicElements["gt-menu-item"] & JSXBase.HTMLAttributes<HTMLGtMenuItemElement>;
            "gt-popup-surface": LocalJSX.IntrinsicElements["gt-popup-surface"] & JSXBase.HTMLAttributes<HTMLGtPopupSurfaceElement>;
            "gt-radio": LocalJSX.IntrinsicElements["gt-radio"] & JSXBase.HTMLAttributes<HTMLGtRadioElement>;
            "gt-range": LocalJSX.IntrinsicElements["gt-range"] & JSXBase.HTMLAttributes<HTMLGtRangeElement>;
            "gt-scrollbar": LocalJSX.IntrinsicElements["gt-scrollbar"] & JSXBase.HTMLAttributes<HTMLGtScrollbarElement>;
            "gt-select": LocalJSX.IntrinsicElements["gt-select"] & JSXBase.HTMLAttributes<HTMLGtSelectElement>;
            "gt-slider-field": LocalJSX.IntrinsicElements["gt-slider-field"] & JSXBase.HTMLAttributes<HTMLGtSliderFieldElement>;
            "gt-state-card": LocalJSX.IntrinsicElements["gt-state-card"] & JSXBase.HTMLAttributes<HTMLGtStateCardElement>;
            "gt-switch": LocalJSX.IntrinsicElements["gt-switch"] & JSXBase.HTMLAttributes<HTMLGtSwitchElement>;
            "gt-tabs": LocalJSX.IntrinsicElements["gt-tabs"] & JSXBase.HTMLAttributes<HTMLGtTabsElement>;
            "gt-textarea": LocalJSX.IntrinsicElements["gt-textarea"] & JSXBase.HTMLAttributes<HTMLGtTextareaElement>;
            "gt-time-picker": LocalJSX.IntrinsicElements["gt-time-picker"] & JSXBase.HTMLAttributes<HTMLGtTimePickerElement>;
            "gt-tooltip": LocalJSX.IntrinsicElements["gt-tooltip"] & JSXBase.HTMLAttributes<HTMLGtTooltipElement>;
        }
    }
}
