// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/multi_device_clipboard.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> createMobileClipboardHost({required String dbPath}) => RustLib
    .instance
    .api
    .crateBindingsMobileClipboardCreateMobileClipboardHost(dbPath: dbPath);

Future<void> disposeMobileClipboardHost({required String hostId}) => RustLib
    .instance
    .api
    .crateBindingsMobileClipboardDisposeMobileClipboardHost(hostId: hostId);

Future<MultiDeviceClipboardDevice> getOrCreateMobileClipboardLocalDevice({
  required String hostId,
  required String name,
}) => RustLib.instance.api
    .crateBindingsMobileClipboardGetOrCreateMobileClipboardLocalDevice(
      hostId: hostId,
      name: name,
    );

Future<void> startMobileClipboardDiscovery({
  required String hostId,
  required MultiDeviceClipboardDiscoveryConfig config,
}) => RustLib.instance.api
    .crateBindingsMobileClipboardStartMobileClipboardDiscovery(
      hostId: hostId,
      config: config,
    );

Future<void> stopMobileClipboardDiscovery({required String hostId}) => RustLib
    .instance
    .api
    .crateBindingsMobileClipboardStopMobileClipboardDiscovery(hostId: hostId);

Future<List<MultiDeviceClipboardDiscoveredDevice>>
listMobileClipboardDiscoveredDevices({required String hostId}) => RustLib
    .instance
    .api
    .crateBindingsMobileClipboardListMobileClipboardDiscoveredDevices(
      hostId: hostId,
    );

Future<List<MultiDeviceClipboardDevice>> listMobileClipboardDevices({
  required String hostId,
}) => RustLib.instance.api
    .crateBindingsMobileClipboardListMobileClipboardDevices(hostId: hostId);

Future<List<MultiDeviceClipboardDeviceStatus>>
listMobileClipboardDeviceStatuses({
  required String hostId,
  required PlatformInt64 onlineWindowSeconds,
}) => RustLib.instance.api
    .crateBindingsMobileClipboardListMobileClipboardDeviceStatuses(
      hostId: hostId,
      onlineWindowSeconds: onlineWindowSeconds,
    );

Future<MultiDeviceClipboardDevice> upsertMobileClipboardDevice({
  required String hostId,
  required UpsertMultiDeviceClipboardDeviceInput input,
}) => RustLib.instance.api
    .crateBindingsMobileClipboardUpsertMobileClipboardDevice(
      hostId: hostId,
      input: input,
    );

Future<MultiDeviceClipboardDevice> setMobileClipboardDeviceTrusted({
  required String hostId,
  required String id,
  required bool trusted,
}) => RustLib.instance.api
    .crateBindingsMobileClipboardSetMobileClipboardDeviceTrusted(
      hostId: hostId,
      id: id,
      trusted: trusted,
    );

Future<void> forgetMobileClipboardDevice({
  required String hostId,
  required String id,
}) => RustLib.instance.api
    .crateBindingsMobileClipboardForgetMobileClipboardDevice(
      hostId: hostId,
      id: id,
    );

Future<List<MultiDeviceClipboardItem>> listMobileClipboardItems({
  required String hostId,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateBindingsMobileClipboardListMobileClipboardItems(
  hostId: hostId,
  limit: limit,
);

Future<MultiDeviceClipboardItem> getMobileClipboardItem({
  required String hostId,
  required String id,
}) => RustLib.instance.api.crateBindingsMobileClipboardGetMobileClipboardItem(
  hostId: hostId,
  id: id,
);

Future<MultiDeviceClipboardItem> upsertMobileClipboardItem({
  required String hostId,
  required UpsertMultiDeviceClipboardItemInput input,
}) =>
    RustLib.instance.api.crateBindingsMobileClipboardUpsertMobileClipboardItem(
      hostId: hostId,
      input: input,
    );

Future<void> deleteMobileClipboardItem({
  required String hostId,
  required String id,
}) =>
    RustLib.instance.api.crateBindingsMobileClipboardDeleteMobileClipboardItem(
      hostId: hostId,
      id: id,
    );

Future<void> clearMobileClipboardHistory({required String hostId}) => RustLib
    .instance
    .api
    .crateBindingsMobileClipboardClearMobileClipboardHistory(hostId: hostId);

Future<void> pruneMobileClipboardHistory({
  required String hostId,
  required PlatformInt64 historyLimit,
}) => RustLib.instance.api
    .crateBindingsMobileClipboardPruneMobileClipboardHistory(
      hostId: hostId,
      historyLimit: historyLimit,
    );

Future<String> computeMobileClipboardContentHash({
  required List<String> parts,
}) => RustLib.instance.api
    .crateBindingsMobileClipboardComputeMobileClipboardContentHash(
      parts: parts,
    );

Future<List<String>> classifyMobileClipboardText({required String text}) =>
    RustLib.instance.api
        .crateBindingsMobileClipboardClassifyMobileClipboardText(text: text);

Future<PlatformInt64> clampMobileClipboardSyncBytes({
  required PlatformInt64 value,
}) => RustLib.instance.api
    .crateBindingsMobileClipboardClampMobileClipboardSyncBytes(value: value);
