// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/home_layout.dart';
import '../models/multi_device_clipboard.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<HomeLayout> getMobileHomeLayout({
  required String dbPath,
  required String workspaceKey,
  required String layoutScope,
}) => RustLib.instance.api.crateBindingsMobileApiGetMobileHomeLayout(
  dbPath: dbPath,
  workspaceKey: workspaceKey,
  layoutScope: layoutScope,
);

Future<HomeLayoutCategory> saveMobileCategoryLayout({
  required String dbPath,
  required String workspaceKey,
  required String layoutScope,
  required SaveMobileHomeCategoryLayoutInput input,
}) => RustLib.instance.api.crateBindingsMobileApiSaveMobileCategoryLayout(
  dbPath: dbPath,
  workspaceKey: workspaceKey,
  layoutScope: layoutScope,
  input: input,
);

Future<HomeLayoutCategory> resetMobileCategoryLayout({
  required String dbPath,
  required String workspaceKey,
  required String layoutScope,
  required String categoryId,
}) => RustLib.instance.api.crateBindingsMobileApiResetMobileCategoryLayout(
  dbPath: dbPath,
  workspaceKey: workspaceKey,
  layoutScope: layoutScope,
  categoryId: categoryId,
);

Future<String> createMobileClipboardHost({required String dbPath}) => RustLib
    .instance
    .api
    .crateBindingsMobileApiCreateMobileClipboardHost(dbPath: dbPath);

Future<void> disposeMobileClipboardHost({required String hostId}) => RustLib
    .instance
    .api
    .crateBindingsMobileApiDisposeMobileClipboardHost(hostId: hostId);

Future<MultiDeviceClipboardDevice> getOrCreateMobileClipboardLocalDevice({
  required String hostId,
  required String name,
}) => RustLib.instance.api
    .crateBindingsMobileApiGetOrCreateMobileClipboardLocalDevice(
      hostId: hostId,
      name: name,
    );

Future<void> startMobileClipboardDiscovery({
  required String hostId,
  required MultiDeviceClipboardDiscoveryConfig config,
}) => RustLib.instance.api.crateBindingsMobileApiStartMobileClipboardDiscovery(
  hostId: hostId,
  config: config,
);

Future<void> stopMobileClipboardDiscovery({required String hostId}) => RustLib
    .instance
    .api
    .crateBindingsMobileApiStopMobileClipboardDiscovery(hostId: hostId);

Future<List<MultiDeviceClipboardDiscoveredDevice>>
listMobileClipboardDiscoveredDevices({required String hostId}) => RustLib
    .instance
    .api
    .crateBindingsMobileApiListMobileClipboardDiscoveredDevices(hostId: hostId);

Future<List<MultiDeviceClipboardDevice>> listMobileClipboardDevices({
  required String hostId,
}) => RustLib.instance.api.crateBindingsMobileApiListMobileClipboardDevices(
  hostId: hostId,
);

Future<List<MultiDeviceClipboardDeviceStatus>>
listMobileClipboardDeviceStatuses({
  required String hostId,
  required PlatformInt64 onlineWindowSeconds,
}) => RustLib.instance.api
    .crateBindingsMobileApiListMobileClipboardDeviceStatuses(
      hostId: hostId,
      onlineWindowSeconds: onlineWindowSeconds,
    );

Future<MultiDeviceClipboardDevice> upsertMobileClipboardDevice({
  required String hostId,
  required UpsertMultiDeviceClipboardDeviceInput input,
}) => RustLib.instance.api.crateBindingsMobileApiUpsertMobileClipboardDevice(
  hostId: hostId,
  input: input,
);

Future<MultiDeviceClipboardDevice> setMobileClipboardDeviceTrusted({
  required String hostId,
  required String id,
  required bool trusted,
}) =>
    RustLib.instance.api.crateBindingsMobileApiSetMobileClipboardDeviceTrusted(
      hostId: hostId,
      id: id,
      trusted: trusted,
    );

Future<void> forgetMobileClipboardDevice({
  required String hostId,
  required String id,
}) => RustLib.instance.api.crateBindingsMobileApiForgetMobileClipboardDevice(
  hostId: hostId,
  id: id,
);

Future<List<MultiDeviceClipboardItem>> listMobileClipboardItems({
  required String hostId,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateBindingsMobileApiListMobileClipboardItems(
  hostId: hostId,
  limit: limit,
);

Future<MultiDeviceClipboardItem> getMobileClipboardItem({
  required String hostId,
  required String id,
}) => RustLib.instance.api.crateBindingsMobileApiGetMobileClipboardItem(
  hostId: hostId,
  id: id,
);

Future<MultiDeviceClipboardItem> upsertMobileClipboardItem({
  required String hostId,
  required UpsertMultiDeviceClipboardItemInput input,
}) => RustLib.instance.api.crateBindingsMobileApiUpsertMobileClipboardItem(
  hostId: hostId,
  input: input,
);

Future<void> deleteMobileClipboardItem({
  required String hostId,
  required String id,
}) => RustLib.instance.api.crateBindingsMobileApiDeleteMobileClipboardItem(
  hostId: hostId,
  id: id,
);

Future<void> clearMobileClipboardHistory({required String hostId}) => RustLib
    .instance
    .api
    .crateBindingsMobileApiClearMobileClipboardHistory(hostId: hostId);

Future<void> pruneMobileClipboardHistory({
  required String hostId,
  required PlatformInt64 historyLimit,
}) => RustLib.instance.api.crateBindingsMobileApiPruneMobileClipboardHistory(
  hostId: hostId,
  historyLimit: historyLimit,
);

Future<String> computeMobileClipboardContentHash({
  required List<String> parts,
}) => RustLib.instance.api
    .crateBindingsMobileApiComputeMobileClipboardContentHash(parts: parts);

Future<List<String>> classifyMobileClipboardText({required String text}) =>
    RustLib.instance.api.crateBindingsMobileApiClassifyMobileClipboardText(
      text: text,
    );

Future<PlatformInt64> clampMobileClipboardSyncBytes({
  required PlatformInt64 value,
}) => RustLib.instance.api.crateBindingsMobileApiClampMobileClipboardSyncBytes(
  value: value,
);
